// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp, type LayerHandle, createLayerHandle, getTopLayer, isInLayerStack, type DismissableLayerEventDetail, type DismissableLayerOptions, type DismissableLayer, type DismissableLayerEvent, createDismissableLayer, type RovingFocusOptions, type RovingFocus, createRovingFocus } from "../bambi-helpers";

const COMBOBOX_ROOT = "data-bambi-combobox" as const;
const COMBOBOX_INPUT = "data-bambi-combobox-input" as const;
const COMBOBOX_TRIGGER = "data-bambi-combobox-trigger" as const;
const COMBOBOX_CONTENT = "data-bambi-combobox-content" as const;
const COMBOBOX_LIST = "data-bambi-combobox-list" as const;
const COMBOBOX_ITEM = "data-bambi-combobox-item" as const;
const COMBOBOX_EMPTY = "data-bambi-combobox-empty" as const;
const COMBOBOX_VALUE = "data-value" as const;
const COMBOBOX_INPUT_VALUE = "data-input-value" as const;
const COMBOBOX_DEFAULT_VALUE = "data-default-value" as const;
const COMBOBOX_OPEN = "data-open" as const;
const COMBOBOX_CONTROLLED = "data-controlled" as const;
const COMBOBOX_DISABLED = "data-disabled" as const;
const COMBOBOX_PLACEHOLDER = "data-placeholder" as const;
const COMBOBOX_STATE = "data-state" as const;
const COMBOBOX_EVENT_VALUE_CHANGE = "bambi:value-change" as const;
const COMBOBOX_EVENT_INPUT_VALUE_CHANGE =
  "bambi:input-value-change" as const;
const COMBOBOX_EVENT_OPEN_CHANGE = "bambi:open-change" as const;

export interface ComboboxValueChangeDetail {
  value: string;
  previousValue: string;
  source: "item" | "keyboard" | "programmatic";
}
export interface ComboboxInputValueChangeDetail {
  inputValue: string;
  previousInputValue: string;
  source: "input" | "item" | "programmatic";
}
export interface ComboboxOpenChangeDetail {
  open: boolean;
  previousOpen: boolean;
  source: "input" | "trigger" | "escape" | "outside" | "item" | "programmatic";
}


export interface ComboboxOptions {
  value?: string;
  inputValue?: string;
  defaultValue?: string;
  open?: boolean;
  controlled?: boolean;
  disabled?: boolean;
  placeholder?: string;
}
class ComboboxBehavior implements BambiBehavior {
  private static _idCounter = 0;
  private readonly root: Element;
  private options: ComboboxOptions;
  private currentValue = "";
  private currentInputValue = "";
  private currentOpen = false;
  private readonly _id: string;
  private bindAbort = new AbortController();
  private dismissableLayer: DismissableLayer | null = null;
  private rovingFocus: RovingFocus | null = null;
  constructor(root: Element, options: ComboboxOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-combobox-${++ComboboxBehavior._idCounter}`;
  }
  sync(): void {
    this.bindAbort.abort();
    this.destroyLayer();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.currentValue =
      this.options.value ??
      getAttr(
        this.root,
        COMBOBOX_VALUE,
        this.options.defaultValue ??
          getAttr(this.root, COMBOBOX_DEFAULT_VALUE, ""),
      );
    this.currentInputValue =
      this.options.inputValue ??
      getAttr(this.root, COMBOBOX_INPUT_VALUE, this.currentValue);
    this.currentOpen =
      this.options.open ?? getBoolAttr(this.root, COMBOBOX_OPEN);
    this.applyState();
    this.bindEvents();
  }
  update(options: ComboboxOptions = {}): void {
    this.options = { ...this.options, ...options };
    if (options.value !== undefined) this.currentValue = options.value;
    if (options.inputValue !== undefined)
      this.currentInputValue = options.inputValue;
    if (options.open !== undefined) this.currentOpen = options.open;
    this.applyState();
  }
  destroy(): void {
    this.bindAbort.abort();
    this.destroyLayer();
  }
  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, COMBOBOX_DISABLED);
  }
  private placeholder(): string {
    return (
      this.options.placeholder ??
      getAttr(this.root, COMBOBOX_PLACEHOLDER, "Search…")
    );
  }
  private input(): HTMLElement | null {
    const el = this.root.querySelector(`[${COMBOBOX_INPUT}]`);
    return el instanceof HTMLElement ? el : null;
  }
  private trigger(): HTMLElement | null {
    const el = this.root.querySelector(`[${COMBOBOX_TRIGGER}]`);
    return el instanceof HTMLElement ? el : null;
  }
  private content(): HTMLElement | null {
    const el = this.root.querySelector(`[${COMBOBOX_CONTENT}]`);
    return el instanceof HTMLElement ? el : null;
  }
  private list(): HTMLElement | null {
    const el = this.root.querySelector(`[${COMBOBOX_LIST}]`);
    return el instanceof HTMLElement ? el : null;
  }
  private items(): HTMLElement[] {
    return Array.from(this.root.querySelectorAll(`[${COMBOBOX_ITEM}]`)).filter(
      (el): el is HTMLElement => el instanceof HTMLElement,
    );
  }
  private visibleItems(): HTMLElement[] {
    return this.items().filter(
      (item) => !item.hidden && !getBoolAttr(item, COMBOBOX_DISABLED),
    );
  }
  private applyState(): void {
    const state = this.currentOpen ? "open" : "closed";
    this.root.setAttribute(COMBOBOX_ROOT, "");
    setAttr(this.root, COMBOBOX_VALUE, this.currentValue || null);
    setAttr(this.root, COMBOBOX_INPUT_VALUE, this.currentInputValue || null);
    setAttr(this.root, COMBOBOX_OPEN, this.currentOpen ? "true" : null);
    setAttr(this.root, COMBOBOX_STATE, state);
    setAttr(this.root, COMBOBOX_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, COMBOBOX_PLACEHOLDER, this.placeholder());
    const input = this.input();
    const trigger = this.trigger();
    const content = this.content();
    const list = this.list();
    if (input) {
      input.setAttribute(COMBOBOX_INPUT, "");
      input.setAttribute("role", "combobox");
      input.setAttribute("aria-expanded", String(this.currentOpen));
      if (input instanceof HTMLInputElement) {
        input.value = this.currentInputValue;
        input.placeholder = this.placeholder();
        input.disabled = this.disabled();
      } else {
        input.textContent = this.currentInputValue || "";
        input.contentEditable = this.disabled() ? "false" : "true";
        input.setAttribute("aria-placeholder", this.placeholder());
      }
      if (list)
        input.setAttribute("aria-controls", list.id || `${this._id}-list`);
    }
    if (trigger) {
      trigger.setAttribute(COMBOBOX_TRIGGER, "");
      if (trigger instanceof HTMLButtonElement) {
        if (!trigger.type) trigger.type = "button";
        trigger.disabled = this.disabled();
      }
    }
    if (content) {
      content.setAttribute(COMBOBOX_CONTENT, "");
      setAttr(content, COMBOBOX_STATE, state);
      content.hidden = !this.currentOpen;
    }
    if (list) {
      if (!list.id) list.id = `${this._id}-list`;
      list.setAttribute(COMBOBOX_LIST, "");
      list.setAttribute("role", "listbox");
    }
    const query = this.currentInputValue.trim().toLowerCase();
    let visibleCount = 0;
    for (const item of this.items()) {
      const checked = item.getAttribute(COMBOBOX_VALUE) === this.currentValue;
      const hidden = query
        ? !item.textContent?.toLowerCase().includes(query)
        : false;
      item.hidden = hidden;
      if (!hidden) visibleCount += 1;
      item.setAttribute("role", "option");
      item.setAttribute("aria-selected", String(checked));
      setAttr(
        item,
        COMBOBOX_STATE,
        hidden ? "hidden" : checked ? "checked" : "unchecked",
      );
      item.tabIndex = hidden ? -1 : 0;
    }
    for (const empty of this.root.querySelectorAll(`[${COMBOBOX_EMPTY}]`)) {
      empty.setAttribute(COMBOBOX_EMPTY, "");
      (empty as HTMLElement).hidden = visibleCount > 0;
    }
    this.destroyLayer();
    if (this.currentOpen && content) this.createLayer(content);
  }
  private setOpen(
    open: boolean,
    source: ComboboxOpenChangeDetail["source"],
  ): void {
    const previousOpen = this.currentOpen;
    if (previousOpen === open) return;
    this.currentOpen = open;
    this.applyState();
    dispatchBambiEvent(this.root, COMBOBOX_EVENT_OPEN_CHANGE, { open, previousOpen, source });
  }
  private setInputValue(
    inputValue: string,
    source: ComboboxInputValueChangeDetail["source"],
  ): void {
    const previousInputValue = this.currentInputValue;
    if (previousInputValue === inputValue) return;
    this.currentInputValue = inputValue;
    this.applyState();
    dispatchBambiEvent(this.root, COMBOBOX_EVENT_INPUT_VALUE_CHANGE, { inputValue, previousInputValue, source });
  }
  private setValue(
    value: string,
    source: ComboboxValueChangeDetail["source"],
  ): void {
    const previousValue = this.currentValue;
    if (previousValue === value) return;
    this.currentValue = value;
    this.setInputValue(
      this.items()
        .find((item) => item.getAttribute(COMBOBOX_VALUE) === value)
        ?.textContent?.trim() || value,
      "item",
    );
    this.applyState();
    dispatchBambiEvent(this.root, COMBOBOX_EVENT_VALUE_CHANGE, { value, previousValue, source });
  }
  private createLayer(content: HTMLElement): void {
    this.dismissableLayer = createDismissableLayer(content, {
      branches: [this.root],
      onEscapeKeyDown: () => this.setOpen(false, "escape"),
      onDismiss: () => this.setOpen(false, "outside"),
    });
    this.rovingFocus = createRovingFocus(content, {
      orientation: "vertical",
      getItems: () => this.visibleItems(),
      onFocus: (item) => item instanceof HTMLElement && item.focus(),
      onActivate: (item) => {
        const value = item.getAttribute(COMBOBOX_VALUE);
        if (value) {
          this.setValue(value, "keyboard");
          this.setOpen(false, "item");
        }
      },
    });
  }
  private destroyLayer(): void {
    this.dismissableLayer?.destroy();
    this.rovingFocus?.destroy();
    this.dismissableLayer = null;
    this.rovingFocus = null;
  }
  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    this.input()?.addEventListener(
      "input",
      (event) => {
        const target = event.target;
        if (!(target instanceof HTMLElement)) return;
        this.setInputValue(
          target instanceof HTMLInputElement
            ? target.value
            : (target.textContent ?? ""),
          "input",
        );
        this.setOpen(true, "input");
      },
      { signal },
    );
    this.trigger()?.addEventListener(
      "click",
      () => !this.disabled() && this.setOpen(!this.currentOpen, "trigger"),
      { signal },
    );
    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const item = target.closest(`[${COMBOBOX_ITEM}]`);
        if (
          !item ||
          !this.root.contains(item) ||
          getBoolAttr(item, COMBOBOX_DISABLED)
        )
          return;
        const value = item.getAttribute(COMBOBOX_VALUE);
        if (value) this.setValue(value, "item");
        this.setOpen(false, "item");
      },
      { signal },
    );
  }
}

export interface ComboboxProps extends Omit<ComboboxOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<ComboboxOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onValueChange?: (detail: ComboboxValueChangeDetail) => void;
  onInputValueChange?: (detail: ComboboxInputValueChangeDetail) => void;
  onOpenChange?: (detail: ComboboxOpenChangeDetail) => void;
}

export type ComboboxInputProps = React.ComponentPropsWithoutRef<"input">;

export interface ComboboxTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type ComboboxContentProps = React.ComponentPropsWithoutRef<"div">;

export type ComboboxListProps = React.ComponentPropsWithoutRef<"div">;

export type ComboboxItemProps = React.ComponentPropsWithoutRef<"div">;

export type ComboboxEmptyProps = React.ComponentPropsWithoutRef<"div">;

export function Combobox({
  value,
  inputValue,
  defaultValue,
  open,
  disabled,
  placeholder,
  onValueChange,
  onInputValueChange,
  onOpenChange,
  children,
  ...props
}: ComboboxProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<ComboboxBehavior | null>(null);
  const controlled = value !== undefined;
  const onValueChangeRef = React.useRef(onValueChange);
  const onInputValueChangeRef = React.useRef(onInputValueChange);
  const onOpenChangeRef = React.useRef(onOpenChange);

  React.useEffect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/combobox] Combobox received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  }, [defaultValue, value]);
  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    onInputValueChangeRef.current = onInputValueChange;
  }, [onInputValueChange]);

  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<ComboboxValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(COMBOBOX_EVENT_VALUE_CHANGE, onValueChangeHandler);
    const onInputValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<ComboboxInputValueChangeDetail>;
      onInputValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(COMBOBOX_EVENT_INPUT_VALUE_CHANGE, onInputValueChangeHandler);
    const onOpenChangeHandler = (event: Event) => {
      const e = event as CustomEvent<ComboboxOpenChangeDetail>;
      onOpenChangeRef.current?.(e.detail);
    };
    root.addEventListener(COMBOBOX_EVENT_OPEN_CHANGE, onOpenChangeHandler);

    const behavior = new ComboboxBehavior(root, {
      value,
      inputValue,
      defaultValue,
      open,
      disabled,
      placeholder,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(COMBOBOX_EVENT_VALUE_CHANGE, onValueChangeHandler);
      root.removeEventListener(COMBOBOX_EVENT_INPUT_VALUE_CHANGE, onInputValueChangeHandler);
      root.removeEventListener(COMBOBOX_EVENT_OPEN_CHANGE, onOpenChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      value,
      inputValue,
      defaultValue,
      open,
      disabled,
      placeholder,
      controlled,
    });
  }, [value, inputValue, defaultValue, open, disabled, placeholder, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [COMBOBOX_ROOT]: "" }}
      {...{ [COMBOBOX_VALUE]: value }}
      {...{ [COMBOBOX_INPUT_VALUE]: inputValue }}
      {...{ [COMBOBOX_DEFAULT_VALUE]: defaultValue }}
      {...{ [COMBOBOX_OPEN]: open ? "true" : undefined }}
      {...{ [COMBOBOX_DISABLED]: disabled ? "true" : undefined }}
      {...{ [COMBOBOX_PLACEHOLDER]: placeholder }}
      {...{ [COMBOBOX_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function ComboboxInput({ children, ...props }: ComboboxInputProps) {

  return (
    <input
      {...props}
      {...{ [COMBOBOX_INPUT]: "" }}
    >
      {children}
    </input>
  );
}

export function ComboboxTrigger({ disabled, children, ...props }: ComboboxTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [COMBOBOX_DISABLED]: disabled ? "true" : undefined }}
      {...{ [COMBOBOX_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function ComboboxContent({ children, ...props }: ComboboxContentProps) {

  return (
    <div
      {...props}
      {...{ [COMBOBOX_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function ComboboxList({ children, ...props }: ComboboxListProps) {

  return (
    <div
      {...props}
      {...{ [COMBOBOX_LIST]: "" }}
    >
      {children}
    </div>
  );
}

export function ComboboxItem({ children, ...props }: ComboboxItemProps) {

  return (
    <div
      {...props}
      {...{ [COMBOBOX_ITEM]: "" }}
    >
      {children}
    </div>
  );
}

export function ComboboxEmpty({ children, ...props }: ComboboxEmptyProps) {

  return (
    <div
      {...props}
      {...{ [COMBOBOX_EMPTY]: "" }}
    >
      {children}
    </div>
  );
}
