// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, type RovingFocusOptions, type RovingFocus, createRovingFocus } from "../bambi-helpers";

const RADIO_GROUP_ROOT = "data-bambi-radio-group" as const;
const RADIO_GROUP_ITEM = "data-bambi-radio-group-item" as const;
const RADIO_GROUP_INPUT = "data-bambi-radio-group-input" as const;
const RADIO_GROUP_INDICATOR = "data-bambi-radio-group-indicator" as const;
const RADIO_GROUP_LABEL = "data-bambi-radio-group-label" as const;
const RADIO_GROUP_VALUE = "data-value" as const;
const RADIO_GROUP_DEFAULT_VALUE = "data-default-value" as const;
const RADIO_GROUP_NAME = "data-name" as const;
const RADIO_GROUP_CONTROLLED = "data-controlled" as const;
const RADIO_GROUP_ORIENTATION = "data-orientation" as const;
const RADIO_GROUP_LOOP = "data-loop" as const;
const RADIO_GROUP_DISABLED = "data-disabled" as const;
const RADIO_GROUP_REQUIRED = "data-required" as const;
const RADIO_GROUP_INVALID = "data-invalid" as const;
const RADIO_GROUP_STATE = "data-state" as const;
const RADIO_GROUP_EVENT_VALUE_CHANGE = "bambi:value-change" as const;

export type RadioGroupOrientation = "horizontal" | "vertical";

export interface RadioGroupValueChangeDetail {
  value: string;
  previousValue: string | null;
  source: "click" | "keyboard" | "programmatic";
}


export interface RadioGroupOptions {
  value?: string;
  defaultValue?: string;
  name?: string;
  orientation?: RadioGroupOrientation;
  loop?: boolean;
  disabled?: boolean;
  required?: boolean;
  invalid?: boolean;
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
  ariaErrormessage?: string;
  controlled?: boolean;
}

function dispatchRadioGroupEvent(
  element: Element,
  detail: RadioGroupValueChangeDetail,
): void {
  element.dispatchEvent(
    new CustomEvent<RadioGroupValueChangeDetail>(
      RADIO_GROUP_EVENT_VALUE_CHANGE,
      {
        bubbles: true,
        cancelable: false,
        composed: false,
        detail,
      },
    ),
  );
}

class RadioGroupBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: RadioGroupOptions;
  private currentValue: string | null = null;
  private readonly _id: string;
  private readonly fallbackName: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private rovingFocus: RovingFocus | null = null;

  constructor(root: Element, options: RadioGroupOptions = {}) {
    this.root = root;
    this.options = options;
    this._id =
      root.id || `bambi-radio-group-${++RadioGroupBehavior._idCounter}`;
    this.fallbackName = `${this._id}-name`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
    this.bindAbort = new AbortController();

    this.syncRootAttributes();

    const initialValue =
      (this.options.value ?? getAttr(this.root, RADIO_GROUP_VALUE, "")) ||
      (this.options.defaultValue ??
        getAttr(this.root, RADIO_GROUP_DEFAULT_VALUE, "")) ||
      this.checkedInputValue() ||
      this.firstEnabledValue();

    if (initialValue) this.applyState(initialValue);
    else this.applyState(null);

    this.bindEvents();
  }

  update(options: RadioGroupOptions = {}): void {
    const prevOrientation = this.orientation();
    const prevLoop = this.loop();
    this.options = { ...this.options, ...options };
    this.syncRootAttributes();

    if (this.orientation() !== prevOrientation || this.loop() !== prevLoop) {
      this.rovingFocus?.destroy();
      this.rovingFocus = this.createRovingFocusInstance();
    }

    if (options.value !== undefined) {
      this.applyState(options.value || null);
    } else if (this.currentValue) {
      this.applyState(this.currentValue);
    } else {
      const fallback = this.firstEnabledValue();
      this.applyState(fallback);
    }
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
  }

  private syncRootAttributes(): void {
    this.root.setAttribute(RADIO_GROUP_ROOT, "");
    this.root.setAttribute("role", "radiogroup");
    setAttr(this.root, RADIO_GROUP_ORIENTATION, this.orientation());
    setAttr(this.root, RADIO_GROUP_LOOP, this.loop() ? "true" : "false");
    setAttr(this.root, RADIO_GROUP_NAME, this.name());
    setAttr(this.root, RADIO_GROUP_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, RADIO_GROUP_REQUIRED, this.required() ? "true" : null);
    setAttr(this.root, RADIO_GROUP_INVALID, this.invalid() ? "true" : null);
    setAttr(
      this.root,
      RADIO_GROUP_CONTROLLED,
      this.controlled() ? "true" : null,
    );
    setAttr(this.root, "aria-orientation", this.orientation());
    setAttr(this.root, "aria-required", this.required() ? "true" : null);
    setAttr(this.root, "aria-invalid", this.invalid() ? "true" : null);
    this.syncAriaOption("aria-label", this.options.ariaLabel);
    this.syncAriaOption("aria-labelledby", this.options.ariaLabelledby);
    this.syncAriaOption("aria-describedby", this.options.ariaDescribedby);
    this.syncAriaOption("aria-errormessage", this.options.ariaErrormessage);
  }

  private syncAriaOption(name: string, value: string | undefined): void {
    if (value !== undefined) setAttr(this.root, name, value || null);
  }

  private orientation(): RadioGroupOrientation {
    return (this.options.orientation ??
      getAttr(
        this.root,
        RADIO_GROUP_ORIENTATION,
        "vertical",
      )) as RadioGroupOrientation;
  }

  private loop(): boolean {
    if (this.options.loop !== undefined) return this.options.loop;
    const attr = this.root.getAttribute(RADIO_GROUP_LOOP);
    return attr === null ? true : attr === "true";
  }

  private name(): string {
    return (
      (this.options.name ?? getAttr(this.root, RADIO_GROUP_NAME, "")) ||
      this.fallbackName
    );
  }

  private controlled(): boolean {
    return (
      this.options.controlled ?? getBoolAttr(this.root, RADIO_GROUP_CONTROLLED)
    );
  }

  private disabled(): boolean {
    return (
      this.options.disabled ?? getBoolAttr(this.root, RADIO_GROUP_DISABLED)
    );
  }

  private required(): boolean {
    return (
      this.options.required ?? getBoolAttr(this.root, RADIO_GROUP_REQUIRED)
    );
  }

  private invalid(): boolean {
    return this.options.invalid ?? getBoolAttr(this.root, RADIO_GROUP_INVALID);
  }

  private items(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${RADIO_GROUP_ITEM}]`));
  }

  private inputs(): HTMLInputElement[] {
    return Array.from(
      this.root.querySelectorAll(`[${RADIO_GROUP_INPUT}]`),
    ).filter(
      (input): input is HTMLInputElement => input instanceof HTMLInputElement,
    );
  }

  private indicatorsFor(item: Element): Element[] {
    return Array.from(item.querySelectorAll(`[${RADIO_GROUP_INDICATOR}]`));
  }

  private inputFor(item: Element): HTMLInputElement | null {
    const input = item.querySelector(`[${RADIO_GROUP_INPUT}]`);
    return input instanceof HTMLInputElement ? input : null;
  }

  private itemForInput(input: Element): Element | null {
    return input.closest(`[${RADIO_GROUP_ITEM}]`);
  }

  private valueForItem(item: Element): string {
    return (
      item.getAttribute(RADIO_GROUP_VALUE) ?? this.inputFor(item)?.value ?? ""
    );
  }

  private checkedInputValue(): string | null {
    return this.inputs().find((input) => input.checked)?.value ?? null;
  }

  private firstEnabledValue(): string | null {
    return this.firstEnabledValueFromItems(this.items());
  }

  private firstEnabledValueFromItems(items: Element[]): string | null {
    const item = items.find((candidate) => !this.isItemDisabled(candidate));
    return item ? this.valueForItem(item) : null;
  }

  private isItemDisabled(item: Element): boolean {
    return this.disabled() || getBoolAttr(item, RADIO_GROUP_DISABLED);
  }

  private applyState(value: string | null): void {
    const selectedValue = value ?? "";
    if (!this.controlled() && value)
      setAttr(this.root, RADIO_GROUP_VALUE, value);
    if (!value && !this.controlled())
      setAttr(this.root, RADIO_GROUP_VALUE, null);
    this.currentValue = value;

    const items = this.items();
    const firstEnabledValue = value
      ? null
      : this.firstEnabledValueFromItems(items);

    for (const item of items) {
      const itemValue = this.valueForItem(item);
      const input = this.inputFor(item);
      const itemDisabled = getBoolAttr(item, RADIO_GROUP_DISABLED);
      const disabled = this.disabled() || itemDisabled;
      const checked = value !== null && itemValue === selectedValue;
      const state = checked ? "checked" : "unchecked";

      if (!item.id) item.id = `${this._id}-item-${itemValue}`;
      setAttr(item, RADIO_GROUP_VALUE, itemValue);
      setAttr(item, RADIO_GROUP_STATE, state);
      setAttr(item, RADIO_GROUP_DISABLED, itemDisabled ? "true" : null);

      if (input) {
        if (!input.id) input.id = `${this._id}-input-${itemValue}`;
        input.type = "radio";
        input.name = this.name();
        input.value = itemValue;
        input.checked = checked;
        input.disabled = disabled;
        input.required = this.required();
        input.tabIndex =
          checked || (!value && itemValue === firstEnabledValue) ? 0 : -1;
        input.setAttribute("aria-invalid", this.invalid() ? "true" : "false");
      }

      for (const indicator of this.indicatorsFor(item)) {
        setAttr(indicator, RADIO_GROUP_STATE, state);
      }

      const label = item.querySelector(`[${RADIO_GROUP_LABEL}]`);
      if (label instanceof HTMLLabelElement && input && !label.htmlFor)
        label.htmlFor = input.id;
    }
  }

  private applyValue(
    newValue: string,
    source: RadioGroupValueChangeDetail["source"],
  ): void {
    if (!newValue || newValue === this.currentValue || this.disabled()) {
      this.applyState(this.currentValue);
      return;
    }

    const previousValue = this.currentValue;
    if (!this.controlled()) {
      this.applyState(newValue);
    } else {
      this.applyState(this.currentValue);
    }

    dispatchRadioGroupEvent(this.root, {
      value: newValue,
      previousValue,
      source,
    });
  }

  private focusInput(input: Element): void {
    if (input instanceof HTMLElement) input.focus();
  }

  private createRovingFocusInstance(): RovingFocus {
    return createRovingFocus(this.root, {
      orientation: this.orientation(),
      loop: this.loop(),
      getItems: () => this.inputs(),
      isDisabled: (input) => {
        const item = this.itemForInput(input);
        return !item || this.isItemDisabled(item);
      },
      onFocus: (input) => {
        this.focusInput(input);
        const item = this.itemForInput(input);
        if (item) this.applyValue(this.valueForItem(item), "keyboard");
      },
      onActivate: (input) => {
        const item = this.itemForInput(input);
        if (item) this.applyValue(this.valueForItem(item), "keyboard");
      },
    });
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;

    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const item = target.closest(`[${RADIO_GROUP_ITEM}]`);
        if (!item || !this.root.contains(item) || this.isItemDisabled(item))
          return;
        event.preventDefault();
        this.inputFor(item)?.focus();
        this.applyValue(this.valueForItem(item), "click");
      },
      { signal },
    );

    this.root.addEventListener(
      "change",
      (event) => {
        const target = event.target;
        if (
          !(target instanceof HTMLInputElement) ||
          !target.hasAttribute(RADIO_GROUP_INPUT)
        )
          return;
        const item = this.itemForInput(target);
        if (item) this.applyValue(this.valueForItem(item), "programmatic");
      },
      { signal },
    );

    const form = this.inputs()[0]?.form;
    form?.addEventListener(
      "reset",
      () => {
        window.setTimeout(() => {
          if (this.controlled()) {
            this.applyState(this.options.value ?? this.currentValue);
          } else {
            const value =
              (this.options.defaultValue ??
                getAttr(this.root, RADIO_GROUP_DEFAULT_VALUE, "")) ||
              this.checkedInputValue() ||
              this.firstEnabledValue();
            this.applyState(value);
          }
        });
      },
      { signal },
    );

    this.rovingFocus = this.createRovingFocusInstance();
  }
}


const SsrSelectedValueContext = React.createContext<string | string[] | undefined>(undefined);
export interface RadioGroupProps extends Omit<RadioGroupOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<RadioGroupOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onValueChange?: (detail: RadioGroupValueChangeDetail) => void;
}

export interface RadioGroupItemProps extends React.ComponentPropsWithoutRef<"div"> {
  value: string;
  disabled?: boolean;
}

export type RadioGroupIndicatorProps = React.ComponentPropsWithoutRef<"span">;

export type RadioGroupLabelProps = React.ComponentPropsWithoutRef<"label">;

export function RadioGroup({
  value,
  defaultValue,
  name,
  orientation = "vertical",
  loop,
  disabled,
  required,
  invalid,
  ariaLabel,
  ariaLabelledby,
  ariaDescribedby,
  ariaErrormessage,
  onValueChange,
  children,
  ...props
}: RadioGroupProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<RadioGroupBehavior | null>(null);
  const controlled = value !== undefined;
  const selectedValue = value ?? defaultValue;
  const onValueChangeRef = React.useRef(onValueChange);

  React.useEffect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/radio-group] RadioGroup received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  }, [defaultValue, value]);
  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<RadioGroupValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(RADIO_GROUP_EVENT_VALUE_CHANGE, onValueChangeHandler);

    const behavior = new RadioGroupBehavior(root, {
      value,
      defaultValue,
      name,
      orientation,
      loop,
      disabled,
      required,
      invalid,
      ariaLabel,
      ariaLabelledby,
      ariaDescribedby,
      ariaErrormessage,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(RADIO_GROUP_EVENT_VALUE_CHANGE, onValueChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      value,
      defaultValue,
      name,
      orientation,
      loop,
      disabled,
      required,
      invalid,
      ariaLabel,
      ariaLabelledby,
      ariaDescribedby,
      ariaErrormessage,
      controlled,
    });
  }, [value, defaultValue, name, orientation, loop, disabled, required, invalid, ariaLabel, ariaLabelledby, ariaDescribedby, ariaErrormessage, controlled]);

  const rootElement = (
    <div
      {...props}
      ref={rootRef}
      {...{ [RADIO_GROUP_ROOT]: "" }}
      {...{ [RADIO_GROUP_VALUE]: value }}
      {...{ [RADIO_GROUP_DEFAULT_VALUE]: defaultValue }}
      {...{ [RADIO_GROUP_NAME]: name }}
      {...{ [RADIO_GROUP_ORIENTATION]: orientation }}
      {...{ [RADIO_GROUP_LOOP]: loop ? "true" : undefined }}
      {...{ [RADIO_GROUP_DISABLED]: disabled ? "true" : undefined }}
      {...{ [RADIO_GROUP_REQUIRED]: required ? "true" : undefined }}
      {...{ [RADIO_GROUP_INVALID]: invalid ? "true" : undefined }}
      {...{ [RADIO_GROUP_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );

  return <SsrSelectedValueContext.Provider value={selectedValue}>{rootElement}</SsrSelectedValueContext.Provider>;
}

export function RadioGroupItem({ value, disabled, children, ...props }: RadioGroupItemProps) {

  const selectedValue = React.useContext(SsrSelectedValueContext);
  const hasSelectedValue = selectedValue !== undefined;
  const isSelected = Array.isArray(selectedValue) ? selectedValue.includes(value) : selectedValue === value;
  return (
    <div
      {...props}
      {...{ [RADIO_GROUP_DISABLED]: disabled ? "true" : undefined }}
      {...{ [RADIO_GROUP_ITEM]: "" }}
      {...{ [RADIO_GROUP_VALUE]: value }}
      data-state={hasSelectedValue ? (isSelected ? "checked" : "unchecked") : undefined}
    >
      <input
        {...{ [RADIO_GROUP_INPUT]: "" }}
        type={"radio"}
        value={value}
        disabled={disabled}
        checked={hasSelectedValue ? isSelected : undefined}
        readOnly={true}
      />
      {children}
    </div>
  );
}

export function RadioGroupIndicator({ children, ...props }: RadioGroupIndicatorProps) {

  return (
    <span
      {...props}
      {...{ [RADIO_GROUP_INDICATOR]: "" }}
    >
      {children}
    </span>
  );
}

export function RadioGroupLabel({ children, ...props }: RadioGroupLabelProps) {

  return (
    <label
      {...props}
      {...{ [RADIO_GROUP_LABEL]: "" }}
    >
      {children}
    </label>
  );
}
