// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp } from "../bambi-helpers";

const CHECKBOX_ROOT = "data-bambi-checkbox" as const;
const CHECKBOX_INPUT = "data-bambi-checkbox-input" as const;
const CHECKBOX_INDICATOR = "data-bambi-checkbox-indicator" as const;
const CHECKBOX_LABEL = "data-bambi-checkbox-label" as const;
const CHECKBOX_CHECKED = "data-checked" as const;
const CHECKBOX_DEFAULT_CHECKED = "data-default-checked" as const;
const CHECKBOX_CONTROLLED = "data-controlled" as const;
const CHECKBOX_DISABLED = "data-disabled" as const;
const CHECKBOX_REQUIRED = "data-required" as const;
const CHECKBOX_INVALID = "data-invalid" as const;
const CHECKBOX_NAME = "data-name" as const;
const CHECKBOX_VALUE = "data-value" as const;
const CHECKBOX_FORM = "data-form" as const;
const CHECKBOX_STATE = "data-state" as const;
const CHECKBOX_EVENT_CHECKED_CHANGE = "bambi:checked-change" as const;

export type CheckboxChecked = boolean | "indeterminate";
export type CheckboxState = "checked" | "unchecked" | "indeterminate";

export interface CheckboxCheckedChangeDetail {
  checked: CheckboxChecked;
  previousChecked: CheckboxChecked;
  source: "click" | "keyboard" | "form-reset" | "programmatic";
}


export interface CheckboxOptions {
  as?: string;
  checked?: CheckboxChecked;
  defaultChecked?: CheckboxChecked;
  name?: string;
  value?: string;
  form?: string;
  disabled?: boolean;
  required?: boolean;
  invalid?: boolean;
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
  ariaErrormessage?: string;
  controlled?: boolean;
}

function normalizeChecked(
  value: CheckboxChecked | string | null | undefined,
): CheckboxChecked | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  if (value === true || value === "true" || value === "checked") return true;
  if (value === false || value === "false" || value === "unchecked")
    return false;
  if (value === "indeterminate") return "indeterminate";
  return Boolean(value);
}

function checkedState(checked: CheckboxChecked): CheckboxState {
  if (checked === "indeterminate") return "indeterminate";
  return checked ? "checked" : "unchecked";
}

function checkedAria(checked: CheckboxChecked): "true" | "false" | "mixed" {
  if (checked === "indeterminate") return "mixed";
  return checked ? "true" : "false";
}

function checkedAttr(checked: CheckboxChecked): string {
  if (checked === "indeterminate") return "indeterminate";
  return checked ? "true" : "false";
}

function nextChecked(checked: CheckboxChecked): CheckboxChecked {
  return checked === true ? false : true;
}

class CheckboxBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: CheckboxOptions;
  private currentChecked: CheckboxChecked = false;
  private readonly _id: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private defaultCheckedSnapshot: CheckboxChecked = false;

  constructor(root: Element, options: CheckboxOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-checkbox-${++CheckboxBehavior._idCounter}`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.ensureInput();
    this.syncRootAttributes();

    this.defaultCheckedSnapshot = this.defaultChecked();
    const initialChecked = this.checkedOption() ?? this.defaultCheckedSnapshot;
    this.applyState(initialChecked);
    this.bindEvents();
  }

  update(options: CheckboxOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.ensureInput();
    this.syncRootAttributes();
    if (options.defaultChecked !== undefined) {
      this.defaultCheckedSnapshot = this.defaultChecked();
    }
    if (options.checked !== undefined) {
      this.applyState(options.checked);
    } else {
      this.applyState(this.currentChecked);
    }
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
  }

  private checkedOption(): CheckboxChecked | undefined {
    return normalizeChecked(
      this.options.checked ?? this.root.getAttribute(CHECKBOX_CHECKED),
    );
  }

  private defaultChecked(): CheckboxChecked {
    return (
      normalizeChecked(
        this.options.defaultChecked ??
          this.root.getAttribute(CHECKBOX_DEFAULT_CHECKED),
      ) ?? false
    );
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, CHECKBOX_CONTROLLED) ||
        this.options.checked !== undefined)
    );
  }

  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, CHECKBOX_DISABLED);
  }

  private required(): boolean {
    return this.options.required ?? getBoolAttr(this.root, CHECKBOX_REQUIRED);
  }

  private invalid(): boolean {
    return this.options.invalid ?? getBoolAttr(this.root, CHECKBOX_INVALID);
  }

  private name(): string {
    return this.options.name ?? getAttr(this.root, CHECKBOX_NAME, "");
  }

  private value(): string {
    return this.options.value ?? getAttr(this.root, CHECKBOX_VALUE, "on");
  }

  private form(): string {
    return this.options.form ?? getAttr(this.root, CHECKBOX_FORM, "");
  }

  private input(): HTMLInputElement | null {
    const input = this.root.querySelector(`[${CHECKBOX_INPUT}]`);
    return input instanceof HTMLInputElement ? input : null;
  }

  private indicators(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${CHECKBOX_INDICATOR}]`));
  }

  private labels(): HTMLElement[] {
    return Array.from(this.root.querySelectorAll(`[${CHECKBOX_LABEL}]`)).filter(
      (label): label is HTMLElement => label instanceof HTMLElement,
    );
  }

  private ensureInput(): HTMLInputElement {
    const existing = this.input();
    if (existing) return existing;

    const input = document.createElement("input");
    input.type = "checkbox";
    input.tabIndex = -1;
    input.setAttribute(CHECKBOX_INPUT, "");
    input.setAttribute("aria-hidden", "true");
    input.style.position = "absolute";
    input.style.pointerEvents = "none";
    input.style.opacity = "0";
    input.style.width = "1px";
    input.style.height = "1px";
    input.style.margin = "0";
    input.style.padding = "0";
    input.style.border = "0";
    this.root.insertBefore(input, this.root.firstChild);
    return input;
  }

  private syncRootAttributes(): void {
    this.root.setAttribute(CHECKBOX_ROOT, "");
    this.root.setAttribute("role", "checkbox");
    if (
      this.root instanceof HTMLButtonElement &&
      !this.root.getAttribute("type")
    ) {
      this.root.type = "button";
    }
    setAttr(this.root, CHECKBOX_CONTROLLED, this.controlled() ? "true" : null);
    setAttr(this.root, CHECKBOX_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, CHECKBOX_REQUIRED, this.required() ? "true" : null);
    setAttr(this.root, CHECKBOX_INVALID, this.invalid() ? "true" : null);
    setAttr(this.root, CHECKBOX_NAME, this.name() || null);
    setAttr(this.root, CHECKBOX_VALUE, this.value() || null);
    setAttr(this.root, CHECKBOX_FORM, this.form() || null);
    setAttr(this.root, "aria-disabled", this.disabled() ? "true" : null);
    setAttr(this.root, "aria-required", this.required() ? "true" : null);
    setAttr(this.root, "aria-invalid", this.invalid() ? "true" : null);
    if (
      this.root instanceof HTMLElement &&
      !(this.root instanceof HTMLButtonElement)
    ) {
      this.root.tabIndex = this.disabled() ? -1 : 0;
    }
    this.syncAriaOption("aria-label", this.options.ariaLabel);
    this.syncAriaOption("aria-labelledby", this.options.ariaLabelledby);
    this.syncAriaOption("aria-describedby", this.options.ariaDescribedby);
    this.syncAriaOption("aria-errormessage", this.options.ariaErrormessage);
  }

  private syncAriaOption(name: string, value: string | undefined): void {
    if (value !== undefined) setAttr(this.root, name, value || null);
  }

  private applyState(checked: CheckboxChecked): void {
    this.currentChecked = checked;
    const state = checkedState(checked);
    const input = this.ensureInput();

    setAttr(this.root, CHECKBOX_CHECKED, checkedAttr(checked));
    setAttr(this.root, CHECKBOX_STATE, state);
    setAttr(this.root, "aria-checked", checkedAria(checked));

    input.checked = checked === true;
    input.defaultChecked = this.defaultCheckedSnapshot === true;
    input.indeterminate = checked === "indeterminate";
    input.disabled = this.disabled();
    input.required = this.required();
    input.name = this.name();
    input.value = this.value();
    if (this.form()) input.setAttribute("form", this.form());
    else input.removeAttribute("form");
    setAttr(input, CHECKBOX_STATE, state);
    setAttr(input, CHECKBOX_DISABLED, this.disabled() ? "true" : null);
    setAttr(input, CHECKBOX_REQUIRED, this.required() ? "true" : null);
    setAttr(input, CHECKBOX_INVALID, this.invalid() ? "true" : null);
    setAttr(input, "aria-invalid", this.invalid() ? "true" : null);
    this.syncAriaOption("aria-errormessage", this.options.ariaErrormessage);
    this.syncInputValidity(input);

    for (const indicator of this.indicators()) {
      setAttr(indicator, CHECKBOX_STATE, state);
      setAttr(indicator, CHECKBOX_DISABLED, this.disabled() ? "true" : null);
      indicator.setAttribute("aria-hidden", "true");
    }

    const labelIds: string[] = [];
    this.labels().forEach((label, index) => {
      if (!label.id) label.id = `${this._id}-label-${index}`;
      labelIds.push(label.id);
      setAttr(label, CHECKBOX_STATE, state);
      setAttr(label, CHECKBOX_DISABLED, this.disabled() ? "true" : null);
    });
    if (
      !this.root.getAttribute("aria-label") &&
      this.options.ariaLabelledby === undefined
    ) {
      setAttr(
        this.root,
        "aria-labelledby",
        labelIds.length > 0 ? labelIds.join(" ") : null,
      );
    }
  }

  private syncInputValidity(input: HTMLInputElement): void {
    if (this.invalid()) input.setCustomValidity("Invalid");
    else input.setCustomValidity("");
  }

  private setChecked(
    checked: CheckboxChecked,
    source: CheckboxCheckedChangeDetail["source"],
  ): void {
    if (this.disabled()) return;
    const previousChecked = this.currentChecked;
    if (previousChecked === checked) return;

    if (!this.controlled()) {
      this.applyState(checked);
    }

    dispatchBambiEvent(this.root, CHECKBOX_EVENT_CHECKED_CHANGE, {
      checked,
      previousChecked,
      source,
    });
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;

    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (
          target instanceof Element &&
          target.closest(`[${CHECKBOX_INPUT}]`)
        ) {
          event.preventDefault();
          return;
        }
        if (this.disabled()) {
          event.preventDefault();
          return;
        }
        this.setChecked(nextChecked(this.currentChecked), "click");
      },
      { signal },
    );

    this.root.addEventListener(
      "keydown",
      (event) => {
        const e = event as KeyboardEvent;
        if (e.key !== " " && e.key !== "Enter") return;
        e.preventDefault();
        this.setChecked(nextChecked(this.currentChecked), "keyboard");
      },
      { signal },
    );

    const form = this.input()?.form;
    form?.addEventListener(
      "reset",
      () => {
        queueMicrotask(() => {
          const checked = this.defaultCheckedSnapshot;
          const previousChecked = this.currentChecked;
          if (!this.controlled()) this.applyState(checked);
          if (previousChecked !== checked) {
            dispatchBambiEvent(this.root, CHECKBOX_EVENT_CHECKED_CHANGE, {
              checked,
              previousChecked,
              source: "form-reset",
            });
          }
        });
      },
      { signal },
    );
  }
}

export interface CheckboxProps extends Omit<CheckboxOptions, "controlled">, Omit<React.HTMLAttributes<HTMLElement>, keyof Omit<CheckboxOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onCheckedChange?: (detail: CheckboxCheckedChangeDetail) => void;
  [key: string]: unknown;
}

export interface CheckboxIndicatorProps extends React.ComponentPropsWithoutRef<"span"> {
  disabled?: boolean;
}

export interface CheckboxLabelProps extends React.ComponentPropsWithoutRef<"span"> {
  disabled?: boolean;
}

export function Checkbox({
  as,
  checked,
  defaultChecked,
  name,
  value = "on",
  form,
  disabled,
  required,
  invalid,
  ariaLabel,
  ariaLabelledby,
  ariaDescribedby,
  ariaErrormessage,
  onCheckedChange,
  children,
  ...props
}: CheckboxProps) {
  const rootRef = React.useRef<HTMLElement>(null);
  const behaviorRef = React.useRef<CheckboxBehavior | null>(null);
  const controlled = checked !== undefined;
  const onCheckedChangeRef = React.useRef(onCheckedChange);

  React.useEffect(() => {
    if (checked !== undefined && defaultChecked !== undefined) {
      console.warn(
        "[bambiui/checkbox] Checkbox received both `checked` and `defaultChecked`. Use `checked` for controlled mode or `defaultChecked` for uncontrolled mode, not both.",
      );
    }
  }, [defaultChecked, checked]);
  React.useEffect(() => {
    onCheckedChangeRef.current = onCheckedChange;
  }, [onCheckedChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onCheckedChangeHandler = (event: Event) => {
      const e = event as CustomEvent<CheckboxCheckedChangeDetail>;
      onCheckedChangeRef.current?.(e.detail);
    };
    root.addEventListener(CHECKBOX_EVENT_CHECKED_CHANGE, onCheckedChangeHandler);

    const behavior = new CheckboxBehavior(root, {
      as,
      checked,
      defaultChecked,
      name,
      value,
      form,
      disabled,
      required,
      invalid,
      ariaLabel,
      ariaLabelledby,
      ariaDescribedby,
      ariaErrormessage,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(CHECKBOX_EVENT_CHECKED_CHANGE, onCheckedChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, [as]);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      as,
      checked,
      defaultChecked,
      name,
      value,
      form,
      disabled,
      required,
      invalid,
      ariaLabel,
      ariaLabelledby,
      ariaDescribedby,
      ariaErrormessage,
      controlled,
    });
  }, [as, checked, defaultChecked, name, value, form, disabled, required, invalid, ariaLabel, ariaLabelledby, ariaDescribedby, ariaErrormessage, controlled]);

  const Component = (as ?? "button") as keyof React.JSX.IntrinsicElements;
  const isNativeElement = Component === "button";
  const effectiveDisabled = Boolean(disabled);

  return React.createElement(
    Component,
    {
      ...props,
      ref: rootRef,
      [CHECKBOX_ROOT]: "",
      type: isNativeElement ? ((props as { type?: string }).type ?? "button") : undefined,
      disabled: isNativeElement ? effectiveDisabled : undefined,
      "aria-disabled": !isNativeElement && effectiveDisabled ? "true" : undefined,
      "aria-busy": undefined,
      [CHECKBOX_CHECKED]: checked,
      [CHECKBOX_DEFAULT_CHECKED]: defaultChecked,
      [CHECKBOX_NAME]: name,
      [CHECKBOX_VALUE]: value,
      [CHECKBOX_FORM]: form,
      "data-disabled": effectiveDisabled ? "true" : undefined,
      [CHECKBOX_REQUIRED]: required ? "true" : undefined,
      [CHECKBOX_INVALID]: invalid ? "true" : undefined,
      [CHECKBOX_CONTROLLED]: controlled ? "true" : undefined,
    },
    children,
  );
}

export function CheckboxIndicator({ disabled, children, ...props }: CheckboxIndicatorProps) {

  return (
    <span
      {...props}
      {...{ [CHECKBOX_DISABLED]: disabled ? "true" : undefined }}
      {...{ [CHECKBOX_INDICATOR]: "" }}
    >
      {children}
    </span>
  );
}

export function CheckboxLabel({ disabled, children, ...props }: CheckboxLabelProps) {

  return (
    <span
      {...props}
      {...{ [CHECKBOX_DISABLED]: disabled ? "true" : undefined }}
      {...{ [CHECKBOX_LABEL]: "" }}
    >
      {children}
    </span>
  );
}
