// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const CONTAINER_ROOT = "data-bambi-container" as const;
const CONTAINER_SIZE = "data-size" as const;
const CONTAINER_ALIGN = "data-align" as const;

export type ContainerSize = "sm" | "md" | "lg" | "xl" | "full";
export type ContainerAlign = "start" | "center" | "end";


export interface ContainerOptions {
  size?: ContainerSize;
  align?: ContainerAlign;
}

class ContainerBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: ContainerOptions;

  constructor(root: Element, options: ContainerOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: ContainerOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(CONTAINER_ROOT, "");
    const size = this.options.size ?? getAttr(this.root, CONTAINER_SIZE, "sm") as ContainerSize;
    setAttr(this.root, CONTAINER_SIZE, size);
    const align = this.options.align ?? getAttr(this.root, CONTAINER_ALIGN, "start") as ContainerAlign;
    setAttr(this.root, CONTAINER_ALIGN, align);
  }
}

export interface ContainerProps extends ContainerOptions, Omit<React.ComponentPropsWithoutRef<"div">, keyof ContainerOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Container({
  size = "sm",
  align = "start",
  children,
  ...props
}: ContainerProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<ContainerBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new ContainerBehavior(root, {
      size,
      align,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      size,
      align,
    });
  }, [size, align]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [CONTAINER_ROOT]: "" }}
      {...{ [CONTAINER_SIZE]: size }}
      {...{ [CONTAINER_ALIGN]: align }}
    >
      {children}
    </div>
  );
}
