// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp, type LayerHandle, createLayerHandle, getTopLayer, isInLayerStack, type DismissableLayerEventDetail, type DismissableLayerOptions, type DismissableLayer, type DismissableLayerEvent, createDismissableLayer, type RovingFocusOptions, type RovingFocus, createRovingFocus } from "../bambi-helpers";

const SELECT_ROOT = "data-bambi-select" as const;
const SELECT_TRIGGER = "data-bambi-select-trigger" as const;
const SELECT_VALUE_PART = "data-bambi-select-value" as const;
const SELECT_CONTENT = "data-bambi-select-content" as const;
const SELECT_VIEWPORT = "data-bambi-select-viewport" as const;
const SELECT_ITEM = "data-bambi-select-item" as const;
const SELECT_ITEM_TEXT = "data-bambi-select-item-text" as const;
const SELECT_ITEM_INDICATOR = "data-bambi-select-item-indicator" as const;
const SELECT_LABEL = "data-bambi-select-label" as const;
const SELECT_GROUP = "data-bambi-select-group" as const;
const SELECT_SEPARATOR = "data-bambi-select-separator" as const;
const SELECT_VALUE = "data-value" as const;
const SELECT_DEFAULT_VALUE = "data-default-value" as const;
const SELECT_OPEN = "data-open" as const;
const SELECT_DEFAULT_OPEN = "data-default-open" as const;
const SELECT_CONTROLLED = "data-controlled" as const;
const SELECT_DISABLED = "data-disabled" as const;
const SELECT_NAME = "data-name" as const;
const SELECT_REQUIRED = "data-required" as const;
const SELECT_PLACEHOLDER = "data-placeholder" as const;
const SELECT_STATE = "data-state" as const;
const SELECT_EVENT_VALUE_CHANGE = "bambi:value-change" as const;
const SELECT_EVENT_OPEN_CHANGE = "bambi:open-change" as const;

export interface SelectValueChangeDetail { value: string; previousValue: string; source: "item" | "keyboard" | "programmatic"; }
export interface SelectOpenChangeDetail { open: boolean; previousOpen: boolean; source: "trigger" | "escape" | "outside" | "item" | "programmatic"; }


export interface SelectOptions { value?: string; defaultValue?: string; open?: boolean; defaultOpen?: boolean; controlled?: boolean; disabled?: boolean; name?: string; required?: boolean; placeholder?: string; }

class SelectBehavior implements BambiBehavior {
  private static _idCounter = 0;
  private readonly root: Element;
  private options: SelectOptions;
  private currentValue = "";
  private currentOpen = false;
  private readonly _id: string;
  private bindAbort = new AbortController();
  private dismissableLayer: DismissableLayer | null = null;
  private rovingFocus: RovingFocus | null = null;

  constructor(root: Element, options: SelectOptions = {}) { this.root = root; this.options = options; this._id = root.id || `bambi-select-${++SelectBehavior._idCounter}`; }
  sync(): void { this.bindAbort.abort(); this.destroyLayer(); this.bindAbort = new AbortController(); if (!this.root.id) this.root.id = this._id; this.currentValue = this.optionValue() ?? this.defaultValue(); this.currentOpen = this.optionOpen() ?? this.defaultOpen(); this.applyState(); this.bindEvents(); }
  update(options: SelectOptions = {}): void { this.options = { ...this.options, ...options }; if (options.value !== undefined) this.currentValue = options.value; if (options.open !== undefined) this.currentOpen = options.open; this.applyState(); }
  destroy(): void { this.bindAbort.abort(); this.destroyLayer(); }

  private controlled(): boolean { return this.options.controlled ?? (getBoolAttr(this.root, SELECT_CONTROLLED) || this.options.value !== undefined); }
  private disabled(): boolean { return this.options.disabled ?? getBoolAttr(this.root, SELECT_DISABLED); }
  private optionValue(): string | undefined { if (this.options.value !== undefined) return this.options.value; const attr = this.root.getAttribute(SELECT_VALUE); return attr ?? undefined; }
  private defaultValue(): string { return this.options.defaultValue ?? getAttr(this.root, SELECT_DEFAULT_VALUE, ""); }
  private optionOpen(): boolean | undefined { if (this.options.open !== undefined) return this.options.open; return this.root.hasAttribute(SELECT_OPEN) ? getBoolAttr(this.root, SELECT_OPEN) : undefined; }
  private defaultOpen(): boolean { return this.options.defaultOpen ?? getBoolAttr(this.root, SELECT_DEFAULT_OPEN); }
  private placeholder(): string { return this.options.placeholder ?? getAttr(this.root, SELECT_PLACEHOLDER, "Select…"); }
  private name(): string { return this.options.name ?? getAttr(this.root, SELECT_NAME, ""); }
  private required(): boolean { return this.options.required ?? getBoolAttr(this.root, SELECT_REQUIRED); }
  private trigger(): HTMLElement | null { const el = this.root.querySelector(`[${SELECT_TRIGGER}]`); return el instanceof HTMLElement ? el : null; }
  private content(): HTMLElement | null { const el = this.root.querySelector(`[${SELECT_CONTENT}]`); return el instanceof HTMLElement ? el : null; }
  private items(): HTMLElement[] { return Array.from(this.root.querySelectorAll(`[${SELECT_ITEM}]`)).filter((el): el is HTMLElement => el instanceof HTMLElement); }

  private applyState(): void {
    const state = this.currentOpen ? "open" : "closed";
    this.root.setAttribute(SELECT_ROOT, "");
    setAttr(this.root, SELECT_VALUE, this.currentValue || null); setAttr(this.root, SELECT_OPEN, this.currentOpen ? "true" : null); setAttr(this.root, SELECT_STATE, state); setAttr(this.root, SELECT_DISABLED, this.disabled() ? "true" : null); setAttr(this.root, SELECT_NAME, this.name() || null); setAttr(this.root, SELECT_REQUIRED, this.required() ? "true" : null); setAttr(this.root, SELECT_PLACEHOLDER, this.placeholder() || null);
    const trigger = this.trigger(); const content = this.content();
    if (trigger) { if (!trigger.id) trigger.id = `${this._id}-trigger`; trigger.setAttribute(SELECT_TRIGGER, ""); trigger.setAttribute("aria-haspopup", "listbox"); trigger.setAttribute("aria-expanded", String(this.currentOpen)); if (content) trigger.setAttribute("aria-controls", content.id || `${this._id}-content`); if (trigger instanceof HTMLButtonElement) { if (!trigger.type) trigger.type = "button"; trigger.disabled = this.disabled(); } }
    if (content) { if (!content.id) content.id = `${this._id}-content`; content.setAttribute(SELECT_CONTENT, ""); content.setAttribute("role", "listbox"); content.setAttribute("aria-labelledby", trigger?.id ?? ""); setAttr(content, SELECT_STATE, state); content.hidden = !this.currentOpen; }
    const selected = this.items().find((item) => item.getAttribute(SELECT_VALUE) === this.currentValue);
    for (const part of this.root.querySelectorAll(`[${SELECT_VALUE_PART}]`)) { part.textContent = selected?.textContent?.trim() || this.placeholder(); setAttr(part, SELECT_STATE, this.currentValue ? "checked" : "unchecked"); }
    for (const item of this.items()) { const checked = item.getAttribute(SELECT_VALUE) === this.currentValue; item.setAttribute("role", "option"); item.setAttribute("aria-selected", String(checked)); setAttr(item, SELECT_STATE, checked ? "checked" : "unchecked"); setAttr(item, SELECT_DISABLED, getBoolAttr(item, SELECT_DISABLED) ? "true" : null); item.tabIndex = checked ? 0 : -1; for (const text of item.querySelectorAll(`[${SELECT_ITEM_TEXT}]`)) text.setAttribute(SELECT_ITEM_TEXT, ""); for (const indicator of item.querySelectorAll(`[${SELECT_ITEM_INDICATOR}]`)) { indicator.setAttribute(SELECT_ITEM_INDICATOR, ""); setAttr(indicator, SELECT_STATE, checked ? "checked" : "unchecked"); } }
    this.destroyLayer(); if (this.currentOpen && content) this.createLayer(content);
  }

  private setOpen(open: boolean, source: SelectOpenChangeDetail["source"]): void { const previousOpen = this.currentOpen; if (previousOpen === open) return; this.currentOpen = open; this.applyState(); dispatchBambiEvent(this.root, SELECT_EVENT_OPEN_CHANGE, { open, previousOpen, source }); }
  private setValue(value: string, source: SelectValueChangeDetail["source"]): void { const previousValue = this.currentValue; if (previousValue === value) return; if (!this.controlled()) this.currentValue = value; this.applyState(); dispatchBambiEvent(this.root, SELECT_EVENT_VALUE_CHANGE, { value, previousValue, source }); }
  private createLayer(content: HTMLElement): void { this.dismissableLayer = createDismissableLayer(content, { branches: [this.root], onEscapeKeyDown: () => this.setOpen(false, "escape"), onDismiss: () => this.setOpen(false, "outside") }); this.rovingFocus = createRovingFocus(content, { orientation: "vertical", getItems: () => this.items(), isDisabled: (item) => getBoolAttr(item, SELECT_DISABLED), onFocus: (item) => item instanceof HTMLElement && item.focus(), onActivate: (item) => { const value = item.getAttribute(SELECT_VALUE); if (value) { this.setValue(value, "keyboard"); this.setOpen(false, "item"); } } }); }
  private destroyLayer(): void { this.dismissableLayer?.destroy(); this.rovingFocus?.destroy(); this.dismissableLayer = null; this.rovingFocus = null; }
  private bindEvents(): void { const signal = this.bindAbort.signal; this.root.addEventListener("click", (event) => { const target = event.target; if (!(target instanceof Element)) return; const trigger = target.closest(`[${SELECT_TRIGGER}]`); if (trigger && this.root.contains(trigger)) { if (!this.disabled()) this.setOpen(!this.currentOpen, "trigger"); return; } const item = target.closest(`[${SELECT_ITEM}]`); if (item && this.root.contains(item) && !getBoolAttr(item, SELECT_DISABLED)) { const value = item.getAttribute(SELECT_VALUE); if (value) this.setValue(value, "item"); this.setOpen(false, "item"); } }, { signal }); }
}

export interface SelectProps extends Omit<SelectOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<SelectOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onValueChange?: (detail: SelectValueChangeDetail) => void;
  onOpenChange?: (detail: SelectOpenChangeDetail) => void;
}

export interface SelectTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type SelectValuePartProps = React.ComponentPropsWithoutRef<"span">;

export type SelectContentProps = React.ComponentPropsWithoutRef<"div">;

export type SelectViewportProps = React.ComponentPropsWithoutRef<"div">;

export type SelectItemProps = React.ComponentPropsWithoutRef<"div">;

export type SelectItemTextProps = React.ComponentPropsWithoutRef<"span">;

export type SelectItemIndicatorProps = React.ComponentPropsWithoutRef<"span">;

export type SelectLabelProps = React.ComponentPropsWithoutRef<"div">;

export type SelectGroupProps = React.ComponentPropsWithoutRef<"div">;

export type SelectSeparatorProps = React.ComponentPropsWithoutRef<"div">;

export function Select({
  value,
  defaultValue,
  open,
  defaultOpen,
  disabled,
  name,
  required,
  placeholder,
  onValueChange,
  onOpenChange,
  children,
  ...props
}: SelectProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<SelectBehavior | null>(null);
  const controlled = value !== undefined;
  const onValueChangeRef = React.useRef(onValueChange);
  const onOpenChangeRef = React.useRef(onOpenChange);

  React.useEffect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/select] Select received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  }, [defaultValue, value]);
  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<SelectValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(SELECT_EVENT_VALUE_CHANGE, onValueChangeHandler);
    const onOpenChangeHandler = (event: Event) => {
      const e = event as CustomEvent<SelectOpenChangeDetail>;
      onOpenChangeRef.current?.(e.detail);
    };
    root.addEventListener(SELECT_EVENT_OPEN_CHANGE, onOpenChangeHandler);

    const behavior = new SelectBehavior(root, {
      value,
      defaultValue,
      open,
      defaultOpen,
      disabled,
      name,
      required,
      placeholder,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(SELECT_EVENT_VALUE_CHANGE, onValueChangeHandler);
      root.removeEventListener(SELECT_EVENT_OPEN_CHANGE, onOpenChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      value,
      defaultValue,
      open,
      defaultOpen,
      disabled,
      name,
      required,
      placeholder,
      controlled,
    });
  }, [value, defaultValue, open, defaultOpen, disabled, name, required, placeholder, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [SELECT_ROOT]: "" }}
      {...{ [SELECT_VALUE]: value }}
      {...{ [SELECT_DEFAULT_VALUE]: defaultValue }}
      {...{ [SELECT_OPEN]: open ? "true" : undefined }}
      {...{ [SELECT_DEFAULT_OPEN]: defaultOpen ? "true" : undefined }}
      {...{ [SELECT_DISABLED]: disabled ? "true" : undefined }}
      {...{ [SELECT_NAME]: name }}
      {...{ [SELECT_REQUIRED]: required ? "true" : undefined }}
      {...{ [SELECT_PLACEHOLDER]: placeholder }}
      {...{ [SELECT_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function SelectTrigger({ disabled, children, ...props }: SelectTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [SELECT_DISABLED]: disabled ? "true" : undefined }}
      {...{ [SELECT_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function SelectValuePart({ children, ...props }: SelectValuePartProps) {

  return (
    <span
      {...props}
      {...{ [SELECT_VALUE_PART]: "" }}
    >
      {children}
    </span>
  );
}

export function SelectContent({ children, ...props }: SelectContentProps) {

  return (
    <div
      {...props}
      {...{ [SELECT_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function SelectViewport({ children, ...props }: SelectViewportProps) {

  return (
    <div
      {...props}
      {...{ [SELECT_VIEWPORT]: "" }}
    >
      {children}
    </div>
  );
}

export function SelectItem({ children, ...props }: SelectItemProps) {

  return (
    <div
      {...props}
      {...{ [SELECT_ITEM]: "" }}
    >
      {children}
    </div>
  );
}

export function SelectItemText({ children, ...props }: SelectItemTextProps) {

  return (
    <span
      {...props}
      {...{ [SELECT_ITEM_TEXT]: "" }}
    >
      {children}
    </span>
  );
}

export function SelectItemIndicator({ children, ...props }: SelectItemIndicatorProps) {

  return (
    <span
      {...props}
      {...{ [SELECT_ITEM_INDICATOR]: "" }}
    >
      {children}
    </span>
  );
}

export function SelectLabel({ children, ...props }: SelectLabelProps) {

  return (
    <div
      {...props}
      {...{ [SELECT_LABEL]: "" }}
    >
      {children}
    </div>
  );
}

export function SelectGroup({ children, ...props }: SelectGroupProps) {

  return (
    <div
      {...props}
      {...{ [SELECT_GROUP]: "" }}
    >
      {children}
    </div>
  );
}

export function SelectSeparator({ children, ...props }: SelectSeparatorProps) {

  return (
    <div
      {...props}
      {...{ [SELECT_SEPARATOR]: "" }}
    >
      {children}
    </div>
  );
}
