// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const CODE_ROOT = "data-bambi-code" as const;
const CODE_VARIANT = "data-variant" as const;
const CODE_SIZE = "data-size" as const;

export type CodeVariant = "inline" | "block";
export type CodeSize = "sm" | "md" | "lg";


export interface CodeOptions {
  variant?: CodeVariant;
  size?: CodeSize;
}

class CodeBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: CodeOptions;

  constructor(root: Element, options: CodeOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: CodeOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(CODE_ROOT, "");
    const variant = this.options.variant ?? getAttr(this.root, CODE_VARIANT, "inline") as CodeVariant;
    setAttr(this.root, CODE_VARIANT, variant);
    const size = this.options.size ?? getAttr(this.root, CODE_SIZE, "sm") as CodeSize;
    setAttr(this.root, CODE_SIZE, size);
  }
}

export interface CodeProps extends CodeOptions, Omit<React.ComponentPropsWithoutRef<"code">, keyof CodeOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Code({
  variant = "inline",
  size = "sm",
  children,
  ...props
}: CodeProps) {
  const rootRef = React.useRef<HTMLElement>(null);
  const behaviorRef = React.useRef<CodeBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new CodeBehavior(root, {
      variant,
      size,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      variant,
      size,
    });
  }, [variant, size]);

  return (
    <code
      {...props}
      ref={rootRef}
      {...{ [CODE_ROOT]: "" }}
      {...{ [CODE_VARIANT]: variant }}
      {...{ [CODE_SIZE]: size }}
    >
      {children}
    </code>
  );
}
