// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp } from "../bambi-helpers";

const SLIDER_ROOT = "data-bambi-slider" as const;
const SLIDER_TRACK = "data-bambi-slider-track" as const;
const SLIDER_RANGE = "data-bambi-slider-range" as const;
const SLIDER_THUMB = "data-bambi-slider-thumb" as const;
const SLIDER_INPUT = "data-bambi-slider-input" as const;
const SLIDER_VALUE = "data-value" as const;
const SLIDER_DEFAULT_VALUE = "data-default-value" as const;
const SLIDER_CONTROLLED = "data-controlled" as const;
const SLIDER_MIN = "data-min" as const;
const SLIDER_MAX = "data-max" as const;
const SLIDER_STEP = "data-step" as const;
const SLIDER_MIN_STEPS_BETWEEN_THUMBS = "data-min-steps-between-thumbs" as const;
const SLIDER_ORIENTATION = "data-orientation" as const;
const SLIDER_DIR = "data-dir" as const;
const SLIDER_INVERTED = "data-inverted" as const;
const SLIDER_DISABLED = "data-disabled" as const;
const SLIDER_NAME = "data-name" as const;
const SLIDER_FORM = "data-form" as const;
const SLIDER_STATE = "data-state" as const;
const SLIDER_EVENT_VALUE_CHANGE = "bambi:value-change" as const;
const SLIDER_EVENT_VALUE_COMMIT = "bambi:value-commit" as const;

export type SliderOrientation = "horizontal" | "vertical";
export type SliderDir = "ltr" | "rtl";

export interface SliderValueChangeDetail {
  value: number[];
  previousValue: number[];
  activeThumbIndex: number;
  source: "pointer" | "keyboard" | "programmatic";
}

export interface SliderValueCommitDetail {
  value: number[];
  previousValue: number[];
  activeThumbIndex: number;
  source: "pointer" | "keyboard";
}


export interface SliderOptions {
  value?: string | number | number[];
  defaultValue?: string | number | number[];
  controlled?: boolean;
  min?: string | number;
  max?: string | number;
  step?: string | number;
  minStepsBetweenThumbs?: string | number;
  orientation?: SliderOrientation;
  dir?: SliderDir;
  inverted?: boolean;
  disabled?: boolean;
  name?: string;
  form?: string;
}

function parseNumber(
  value: string | number | undefined,
  fallback: number,
): number {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : fallback;
}

function serializeValue(value: number[]): string {
  return value.join(",");
}

function parseValue(
  value: string | number | number[] | null | undefined,
): number[] | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  if (Array.isArray(value)) return value.map(Number).filter(Number.isFinite);
  if (typeof value === "number")
    return Number.isFinite(value) ? [value] : undefined;
  const values = value
    .split(",")
    .map((part) => Number(part.trim()))
    .filter(Number.isFinite);
  return values.length > 0 ? values : undefined;
}

function decimalPlaces(value: number): number {
  const text = String(value);
  const decimal = text.includes(".") ? (text.split(".")[1]?.length ?? 0) : 0;
  const exponent = text.includes("e-") ? Number(text.split("e-")[1]) : 0;
  return Math.max(decimal, exponent);
}

class SliderBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: SliderOptions;
  private currentValue: number[] = [0];
  private readonly _id: string;
  private bindAbort = new AbortController();
  private activeThumbIndex = 0;
  private commitSnapshot: number[] = [0];

  constructor(root: Element, options: SliderOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-slider-${++SliderBehavior._idCounter}`;
  }

  sync(): void {
    this.bindAbort.abort();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    const initial = this.optionValue() ?? this.defaultValue();
    this.currentValue = this.normalizeValues(initial);
    this.applyState();
    this.bindEvents();
  }

  update(options: SliderOptions = {}): void {
    this.options = { ...this.options, ...options };
    if (options.value !== undefined)
      this.currentValue = this.normalizeValues(
        parseValue(options.value) ?? this.currentValue,
      );
    this.applyState();
  }

  destroy(): void {
    this.bindAbort.abort();
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, SLIDER_CONTROLLED) ||
        this.options.value !== undefined)
    );
  }

  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, SLIDER_DISABLED);
  }

  private min(): number {
    return parseNumber(
      this.options.min ?? getAttr(this.root, SLIDER_MIN, "0"),
      0,
    );
  }

  private max(): number {
    return parseNumber(
      this.options.max ?? getAttr(this.root, SLIDER_MAX, "100"),
      100,
    );
  }

  private step(): number {
    return Math.max(
      parseNumber(this.options.step ?? getAttr(this.root, SLIDER_STEP, "1"), 1),
      0.000001,
    );
  }

  private minStepsBetweenThumbs(): number {
    return Math.max(
      parseNumber(
        this.options.minStepsBetweenThumbs ??
          getAttr(this.root, SLIDER_MIN_STEPS_BETWEEN_THUMBS, "0"),
        0,
      ),
      0,
    );
  }

  private orientation(): SliderOrientation {
    const orientation =
      this.options.orientation ??
      getAttr(this.root, SLIDER_ORIENTATION, "horizontal");
    return orientation === "vertical" ? "vertical" : "horizontal";
  }

  private dir(): SliderDir {
    const dir = this.options.dir ?? getAttr(this.root, SLIDER_DIR, "ltr");
    return dir === "rtl" ? "rtl" : "ltr";
  }

  private inverted(): boolean {
    return this.options.inverted ?? getBoolAttr(this.root, SLIDER_INVERTED);
  }

  private name(): string {
    return this.options.name ?? getAttr(this.root, SLIDER_NAME, "");
  }

  private form(): string {
    return this.options.form ?? getAttr(this.root, SLIDER_FORM, "");
  }

  private optionValue(): number[] | undefined {
    return parseValue(
      this.options.value ?? this.root.getAttribute(SLIDER_VALUE),
    );
  }

  private defaultValue(): number[] {
    return (
      parseValue(
        this.options.defaultValue ??
          this.root.getAttribute(SLIDER_DEFAULT_VALUE),
      ) ?? [this.min()]
    );
  }

  private track(): HTMLElement | null {
    const track = this.root.querySelector(`[${SLIDER_TRACK}]`);
    return track instanceof HTMLElement ? track : null;
  }

  private range(): HTMLElement | null {
    const range = this.root.querySelector(`[${SLIDER_RANGE}]`);
    return range instanceof HTMLElement ? range : null;
  }

  private thumbs(): HTMLElement[] {
    return Array.from(this.root.querySelectorAll(`[${SLIDER_THUMB}]`)).filter(
      (thumb): thumb is HTMLElement => thumb instanceof HTMLElement,
    );
  }

  private normalizeValues(values: number[]): number[] {
    const min = this.min();
    const max = this.max();
    const spacing = this.minStepsBetweenThumbs() * this.step();
    const rounded = values.length > 0 ? values : [min];
    const sorted = rounded
      .map((value) => this.roundValue(value))
      .sort((a, b) => a - b);
    for (let index = 0; index < sorted.length; index += 1) {
      const lower = index === 0 ? min : sorted[index - 1] + spacing;
      const upper =
        index === sorted.length - 1 ? max : sorted[index + 1] - spacing;
      sorted[index] = clamp(sorted[index], lower, upper);
    }
    return sorted;
  }

  private roundValue(value: number): number {
    const min = this.min();
    const max = this.max();
    const step = this.step();
    const rounded = Math.round((value - min) / step) * step + min;
    return Number(clamp(rounded, min, max).toFixed(decimalPlaces(step)));
  }

  private percent(value: number): number {
    const min = this.min();
    const max = this.max();
    if (max === min) return 0;
    return ((value - min) / (max - min)) * 100;
  }

  private valueFromPointer(event: PointerEvent): number {
    const track = this.track();
    if (!track) return this.currentValue[this.activeThumbIndex] ?? this.min();
    const rect = track.getBoundingClientRect();
    const raw =
      this.orientation() === "vertical"
        ? (rect.bottom - event.clientY) / rect.height
        : (event.clientX - rect.left) / rect.width;
    const directionAdjusted =
      this.orientation() === "horizontal" && this.dir() === "rtl"
        ? 1 - raw
        : raw;
    const invertedAdjusted = this.inverted()
      ? 1 - directionAdjusted
      : directionAdjusted;
    return this.roundValue(
      this.min() + clamp(invertedAdjusted, 0, 1) * (this.max() - this.min()),
    );
  }

  private nearestThumbIndex(value: number): number {
    let nearest = 0;
    let distance = Number.POSITIVE_INFINITY;
    this.currentValue.forEach((candidate, index) => {
      const nextDistance = Math.abs(candidate - value);
      if (nextDistance < distance) {
        nearest = index;
        distance = nextDistance;
      }
    });
    return nearest;
  }

  private applyState(): void {
    const values = this.currentValue;
    this.root.setAttribute(SLIDER_ROOT, "");
    setAttr(this.root, SLIDER_VALUE, serializeValue(values));
    setAttr(this.root, SLIDER_CONTROLLED, this.controlled() ? "true" : null);
    setAttr(this.root, SLIDER_MIN, String(this.min()));
    setAttr(this.root, SLIDER_MAX, String(this.max()));
    setAttr(this.root, SLIDER_STEP, String(this.step()));
    setAttr(
      this.root,
      SLIDER_MIN_STEPS_BETWEEN_THUMBS,
      String(this.minStepsBetweenThumbs()),
    );
    setAttr(this.root, SLIDER_ORIENTATION, this.orientation());
    setAttr(this.root, SLIDER_DIR, this.dir());
    setAttr(this.root, SLIDER_INVERTED, this.inverted() ? "true" : null);
    setAttr(this.root, SLIDER_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, SLIDER_NAME, this.name() || null);
    setAttr(this.root, SLIDER_FORM, this.form() || null);
    setAttr(this.root, SLIDER_STATE, this.disabled() ? "inactive" : "active");

    const track = this.track();
    track?.setAttribute(SLIDER_TRACK, "");
    const range = this.range();
    if (range) this.positionRange(range);
    this.syncThumbs();
    this.syncInputs();
  }

  private positionRange(range: HTMLElement): void {
    range.setAttribute(SLIDER_RANGE, "");
    const percentages = this.currentValue.map((value) => this.percent(value));
    const start = percentages.length > 1 ? Math.min(...percentages) : 0;
    const end =
      percentages.length > 1 ? Math.max(...percentages) : (percentages[0] ?? 0);
    if (this.orientation() === "vertical") {
      range.style.bottom = `${start}%`;
      range.style.height = `${Math.max(0, end - start)}%`;
      range.style.left = "";
      range.style.width = "";
    } else {
      range.style.left = `${start}%`;
      range.style.width = `${Math.max(0, end - start)}%`;
      range.style.bottom = "";
      range.style.height = "";
    }
  }

  private syncThumbs(): void {
    const thumbs = this.thumbs();
    thumbs.forEach((thumb, index) => {
      const value =
        this.currentValue[index] ??
        this.currentValue[this.currentValue.length - 1] ??
        this.min();
      thumb.setAttribute(SLIDER_THUMB, "");
      thumb.setAttribute("role", "slider");
      thumb.tabIndex = this.disabled() ? -1 : 0;
      thumb.setAttribute("aria-valuemin", String(this.min()));
      thumb.setAttribute("aria-valuemax", String(this.max()));
      thumb.setAttribute("aria-valuenow", String(value));
      thumb.setAttribute("aria-orientation", this.orientation());
      setAttr(thumb, SLIDER_DISABLED, this.disabled() ? "true" : null);
      setAttr(
        thumb,
        SLIDER_STATE,
        index === this.activeThumbIndex ? "active" : "inactive",
      );
      const percent = this.percent(value);
      if (this.orientation() === "vertical") {
        thumb.style.bottom = `${percent}%`;
        thumb.style.left = "";
      } else {
        thumb.style.left = `${percent}%`;
        thumb.style.bottom = "";
      }
    });
  }

  private syncInputs(): void {
    const inputs = Array.from(
      this.root.querySelectorAll(`[${SLIDER_INPUT}]`),
    ).filter(
      (input): input is HTMLInputElement => input instanceof HTMLInputElement,
    );
    while (inputs.length < this.currentValue.length) {
      const input = document.createElement("input");
      input.type = "hidden";
      input.setAttribute(SLIDER_INPUT, "");
      this.root.appendChild(input);
      inputs.push(input);
    }
    inputs.forEach((input, index) => {
      input.value = String(this.currentValue[index] ?? "");
      input.name = this.name();
      input.disabled = this.disabled();
      if (this.form()) input.setAttribute("form", this.form());
      else input.removeAttribute("form");
    });
  }

  private setValue(
    next: number[],
    activeThumbIndex: number,
    source: SliderValueChangeDetail["source"],
  ): void {
    const previousValue = [...this.currentValue];
    const value = this.normalizeValues(next);
    if (serializeValue(previousValue) === serializeValue(value)) return;
    this.activeThumbIndex = activeThumbIndex;
    if (!this.controlled()) {
      this.currentValue = value;
      this.applyState();
    }
    dispatchBambiEvent(this.root, SLIDER_EVENT_VALUE_CHANGE, {
      value,
      previousValue,
      activeThumbIndex,
      source,
    });
  }

  private commit(source: SliderValueCommitDetail["source"]): void {
    const value = [...this.currentValue];
    const previousValue = [...this.commitSnapshot];
    dispatchBambiEvent(this.root, SLIDER_EVENT_VALUE_COMMIT, {
      value,
      previousValue,
      activeThumbIndex: this.activeThumbIndex,
      source,
    });
  }

  private stepValue(index: number, delta: number): void {
    const next = [...this.currentValue];
    next[index] = (next[index] ?? this.min()) + delta;
    this.setValue(next, index, "keyboard");
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    this.root.addEventListener(
      "pointerdown",
      (event) => {
        const e = event as PointerEvent;
        if (this.disabled()) return;
        const target = e.target;
        if (!(target instanceof Element)) return;
        if (!target.closest(`[${SLIDER_TRACK}], [${SLIDER_THUMB}]`)) return;
        e.preventDefault();
        const value = this.valueFromPointer(e);
        this.activeThumbIndex = this.nearestThumbIndex(value);
        this.commitSnapshot = [...this.currentValue];
        this.setValue(
          Object.assign([...this.currentValue], {
            [this.activeThumbIndex]: value,
          }),
          this.activeThumbIndex,
          "pointer",
        );
        const onMove = (moveEvent: PointerEvent) => {
          this.setValue(
            Object.assign([...this.currentValue], {
              [this.activeThumbIndex]: this.valueFromPointer(moveEvent),
            }),
            this.activeThumbIndex,
            "pointer",
          );
        };
        const onUp = () => {
          this.root.ownerDocument.removeEventListener("pointermove", onMove);
          this.root.ownerDocument.removeEventListener("pointerup", onUp);
          this.commit("pointer");
        };
        this.root.ownerDocument.addEventListener("pointermove", onMove);
        this.root.ownerDocument.addEventListener("pointerup", onUp, {
          once: true,
        });
      },
      { signal },
    );

    this.root.addEventListener(
      "keydown",
      (event) => {
        const e = event as KeyboardEvent;
        const target = e.target;
        if (
          this.disabled() ||
          !(target instanceof Element) ||
          !target.hasAttribute(SLIDER_THUMB)
        )
          return;
        const thumbs = this.thumbs();
        const index = Math.max(0, thumbs.indexOf(target as HTMLElement));
        const multiplier = e.shiftKey ? 10 : 1;
        const page = this.step() * 10;
        let handled = true;
        this.commitSnapshot = [...this.currentValue];
        if (e.key === "Home")
          this.setValue(
            Object.assign([...this.currentValue], { [index]: this.min() }),
            index,
            "keyboard",
          );
        else if (e.key === "End")
          this.setValue(
            Object.assign([...this.currentValue], { [index]: this.max() }),
            index,
            "keyboard",
          );
        else if (e.key === "PageUp") this.stepValue(index, page);
        else if (e.key === "PageDown") this.stepValue(index, -page);
        else if (e.key === "ArrowRight" || e.key === "ArrowUp")
          this.stepValue(
            index,
            this.step() *
              multiplier *
              (this.dir() === "rtl" && e.key === "ArrowRight" ? -1 : 1),
          );
        else if (e.key === "ArrowLeft" || e.key === "ArrowDown")
          this.stepValue(
            index,
            -this.step() *
              multiplier *
              (this.dir() === "rtl" && e.key === "ArrowLeft" ? -1 : 1),
          );
        else handled = false;
        if (handled) {
          e.preventDefault();
          this.commit("keyboard");
        }
      },
      { signal },
    );
  }
}

export interface SliderProps extends Omit<SliderOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<SliderOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onValueChange?: (detail: SliderValueChangeDetail) => void;
  onValueCommit?: (detail: SliderValueCommitDetail) => void;
}

export type SliderTrackProps = React.ComponentPropsWithoutRef<"span">;

export type SliderRangeProps = React.ComponentPropsWithoutRef<"span">;

export interface SliderThumbProps extends React.ComponentPropsWithoutRef<"span"> {
  disabled?: boolean;
}

export function Slider({
  value,
  defaultValue,
  min = "0",
  max = "100",
  step = "1",
  minStepsBetweenThumbs = "0",
  orientation = "horizontal",
  dir = "ltr",
  inverted,
  disabled,
  name,
  form,
  onValueChange,
  onValueCommit,
  children,
  ...props
}: SliderProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<SliderBehavior | null>(null);
  const controlled = value !== undefined;
  const onValueChangeRef = React.useRef(onValueChange);
  const onValueCommitRef = React.useRef(onValueCommit);

  React.useEffect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/slider] Slider received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  }, [defaultValue, value]);
  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    onValueCommitRef.current = onValueCommit;
  }, [onValueCommit]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<SliderValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(SLIDER_EVENT_VALUE_CHANGE, onValueChangeHandler);
    const onValueCommitHandler = (event: Event) => {
      const e = event as CustomEvent<SliderValueCommitDetail>;
      onValueCommitRef.current?.(e.detail);
    };
    root.addEventListener(SLIDER_EVENT_VALUE_COMMIT, onValueCommitHandler);

    const behavior = new SliderBehavior(root, {
      value,
      defaultValue,
      min,
      max,
      step,
      minStepsBetweenThumbs,
      orientation,
      dir,
      inverted,
      disabled,
      name,
      form,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(SLIDER_EVENT_VALUE_CHANGE, onValueChangeHandler);
      root.removeEventListener(SLIDER_EVENT_VALUE_COMMIT, onValueCommitHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      value,
      defaultValue,
      min,
      max,
      step,
      minStepsBetweenThumbs,
      orientation,
      dir,
      inverted,
      disabled,
      name,
      form,
      controlled,
    });
  }, [value, defaultValue, min, max, step, minStepsBetweenThumbs, orientation, dir, inverted, disabled, name, form, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [SLIDER_ROOT]: "" }}
      {...{ [SLIDER_VALUE]: value }}
      {...{ [SLIDER_DEFAULT_VALUE]: defaultValue }}
      {...{ [SLIDER_MIN]: min }}
      {...{ [SLIDER_MAX]: max }}
      {...{ [SLIDER_STEP]: step }}
      {...{ [SLIDER_MIN_STEPS_BETWEEN_THUMBS]: minStepsBetweenThumbs }}
      {...{ [SLIDER_ORIENTATION]: orientation }}
      {...{ [SLIDER_DIR]: dir }}
      {...{ [SLIDER_INVERTED]: inverted ? "true" : undefined }}
      {...{ [SLIDER_DISABLED]: disabled ? "true" : undefined }}
      {...{ [SLIDER_NAME]: name }}
      {...{ [SLIDER_FORM]: form }}
      {...{ [SLIDER_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function SliderTrack({ children, ...props }: SliderTrackProps) {

  return (
    <span
      {...props}
      {...{ [SLIDER_TRACK]: "" }}
    >
      {children}
    </span>
  );
}

export function SliderRange({ children, ...props }: SliderRangeProps) {

  return (
    <span
      {...props}
      {...{ [SLIDER_RANGE]: "" }}
    >
      {children}
    </span>
  );
}

export function SliderThumb({ disabled, children, ...props }: SliderThumbProps) {

  return (
    <span
      {...props}
      {...{ [SLIDER_DISABLED]: disabled ? "true" : undefined }}
      {...{ [SLIDER_THUMB]: "" }}
    >
      {children}
    </span>
  );
}
