// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp, type LayerHandle, createLayerHandle, getTopLayer, isInLayerStack, type DismissableLayerEventDetail, type DismissableLayerOptions, type DismissableLayer, type DismissableLayerEvent, createDismissableLayer, type FocusScopeOptions, type FocusScope, getFocusableElements, createFocusScope, type ScrollLock, createScrollLock } from "../bambi-helpers";

const POPOVER_ROOT = "data-bambi-popover" as const;
const POPOVER_TRIGGER = "data-bambi-popover-trigger" as const;
const POPOVER_ANCHOR = "data-bambi-popover-anchor" as const;
const POPOVER_CONTENT = "data-bambi-popover-content" as const;
const POPOVER_CLOSE = "data-bambi-popover-close" as const;
const POPOVER_ARROW = "data-bambi-popover-arrow" as const;
const POPOVER_OPEN = "data-open" as const;
const POPOVER_DEFAULT_OPEN = "data-default-open" as const;
const POPOVER_CONTROLLED = "data-controlled" as const;
const POPOVER_MODAL = "data-modal" as const;
const POPOVER_DISABLED = "data-disabled" as const;
const POPOVER_SIDE = "data-side" as const;
const POPOVER_ALIGN = "data-align" as const;
const POPOVER_SIDE_OFFSET = "data-side-offset" as const;
const POPOVER_ALIGN_OFFSET = "data-align-offset" as const;
const POPOVER_COLLISION_PADDING = "data-collision-padding" as const;
const POPOVER_COLLISION_BOUNDARY = "data-collision-boundary" as const;
const POPOVER_SIDE_FALLBACKS = "data-side-fallbacks" as const;
const POPOVER_AVOID_COLLISIONS = "data-avoid-collisions" as const;
const POPOVER_STICKY = "data-sticky" as const;
const POPOVER_HIDE_WHEN_DETACHED = "data-hide-when-detached" as const;
const POPOVER_PORTAL = "data-portal" as const;
const POPOVER_PORTAL_CONTAINER = "data-portal-container" as const;
const POPOVER_STATE = "data-state" as const;
const POPOVER_EVENT_OPEN_CHANGE = "bambi:open-change" as const;

export type PopoverSide = "top" | "right" | "bottom" | "left";
export type PopoverAlign = "start" | "center" | "end";
export type PopoverSticky = "partial" | "always";

export interface PopoverOpenChangeDetail {
  open: boolean;
  previousOpen: boolean;
  source: "trigger" | "close" | "escape" | "outside" | "programmatic";
}


type PopoverPrimitiveReferenceTypes =
  | LayerHandle
  | DismissableLayerEventDetail
  | DismissableLayerOptions
  | DismissableLayerEvent
  | FocusScopeOptions;

const popoverPrimitiveReferenceTypes: PopoverPrimitiveReferenceTypes | null =
  null;
const popoverPrimitiveReferenceValues = [
  createLayerHandle,
  getTopLayer,
  isInLayerStack,
  getFocusableElements,
] as const;
void popoverPrimitiveReferenceTypes;
void popoverPrimitiveReferenceValues;

export interface PopoverOptions {
  open?: boolean;
  defaultOpen?: boolean;
  controlled?: boolean;
  modal?: boolean;
  disabled?: boolean;
  side?: PopoverSide;
  align?: PopoverAlign;
  sideOffset?: string;
  alignOffset?: string;
  collisionPadding?: string;
  collisionBoundary?: string;
  sideFallbacks?: string;
  avoidCollisions?: boolean;
  sticky?: PopoverSticky;
  hideWhenDetached?: boolean;
  portal?: boolean;
  portalContainer?: string;
}

function oppositeSide(side: PopoverSide): PopoverSide {
  if (side === "top") return "bottom";
  if (side === "bottom") return "top";
  if (side === "left") return "right";
  return "left";
}

class PopoverBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: PopoverOptions;
  private currentOpen = false;
  private readonly _id: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private dismissableLayer: DismissableLayer | null = null;
  private focusScope: FocusScope | null = null;
  private scrollLock: ScrollLock | null = null;
  private portaledContent: HTMLElement | null = null;
  private portalPlaceholder: Comment | null = null;
  private originalContentParent: Node | null = null;
  private originalContentNextSibling: Node | null = null;

  constructor(root: Element, options: PopoverOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-popover-${++PopoverBehavior._idCounter}`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.destroyLayerBehavior();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.syncRootAttributes();
    const initialOpen = this.optionOpen() ?? this.defaultOpen();
    this.applyState(initialOpen);
    this.bindEvents();
  }

  update(options: PopoverOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.syncRootAttributes();
    if (options.open !== undefined) this.applyState(options.open);
    else this.applyState(this.currentOpen);
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.destroyLayerBehavior();
    this.restorePortal();
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, POPOVER_CONTROLLED) ||
        this.options.open !== undefined)
    );
  }

  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, POPOVER_DISABLED);
  }

  private modal(): boolean {
    return this.options.modal ?? getBoolAttr(this.root, POPOVER_MODAL);
  }

  private side(): PopoverSide {
    return (this.options.side ??
      getAttr(this.root, POPOVER_SIDE, "bottom")) as PopoverSide;
  }

  private align(): PopoverAlign {
    return (this.options.align ??
      getAttr(this.root, POPOVER_ALIGN, "center")) as PopoverAlign;
  }

  private sideOffset(): number {
    return (
      Number(
        this.options.sideOffset ?? getAttr(this.root, POPOVER_SIDE_OFFSET, "4"),
      ) || 0
    );
  }

  private alignOffset(): number {
    return (
      Number(
        this.options.alignOffset ??
          getAttr(this.root, POPOVER_ALIGN_OFFSET, "0"),
      ) || 0
    );
  }

  private collisionPadding(): number {
    return (
      Number(
        this.options.collisionPadding ??
          getAttr(this.root, POPOVER_COLLISION_PADDING, "8"),
      ) || 0
    );
  }

  private collisionBoundary(): string {
    return (
      this.options.collisionBoundary ??
      getAttr(this.root, POPOVER_COLLISION_BOUNDARY, "")
    );
  }

  private sideFallbacks(): PopoverSide[] {
    const value =
      this.options.sideFallbacks ??
      getAttr(this.root, POPOVER_SIDE_FALLBACKS, "");
    return value
      .split(",")
      .map((side) => side.trim())
      .filter(
        (side): side is PopoverSide =>
          side === "top" ||
          side === "right" ||
          side === "bottom" ||
          side === "left",
      );
  }

  private avoidCollisions(): boolean {
    return (
      this.options.avoidCollisions ??
      this.root.getAttribute(POPOVER_AVOID_COLLISIONS) !== "false"
    );
  }

  private sticky(): PopoverSticky {
    return (this.options.sticky ??
      getAttr(this.root, POPOVER_STICKY, "partial")) as PopoverSticky;
  }

  private hideWhenDetached(): boolean {
    return (
      this.options.hideWhenDetached ??
      getBoolAttr(this.root, POPOVER_HIDE_WHEN_DETACHED)
    );
  }

  private portal(): boolean {
    return this.options.portal ?? getBoolAttr(this.root, POPOVER_PORTAL);
  }

  private portalContainer(): string {
    return (
      this.options.portalContainer ??
      getAttr(this.root, POPOVER_PORTAL_CONTAINER, "")
    );
  }

  private optionOpen(): boolean | undefined {
    if (this.options.open !== undefined) return this.options.open;
    if (this.root.hasAttribute(POPOVER_OPEN))
      return getBoolAttr(this.root, POPOVER_OPEN);
    return undefined;
  }

  private defaultOpen(): boolean {
    return (
      this.options.defaultOpen ?? getBoolAttr(this.root, POPOVER_DEFAULT_OPEN)
    );
  }

  private trigger(): HTMLElement | null {
    const trigger = this.root.querySelector(`[${POPOVER_TRIGGER}]`);
    return trigger instanceof HTMLElement ? trigger : null;
  }

  private anchor(): HTMLElement | null {
    const anchor = this.root.querySelector(`[${POPOVER_ANCHOR}]`);
    return anchor instanceof HTMLElement ? anchor : this.trigger();
  }

  private content(): HTMLElement | null {
    if (this.portaledContent?.isConnected) return this.portaledContent;
    const content = this.root.querySelector(`[${POPOVER_CONTENT}]`);
    return content instanceof HTMLElement ? content : null;
  }

  private syncRootAttributes(): void {
    this.root.setAttribute(POPOVER_ROOT, "");
    setAttr(this.root, POPOVER_CONTROLLED, this.controlled() ? "true" : null);
    setAttr(this.root, POPOVER_MODAL, this.modal() ? "true" : null);
    setAttr(this.root, POPOVER_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, POPOVER_SIDE, this.side());
    setAttr(this.root, POPOVER_ALIGN, this.align());
    setAttr(this.root, POPOVER_SIDE_OFFSET, String(this.sideOffset()));
    setAttr(this.root, POPOVER_ALIGN_OFFSET, String(this.alignOffset()));
    setAttr(
      this.root,
      POPOVER_COLLISION_PADDING,
      String(this.collisionPadding()),
    );
    setAttr(
      this.root,
      POPOVER_COLLISION_BOUNDARY,
      this.collisionBoundary() || null,
    );
    setAttr(
      this.root,
      POPOVER_SIDE_FALLBACKS,
      this.sideFallbacks().join(",") || null,
    );
    setAttr(
      this.root,
      POPOVER_AVOID_COLLISIONS,
      this.avoidCollisions() ? null : "false",
    );
    setAttr(
      this.root,
      POPOVER_STICKY,
      this.sticky() === "partial" ? null : this.sticky(),
    );
    setAttr(
      this.root,
      POPOVER_HIDE_WHEN_DETACHED,
      this.hideWhenDetached() ? "true" : null,
    );
    setAttr(this.root, POPOVER_PORTAL, this.portal() ? "true" : null);
    setAttr(
      this.root,
      POPOVER_PORTAL_CONTAINER,
      this.portalContainer() || null,
    );
  }

  private resolvePortalContainer(): HTMLElement | null {
    const selector = this.portalContainer();
    if (selector) {
      const target = this.root.ownerDocument.querySelector(selector);
      return target instanceof HTMLElement ? target : null;
    }
    return this.root.ownerDocument.body;
  }

  private mountPortal(content: HTMLElement): void {
    if (!this.portal() || this.portaledContent === content) return;
    const container = this.resolvePortalContainer();
    if (!container) return;
    this.originalContentParent = content.parentNode;
    this.originalContentNextSibling = content.nextSibling;
    this.portalPlaceholder = this.root.ownerDocument.createComment(
      "bambi-popover-portal",
    );
    this.originalContentParent?.insertBefore(this.portalPlaceholder, content);
    container.appendChild(content);
    this.portaledContent = content;
  }

  private restorePortal(): void {
    const content = this.portaledContent;
    if (!content) return;
    if (this.originalContentParent) {
      this.originalContentParent.insertBefore(
        content,
        this.originalContentNextSibling,
      );
    }
    this.portalPlaceholder?.remove();
    this.portaledContent = null;
    this.portalPlaceholder = null;
    this.originalContentParent = null;
    this.originalContentNextSibling = null;
  }

  private applyState(open: boolean): void {
    const wasOpen = this.currentOpen;
    this.currentOpen = open;
    const state = open ? "open" : "closed";
    setAttr(this.root, POPOVER_OPEN, open ? "true" : null);
    setAttr(this.root, POPOVER_STATE, state);

    const trigger = this.trigger();
    const content = this.content();
    if (open && content) this.mountPortal(content);

    if (trigger) {
      if (!trigger.id) trigger.id = `${this._id}-trigger`;
      trigger.setAttribute(POPOVER_TRIGGER, "");
      setAttr(trigger, POPOVER_STATE, state);
      setAttr(trigger, POPOVER_DISABLED, this.disabled() ? "true" : null);
      trigger.setAttribute("aria-haspopup", "dialog");
      trigger.setAttribute("aria-expanded", open ? "true" : "false");
      if (content)
        trigger.setAttribute(
          "aria-controls",
          content.id || `${this._id}-content`,
        );
      if (trigger instanceof HTMLButtonElement) {
        if (!trigger.getAttribute("type")) trigger.type = "button";
        trigger.disabled = this.disabled();
      } else {
        setAttr(trigger, "aria-disabled", this.disabled() ? "true" : null);
      }
    }

    if (content) {
      if (!content.id) content.id = `${this._id}-content`;
      content.setAttribute(POPOVER_CONTENT, "");
      content.setAttribute("role", "dialog");
      if (trigger) content.setAttribute("aria-labelledby", trigger.id);
      setAttr(content, POPOVER_STATE, state);
      setAttr(content, POPOVER_SIDE, this.side());
      setAttr(content, POPOVER_ALIGN, this.align());
      content.hidden = !open;
      if (open) this.positionContent();
    }

    for (const close of this.root.querySelectorAll(`[${POPOVER_CLOSE}]`)) {
      close.setAttribute(POPOVER_CLOSE, "");
      setAttr(close, POPOVER_STATE, state);
      if (close instanceof HTMLButtonElement && !close.getAttribute("type"))
        close.type = "button";
    }

    for (const arrow of this.root.querySelectorAll(`[${POPOVER_ARROW}]`)) {
      arrow.setAttribute(POPOVER_ARROW, "");
      setAttr(arrow, POPOVER_STATE, state);
    }

    if (open && content) {
      if (!wasOpen || !this.dismissableLayer || !this.focusScope) {
        this.destroyLayerBehavior(false);
        this.createLayerBehavior(content);
      }
    } else if (!open && wasOpen) {
      this.destroyLayerBehavior(true);
      this.restorePortal();
    }
  }

  private setOpen(
    open: boolean,
    source: PopoverOpenChangeDetail["source"],
  ): void {
    const previousOpen = this.currentOpen;
    if (previousOpen === open) return;
    if (!this.controlled()) this.applyState(open);
    dispatchBambiEvent(this.root, POPOVER_EVENT_OPEN_CHANGE, {
      open,
      previousOpen,
      source,
    });
  }

  private createLayerBehavior(content: HTMLElement): void {
    const signal = this.bindAbort.signal;
    this.dismissableLayer = createDismissableLayer(content, {
      modal: this.modal(),
      branches: [this.root],
      onEscapeKeyDown: () => this.setOpen(false, "escape"),
      onDismiss: (event) => {
        if (event instanceof KeyboardEvent && event.key === "Escape") return;
        this.setOpen(false, "outside");
      },
    });
    this.focusScope = createFocusScope(content, {
      trapped: this.modal(),
      restoreFocus: true,
      autofocus: this.modal(),
      containers: [this.root],
    });
    if (this.modal()) this.scrollLock = createScrollLock(content.ownerDocument);
    content.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const close = target.closest(`[${POPOVER_CLOSE}]`);
        if (close && content.contains(close)) this.setOpen(false, "close");
      },
      { signal },
    );
  }

  private destroyLayerBehavior(restoreFocus = true): void {
    this.dismissableLayer?.destroy();
    this.scrollLock?.destroy();
    if (restoreFocus) this.focusScope?.destroy();
    else {
      const scope = this.focusScope;
      this.focusScope = null;
      scope?.destroy();
    }
    this.dismissableLayer = null;
    this.focusScope = null;
    this.scrollLock = null;
  }

  private positionContent(): void {
    const anchor = this.anchor();
    const content = this.content();
    if (!anchor || !content || typeof window === "undefined") return;

    const anchorRect = anchor.getBoundingClientRect();
    const contentRect = content.getBoundingClientRect();
    const preferredSide = this.side();
    const align = this.align();
    const sideOffset = this.sideOffset();
    const alignOffset = this.alignOffset();
    const padding = this.collisionPadding();
    const boundary = this.boundaryRect();
    const viewportWidth = boundary.width;
    const available = {
      top: anchorRect.top - boundary.top - padding,
      bottom: boundary.bottom - anchorRect.bottom - padding,
      left: anchorRect.left - boundary.left - padding,
      right: boundary.right - anchorRect.right - padding,
    };
    if (this.hideWhenDetached() && this.isDetached(anchorRect, boundary)) {
      content.style.visibility = "hidden";
      return;
    }
    content.style.visibility = "";
    const side = this.avoidCollisions()
      ? this.chooseSide(preferredSide, available, contentRect, sideOffset)
      : preferredSide;

    let top = 0;
    let left = 0;

    if (side === "top") top = anchorRect.top - contentRect.height - sideOffset;
    else if (side === "bottom") top = anchorRect.bottom + sideOffset;
    else top = anchorRect.top + (anchorRect.height - contentRect.height) / 2;

    if (side === "left")
      left = anchorRect.left - contentRect.width - sideOffset;
    else if (side === "right") left = anchorRect.right + sideOffset;
    else left = anchorRect.left + (anchorRect.width - contentRect.width) / 2;

    if (side === "top" || side === "bottom") {
      if (align === "start") left = anchorRect.left + alignOffset;
      if (align === "end")
        left = anchorRect.right - contentRect.width - alignOffset;
    } else {
      if (align === "start") top = anchorRect.top + alignOffset;
      if (align === "end")
        top = anchorRect.bottom - contentRect.height - alignOffset;
    }

    if (this.avoidCollisions() && this.sticky() !== "always") {
      left = clamp(
        left,
        boundary.left + padding,
        boundary.right - contentRect.width - padding,
      );
      top = clamp(
        top,
        boundary.top + padding,
        boundary.bottom - contentRect.height - padding,
      );
    }

    content.style.position = "fixed";
    content.style.left = `${left}px`;
    content.style.top = `${top}px`;
    content.style.setProperty(
      "--bambi-popover-available-width",
      `${viewportWidth - padding * 2}px`,
    );
    content.style.setProperty(
      "--bambi-popover-available-height",
      `${available[side]}px`,
    );
    content.style.setProperty(
      "--bambi-popover-transform-origin",
      `${align} ${side}`,
    );
    setAttr(content, POPOVER_SIDE, side);
    this.positionArrow(content, anchorRect, { top, left }, side);
  }

  private boundaryRect(): DOMRect {
    const selector = this.collisionBoundary();
    const boundary = selector
      ? this.root.ownerDocument.querySelector(selector)
      : null;
    if (boundary instanceof Element) return boundary.getBoundingClientRect();
    return new DOMRect(0, 0, window.innerWidth, window.innerHeight);
  }

  private isDetached(anchorRect: DOMRect, boundary: DOMRect): boolean {
    return (
      anchorRect.width === 0 ||
      anchorRect.height === 0 ||
      anchorRect.bottom < boundary.top ||
      anchorRect.top > boundary.bottom ||
      anchorRect.right < boundary.left ||
      anchorRect.left > boundary.right
    );
  }

  private chooseSide(
    preferredSide: PopoverSide,
    available: Record<PopoverSide, number>,
    contentRect: DOMRect,
    sideOffset: number,
  ): PopoverSide {
    const candidates = [
      preferredSide,
      ...this.sideFallbacks(),
      oppositeSide(preferredSide),
    ];
    const unique = candidates.filter(
      (side, index) => candidates.indexOf(side) === index,
    );
    return (
      unique.find(
        (side) =>
          available[side] >= this.sideSize(contentRect, side) + sideOffset,
      ) ??
      unique.sort((a, b) => available[b] - available[a])[0] ??
      preferredSide
    );
  }

  private sideSize(rect: DOMRect, side: PopoverSide): number {
    return side === "top" || side === "bottom" ? rect.height : rect.width;
  }

  private positionArrow(
    content: HTMLElement,
    anchorRect: DOMRect,
    contentPosition: { top: number; left: number },
    side: PopoverSide,
  ): void {
    const arrow = content.querySelector(`[${POPOVER_ARROW}]`);
    if (!(arrow instanceof HTMLElement)) return;
    arrow.style.left = "";
    arrow.style.top = "";
    arrow.style.right = "";
    arrow.style.bottom = "";
    if (side === "top" || side === "bottom") {
      const anchorCenter = anchorRect.left + anchorRect.width / 2;
      arrow.style.left = `${clamp(anchorCenter - contentPosition.left, 8, content.offsetWidth - 8)}px`;
    } else {
      const anchorCenter = anchorRect.top + anchorRect.height / 2;
      arrow.style.top = `${clamp(anchorCenter - contentPosition.top, 8, content.offsetHeight - 8)}px`;
    }
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const trigger = target.closest(`[${POPOVER_TRIGGER}]`);
        if (trigger && this.root.contains(trigger)) {
          if (this.disabled()) return;
          this.setOpen(!this.currentOpen, "trigger");
          return;
        }
        const close = target.closest(`[${POPOVER_CLOSE}]`);
        if (close && this.root.contains(close)) this.setOpen(false, "close");
      },
      { signal },
    );
    window.addEventListener(
      "resize",
      () => this.currentOpen && this.positionContent(),
      { signal },
    );
    window.addEventListener(
      "scroll",
      () => this.currentOpen && this.positionContent(),
      { capture: true, signal },
    );
  }
}

export interface PopoverProps extends Omit<PopoverOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<PopoverOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onOpenChange?: (detail: PopoverOpenChangeDetail) => void;
}

export interface PopoverTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type PopoverAnchorProps = React.ComponentPropsWithoutRef<"div">;

export type PopoverContentProps = React.ComponentPropsWithoutRef<"div">;

export type PopoverCloseProps = React.ComponentPropsWithoutRef<"button">;

export type PopoverArrowProps = React.ComponentPropsWithoutRef<"div">;

export function Popover({
  open,
  defaultOpen,
  modal,
  disabled,
  side = "bottom",
  align = "center",
  sideOffset,
  alignOffset,
  collisionPadding,
  collisionBoundary,
  sideFallbacks,
  avoidCollisions,
  sticky,
  hideWhenDetached,
  portal,
  portalContainer,
  onOpenChange,
  children,
  ...props
}: PopoverProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<PopoverBehavior | null>(null);
  const controlled = open !== undefined;
  const onOpenChangeRef = React.useRef(onOpenChange);

  React.useEffect(() => {
    if (open !== undefined && defaultOpen !== undefined) {
      console.warn(
        "[bambiui/popover] Popover received both `open` and `defaultOpen`. Use `open` for controlled mode or `defaultOpen` for uncontrolled mode, not both.",
      );
    }
  }, [defaultOpen, open]);
  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onOpenChangeHandler = (event: Event) => {
      const e = event as CustomEvent<PopoverOpenChangeDetail>;
      onOpenChangeRef.current?.(e.detail);
    };
    root.addEventListener(POPOVER_EVENT_OPEN_CHANGE, onOpenChangeHandler);

    const behavior = new PopoverBehavior(root, {
      open,
      defaultOpen,
      modal,
      disabled,
      side,
      align,
      sideOffset,
      alignOffset,
      collisionPadding,
      collisionBoundary,
      sideFallbacks,
      avoidCollisions,
      sticky,
      hideWhenDetached,
      portal,
      portalContainer,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(POPOVER_EVENT_OPEN_CHANGE, onOpenChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      open,
      defaultOpen,
      modal,
      disabled,
      side,
      align,
      sideOffset,
      alignOffset,
      collisionPadding,
      collisionBoundary,
      sideFallbacks,
      avoidCollisions,
      sticky,
      hideWhenDetached,
      portal,
      portalContainer,
      controlled,
    });
  }, [open, defaultOpen, modal, disabled, side, align, sideOffset, alignOffset, collisionPadding, collisionBoundary, sideFallbacks, avoidCollisions, sticky, hideWhenDetached, portal, portalContainer, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [POPOVER_ROOT]: "" }}
      {...{ [POPOVER_OPEN]: open ? "true" : undefined }}
      {...{ [POPOVER_DEFAULT_OPEN]: defaultOpen ? "true" : undefined }}
      {...{ [POPOVER_MODAL]: modal ? "true" : undefined }}
      {...{ [POPOVER_DISABLED]: disabled ? "true" : undefined }}
      {...{ [POPOVER_SIDE]: side }}
      {...{ [POPOVER_ALIGN]: align }}
      {...{ [POPOVER_SIDE_OFFSET]: sideOffset }}
      {...{ [POPOVER_ALIGN_OFFSET]: alignOffset }}
      {...{ [POPOVER_COLLISION_PADDING]: collisionPadding }}
      {...{ [POPOVER_COLLISION_BOUNDARY]: collisionBoundary }}
      {...{ [POPOVER_SIDE_FALLBACKS]: sideFallbacks }}
      {...{ [POPOVER_AVOID_COLLISIONS]: avoidCollisions ? "true" : undefined }}
      {...{ [POPOVER_STICKY]: sticky }}
      {...{ [POPOVER_HIDE_WHEN_DETACHED]: hideWhenDetached ? "true" : undefined }}
      {...{ [POPOVER_PORTAL]: portal ? "true" : undefined }}
      {...{ [POPOVER_PORTAL_CONTAINER]: portalContainer }}
      {...{ [POPOVER_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function PopoverTrigger({ disabled, children, ...props }: PopoverTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [POPOVER_DISABLED]: disabled ? "true" : undefined }}
      {...{ [POPOVER_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function PopoverAnchor({ children, ...props }: PopoverAnchorProps) {

  return (
    <div
      {...props}
      {...{ [POPOVER_ANCHOR]: "" }}
    >
      {children}
    </div>
  );
}

export function PopoverContent({ children, ...props }: PopoverContentProps) {

  return (
    <div
      {...props}
      {...{ [POPOVER_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function PopoverClose({ children, ...props }: PopoverCloseProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      {...{ [POPOVER_CLOSE]: "" }}
    >
      {children}
    </button>
  );
}

export function PopoverArrow({ children, ...props }: PopoverArrowProps) {

  return (
    <div
      {...props}
      {...{ [POPOVER_ARROW]: "" }}
    >
      {children}
    </div>
  );
}
