// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp, type LayerHandle, createLayerHandle, getTopLayer, isInLayerStack, type DismissableLayerEventDetail, type DismissableLayerOptions, type DismissableLayer, type DismissableLayerEvent, createDismissableLayer, type RovingFocusOptions, type RovingFocus, createRovingFocus } from "../bambi-helpers";

const DROPDOWN_MENU_ROOT = "data-bambi-dropdown-menu" as const;
const DROPDOWN_MENU_TRIGGER =
  "data-bambi-dropdown-menu-trigger" as const;
const DROPDOWN_MENU_PORTAL = "data-bambi-dropdown-menu-portal" as const;
const DROPDOWN_MENU_CONTENT =
  "data-bambi-dropdown-menu-content" as const;
const DROPDOWN_MENU_ITEM = "data-bambi-dropdown-menu-item" as const;
const DROPDOWN_MENU_CHECKBOX_ITEM =
  "data-bambi-dropdown-menu-checkbox-item" as const;
const DROPDOWN_MENU_RADIO_GROUP =
  "data-bambi-dropdown-menu-radio-group" as const;
const DROPDOWN_MENU_RADIO_ITEM =
  "data-bambi-dropdown-menu-radio-item" as const;
const DROPDOWN_MENU_ITEM_INDICATOR =
  "data-bambi-dropdown-menu-item-indicator" as const;
const DROPDOWN_MENU_LABEL = "data-bambi-dropdown-menu-label" as const;
const DROPDOWN_MENU_SEPARATOR =
  "data-bambi-dropdown-menu-separator" as const;
const DROPDOWN_MENU_GROUP = "data-bambi-dropdown-menu-group" as const;
const DROPDOWN_MENU_SUB = "data-bambi-dropdown-menu-sub" as const;
const DROPDOWN_MENU_SUB_TRIGGER =
  "data-bambi-dropdown-menu-sub-trigger" as const;
const DROPDOWN_MENU_SUB_CONTENT =
  "data-bambi-dropdown-menu-sub-content" as const;
const DROPDOWN_MENU_ARROW = "data-bambi-dropdown-menu-arrow" as const;
const DROPDOWN_MENU_OPEN = "data-open" as const;
const DROPDOWN_MENU_DEFAULT_OPEN = "data-default-open" as const;
const DROPDOWN_MENU_CONTROLLED = "data-controlled" as const;
const DROPDOWN_MENU_DISABLED = "data-disabled" as const;
const DROPDOWN_MENU_MODAL = "data-modal" as const;
const DROPDOWN_MENU_DIR = "data-dir" as const;
const DROPDOWN_MENU_LOOP = "data-loop" as const;
const DROPDOWN_MENU_VALUE = "data-value" as const;
const DROPDOWN_MENU_TEXT_VALUE = "data-text-value" as const;
const DROPDOWN_MENU_CHECKED = "data-checked" as const;
const DROPDOWN_MENU_STATE = "data-state" as const;
const DROPDOWN_MENU_HIGHLIGHTED = "data-highlighted" as const;
const DROPDOWN_MENU_EVENT_OPEN_CHANGE = "bambi:open-change" as const;
const DROPDOWN_MENU_EVENT_SELECT = "bambi:select" as const;
const DROPDOWN_MENU_EVENT_CHECKED_CHANGE =
  "bambi:checked-change" as const;
const DROPDOWN_MENU_EVENT_VALUE_CHANGE = "bambi:value-change" as const;

export type DropdownMenuDir = "ltr" | "rtl";
export type DropdownMenuChecked = boolean | "indeterminate";

export interface DropdownMenuOpenChangeDetail {
  open: boolean;
  previousOpen: boolean;
  source: "trigger" | "escape" | "outside" | "item" | "programmatic";
}

export interface DropdownMenuItemSelectDetail {
  value: string;
  source: "click" | "keyboard";
}

export type DropdownMenuSelectDetail = DropdownMenuItemSelectDetail;

export interface DropdownMenuCheckedChangeDetail {
  checked: DropdownMenuChecked;
  previousChecked: DropdownMenuChecked;
  value: string;
  source: "click" | "keyboard";
}

export interface DropdownMenuValueChangeDetail {
  value: string;
  previousValue: string;
  source: "click" | "keyboard";
}


type DropdownMenuPrimitiveReferenceTypes =
  | DropdownMenuCheckedChangeDetail
  | DropdownMenuSelectDetail
  | DropdownMenuValueChangeDetail
  | LayerHandle
  | DismissableLayerEvent
  | DismissableLayerEventDetail
  | DismissableLayerOptions
  | RovingFocusOptions;

const dropdownMenuPrimitiveReferenceTypes: DropdownMenuPrimitiveReferenceTypes | null =
  null;
const dropdownMenuPrimitiveReferenceValues = [
  clamp,
  createLayerHandle,
  getTopLayer,
  isInLayerStack,
] as const;
void dropdownMenuPrimitiveReferenceTypes;
void dropdownMenuPrimitiveReferenceValues;

export interface DropdownMenuOptions {
  open?: boolean;
  defaultOpen?: boolean;
  controlled?: boolean;
  disabled?: boolean;
  modal?: boolean;
  dir?: DropdownMenuDir;
  loop?: boolean;
}

function normalizeChecked(
  value: string | boolean | null | undefined,
): DropdownMenuChecked {
  if (value === "indeterminate") return "indeterminate";
  if (value === true || value === "true" || value === "checked") return true;
  return false;
}

function checkedState(
  checked: DropdownMenuChecked,
): "checked" | "unchecked" | "indeterminate" {
  if (checked === "indeterminate") return "indeterminate";
  return checked ? "checked" : "unchecked";
}

function checkedAria(checked: DropdownMenuChecked): "true" | "false" | "mixed" {
  if (checked === "indeterminate") return "mixed";
  return checked ? "true" : "false";
}

function checkedAttr(checked: DropdownMenuChecked): string {
  if (checked === "indeterminate") return "indeterminate";
  return checked ? "true" : "false";
}

class DropdownMenuBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: DropdownMenuOptions;
  private currentOpen = false;
  private readonly _id: string;
  private bindAbort = new AbortController();
  private dismissableLayer: DismissableLayer | null = null;
  private rovingFocus: RovingFocus | null = null;
  private typeaheadBuffer = "";
  private typeaheadTimer = 0;
  private portaledNode: HTMLElement | null = null;
  private portalPlaceholder: Comment | null = null;
  private originalPortalParent: Node | null = null;
  private originalPortalNextSibling: Node | null = null;

  constructor(root: Element, options: DropdownMenuOptions = {}) {
    this.root = root;
    this.options = options;
    this._id =
      root.id || `bambi-dropdown-menu-${++DropdownMenuBehavior._idCounter}`;
  }

  sync(): void {
    this.bindAbort.abort();
    this.destroyLayer();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.currentOpen = this.optionOpen() ?? this.defaultOpen();
    this.applyState();
    this.bindEvents();
  }

  update(options: DropdownMenuOptions = {}): void {
    this.options = { ...this.options, ...options };
    if (options.open !== undefined) this.currentOpen = options.open;
    this.applyState();
  }

  destroy(): void {
    this.bindAbort.abort();
    this.destroyLayer();
    this.restorePortal();
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, DROPDOWN_MENU_CONTROLLED) ||
        this.options.open !== undefined)
    );
  }

  private disabled(): boolean {
    return (
      this.options.disabled ?? getBoolAttr(this.root, DROPDOWN_MENU_DISABLED)
    );
  }

  private modal(): boolean {
    return (
      this.options.modal ??
      this.root.getAttribute(DROPDOWN_MENU_MODAL) !== "false"
    );
  }

  private dir(): DropdownMenuDir {
    const dir =
      this.options.dir ?? getAttr(this.root, DROPDOWN_MENU_DIR, "ltr");
    return dir === "rtl" ? "rtl" : "ltr";
  }

  private loop(): boolean {
    return (
      this.options.loop ??
      this.root.getAttribute(DROPDOWN_MENU_LOOP) !== "false"
    );
  }

  private optionOpen(): boolean | undefined {
    if (this.options.open !== undefined) return this.options.open;
    if (this.root.hasAttribute(DROPDOWN_MENU_OPEN))
      return getBoolAttr(this.root, DROPDOWN_MENU_OPEN);
    return undefined;
  }

  private defaultOpen(): boolean {
    return (
      this.options.defaultOpen ??
      getBoolAttr(this.root, DROPDOWN_MENU_DEFAULT_OPEN)
    );
  }

  private trigger(): HTMLElement | null {
    const trigger = this.root.querySelector(`[${DROPDOWN_MENU_TRIGGER}]`);
    return trigger instanceof HTMLElement ? trigger : null;
  }

  private portal(): HTMLElement | null {
    if (this.portaledNode?.hasAttribute(DROPDOWN_MENU_PORTAL))
      return this.portaledNode;
    const portal = this.root.querySelector(`[${DROPDOWN_MENU_PORTAL}]`);
    return portal instanceof HTMLElement ? portal : null;
  }

  private content(): HTMLElement | null {
    const scope = this.portaledNode ?? this.root;
    const content = scope.querySelector(`[${DROPDOWN_MENU_CONTENT}]`);
    return content instanceof HTMLElement ? content : null;
  }

  private itemSelector(): string {
    return `[${DROPDOWN_MENU_ITEM}], [${DROPDOWN_MENU_CHECKBOX_ITEM}], [${DROPDOWN_MENU_RADIO_ITEM}], [${DROPDOWN_MENU_SUB_TRIGGER}]`;
  }

  private items(scope: Element | null = this.content()): HTMLElement[] {
    if (!scope) return [];
    return Array.from(scope.querySelectorAll(this.itemSelector())).filter(
      (item): item is HTMLElement => {
        if (!(item instanceof HTMLElement)) return false;
        const subContent = item.closest(`[${DROPDOWN_MENU_SUB_CONTENT}]`);
        return !subContent || subContent === scope;
      },
    );
  }

  private itemValue(item: Element): string {
    return (
      item.getAttribute(DROPDOWN_MENU_VALUE) ?? item.textContent?.trim() ?? ""
    );
  }

  private itemText(item: Element): string {
    return (
      item.getAttribute(DROPDOWN_MENU_TEXT_VALUE) ??
      item.textContent?.trim() ??
      ""
    );
  }

  private mountPortal(): void {
    if (this.portaledNode) return;
    const portal = this.portal();
    if (!portal) return;
    const container = this.root.ownerDocument.body;
    if (portal.parentNode === container) return;
    this.originalPortalParent = portal.parentNode;
    this.originalPortalNextSibling = portal.nextSibling;
    this.portalPlaceholder = this.root.ownerDocument.createComment(
      "bambi-dropdown-menu-portal",
    );
    this.originalPortalParent?.insertBefore(this.portalPlaceholder, portal);
    container.appendChild(portal);
    this.portaledNode = portal;
  }

  private restorePortal(): void {
    const node = this.portaledNode;
    if (!node) return;
    if (this.originalPortalParent)
      this.originalPortalParent.insertBefore(
        node,
        this.originalPortalNextSibling,
      );
    this.portalPlaceholder?.remove();
    this.portaledNode = null;
    this.portalPlaceholder = null;
    this.originalPortalParent = null;
    this.originalPortalNextSibling = null;
  }

  private applyState(): void {
    const state = this.currentOpen ? "open" : "closed";
    this.root.setAttribute(DROPDOWN_MENU_ROOT, "");
    setAttr(this.root, DROPDOWN_MENU_OPEN, this.currentOpen ? "true" : null);
    setAttr(this.root, DROPDOWN_MENU_STATE, state);
    setAttr(
      this.root,
      DROPDOWN_MENU_CONTROLLED,
      this.controlled() ? "true" : null,
    );
    setAttr(this.root, DROPDOWN_MENU_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, DROPDOWN_MENU_MODAL, this.modal() ? "true" : "false");
    setAttr(this.root, DROPDOWN_MENU_DIR, this.dir());
    setAttr(this.root, DROPDOWN_MENU_LOOP, this.loop() ? null : "false");

    if (this.currentOpen) this.mountPortal();
    const trigger = this.trigger();
    const portal = this.portal();
    const content = this.content();

    if (trigger) {
      if (!trigger.id) trigger.id = `${this._id}-trigger`;
      trigger.setAttribute(DROPDOWN_MENU_TRIGGER, "");
      trigger.setAttribute("aria-haspopup", "menu");
      trigger.setAttribute(
        "aria-expanded",
        this.currentOpen ? "true" : "false",
      );
      if (content)
        trigger.setAttribute(
          "aria-controls",
          content.id || `${this._id}-content`,
        );
      setAttr(trigger, DROPDOWN_MENU_STATE, state);
      setAttr(trigger, DROPDOWN_MENU_DISABLED, this.disabled() ? "true" : null);
      if (trigger instanceof HTMLButtonElement) {
        if (!trigger.type) trigger.type = "button";
        trigger.disabled = this.disabled();
      } else setAttr(trigger, "aria-disabled", this.disabled() ? "true" : null);
    }

    if (portal) {
      portal.setAttribute(DROPDOWN_MENU_PORTAL, "");
      setAttr(portal, DROPDOWN_MENU_STATE, state);
      portal.hidden = !this.currentOpen;
    }

    if (content) {
      if (!content.id) content.id = `${this._id}-content`;
      content.setAttribute(DROPDOWN_MENU_CONTENT, "");
      content.setAttribute("role", "menu");
      content.setAttribute("aria-orientation", "vertical");
      if (trigger) content.setAttribute("aria-labelledby", trigger.id);
      setAttr(content, DROPDOWN_MENU_STATE, state);
      content.hidden = !this.currentOpen;
      if (this.currentOpen) this.positionContent(content, trigger);
    }

    this.syncStaticParts();
    this.syncItems();
    this.destroyLayer();
    if (this.currentOpen && content) this.createLayer(content);
  }

  private syncStaticParts(): void {
    const scope = this.portaledNode ?? this.root;
    for (const label of scope.querySelectorAll(`[${DROPDOWN_MENU_LABEL}]`))
      label.setAttribute(DROPDOWN_MENU_LABEL, "");
    for (const separator of scope.querySelectorAll(
      `[${DROPDOWN_MENU_SEPARATOR}]`,
    )) {
      separator.setAttribute(DROPDOWN_MENU_SEPARATOR, "");
      separator.setAttribute("role", "separator");
    }
    for (const group of scope.querySelectorAll(
      `[${DROPDOWN_MENU_GROUP}], [${DROPDOWN_MENU_RADIO_GROUP}]`,
    ))
      group.setAttribute("role", "group");
    for (const arrow of scope.querySelectorAll(`[${DROPDOWN_MENU_ARROW}]`))
      arrow.setAttribute(DROPDOWN_MENU_ARROW, "");
  }

  private syncItems(): void {
    for (const item of this.items()) {
      const disabled = getBoolAttr(item, DROPDOWN_MENU_DISABLED);
      const isCheckbox = item.hasAttribute(DROPDOWN_MENU_CHECKBOX_ITEM);
      const isRadio = item.hasAttribute(DROPDOWN_MENU_RADIO_ITEM);
      const isSubTrigger = item.hasAttribute(DROPDOWN_MENU_SUB_TRIGGER);
      if (isCheckbox) item.setAttribute("role", "menuitemcheckbox");
      else if (isRadio) item.setAttribute("role", "menuitemradio");
      else item.setAttribute("role", "menuitem");
      item.tabIndex = disabled ? -1 : -1;
      setAttr(item, DROPDOWN_MENU_DISABLED, disabled ? "true" : null);
      setAttr(item, "aria-disabled", disabled ? "true" : null);
      setAttr(item, DROPDOWN_MENU_HIGHLIGHTED, null);
      if (isSubTrigger) {
        const sub = item.closest(`[${DROPDOWN_MENU_SUB}]`);
        const subContent = sub?.querySelector(`[${DROPDOWN_MENU_SUB_CONTENT}]`);
        item.setAttribute("aria-haspopup", "menu");
        item.setAttribute(
          "aria-expanded",
          sub?.getAttribute(DROPDOWN_MENU_STATE) === "open" ? "true" : "false",
        );
        if (subContent instanceof HTMLElement) {
          if (!subContent.id)
            subContent.id = `${this._id}-sub-content-${this.items().indexOf(item)}`;
          item.setAttribute("aria-controls", subContent.id);
        }
      }
      if (isCheckbox || isRadio) {
        const checked = this.itemChecked(item);
        item.setAttribute("aria-checked", checkedAria(checked));
        setAttr(item, DROPDOWN_MENU_STATE, checkedState(checked));
      }
      for (const indicator of item.querySelectorAll(
        `[${DROPDOWN_MENU_ITEM_INDICATOR}]`,
      )) {
        indicator.setAttribute(DROPDOWN_MENU_ITEM_INDICATOR, "");
        setAttr(
          indicator,
          DROPDOWN_MENU_STATE,
          item.getAttribute(DROPDOWN_MENU_STATE),
        );
        indicator.setAttribute("aria-hidden", "true");
      }
    }
    for (const sub of (this.portaledNode ?? this.root).querySelectorAll(
      `[${DROPDOWN_MENU_SUB}]`,
    )) {
      const open = sub.getAttribute(DROPDOWN_MENU_STATE) === "open";
      const subContent = sub.querySelector(`[${DROPDOWN_MENU_SUB_CONTENT}]`);
      if (subContent instanceof HTMLElement) {
        subContent.setAttribute(DROPDOWN_MENU_SUB_CONTENT, "");
        subContent.setAttribute("role", "menu");
        setAttr(subContent, DROPDOWN_MENU_STATE, open ? "open" : "closed");
        subContent.hidden = !open;
      }
    }
  }

  private itemChecked(item: Element): DropdownMenuChecked {
    if (item.hasAttribute(DROPDOWN_MENU_RADIO_ITEM)) {
      const value = item.getAttribute(DROPDOWN_MENU_VALUE) ?? "";
      const group = item.closest(`[${DROPDOWN_MENU_RADIO_GROUP}]`);
      return value !== "" && group?.getAttribute(DROPDOWN_MENU_VALUE) === value;
    }
    return normalizeChecked(item.getAttribute(DROPDOWN_MENU_CHECKED));
  }

  private setOpen(
    open: boolean,
    source: DropdownMenuOpenChangeDetail["source"],
  ): void {
    const previousOpen = this.currentOpen;
    if (previousOpen === open) return;
    if (!this.controlled()) {
      this.currentOpen = open;
      this.applyState();
    }
    dispatchBambiEvent(this.root, DROPDOWN_MENU_EVENT_OPEN_CHANGE, {
      open,
      previousOpen,
      source,
    });
  }

  private createLayer(content: HTMLElement): void {
    this.dismissableLayer = createDismissableLayer(content, {
      modal: this.modal(),
      branches: [this.root],
      onEscapeKeyDown: () => this.setOpen(false, "escape"),
      onDismiss: () => this.setOpen(false, "outside"),
    });
    this.rovingFocus = createRovingFocus(content, {
      orientation: "vertical",
      loop: this.loop(),
      getItems: () => this.items(content),
      isDisabled: (item) => getBoolAttr(item, DROPDOWN_MENU_DISABLED),
      onFocus: (item) => {
        if (item instanceof HTMLElement) this.highlightItem(item);
      },
      onActivate: (item) => this.activateItem(item, "keyboard"),
    });
    queueMicrotask(() => this.focusFirstItem());
  }

  private destroyLayer(): void {
    this.dismissableLayer?.destroy();
    this.rovingFocus?.destroy();
    this.dismissableLayer = null;
    this.rovingFocus = null;
  }

  private focusFirstItem(): void {
    const first = this.items().find(
      (item) => !getBoolAttr(item, DROPDOWN_MENU_DISABLED),
    );
    if (first) this.highlightItem(first);
  }

  private highlightItem(item: HTMLElement): void {
    for (const candidate of this.items())
      setAttr(candidate, DROPDOWN_MENU_HIGHLIGHTED, null);
    setAttr(item, DROPDOWN_MENU_HIGHLIGHTED, "true");
    item.focus({ preventScroll: true });
  }

  private activateItem(item: Element, source: "click" | "keyboard"): void {
    if (getBoolAttr(item, DROPDOWN_MENU_DISABLED)) return;
    if (item.hasAttribute(DROPDOWN_MENU_SUB_TRIGGER)) {
      this.setSubOpen(item, true);
      return;
    }
    const value = this.itemValue(item);
    if (item.hasAttribute(DROPDOWN_MENU_CHECKBOX_ITEM)) {
      const previousChecked = this.itemChecked(item);
      const checked = previousChecked === true ? false : true;
      setAttr(item, DROPDOWN_MENU_CHECKED, checkedAttr(checked));
      setAttr(item, DROPDOWN_MENU_STATE, checkedState(checked));
      item.setAttribute("aria-checked", checkedAria(checked));
      dispatchBambiEvent(this.root, DROPDOWN_MENU_EVENT_CHECKED_CHANGE, {
        checked,
        previousChecked,
        value,
        source,
      });
      return;
    }
    if (item.hasAttribute(DROPDOWN_MENU_RADIO_ITEM)) {
      const group = item.closest(`[${DROPDOWN_MENU_RADIO_GROUP}]`);
      const previousValue = group?.getAttribute(DROPDOWN_MENU_VALUE) ?? "";
      if (group && value && previousValue !== value) {
        group.setAttribute(DROPDOWN_MENU_VALUE, value);
        dispatchBambiEvent(this.root, DROPDOWN_MENU_EVENT_VALUE_CHANGE, {
          value,
          previousValue,
          source,
        });
      }
      this.syncItems();
      this.setOpen(false, "item");
      return;
    }
    dispatchBambiEvent<DropdownMenuItemSelectDetail>(
      this.root,
      DROPDOWN_MENU_EVENT_SELECT,
      { value, source },
    );
    this.setOpen(false, "item");
  }

  private setSubOpen(item: Element, open: boolean): void {
    const sub = item.closest(`[${DROPDOWN_MENU_SUB}]`);
    if (!sub) return;
    setAttr(sub, DROPDOWN_MENU_STATE, open ? "open" : "closed");
    const content = sub.querySelector(`[${DROPDOWN_MENU_SUB_CONTENT}]`);
    if (content instanceof HTMLElement) {
      setAttr(content, DROPDOWN_MENU_STATE, open ? "open" : "closed");
      content.hidden = !open;
    }
    item.setAttribute("aria-expanded", open ? "true" : "false");
  }

  private handleTypeahead(key: string): void {
    window.clearTimeout(this.typeaheadTimer);
    this.typeaheadBuffer += key.toLowerCase();
    this.typeaheadTimer = window.setTimeout(() => {
      this.typeaheadBuffer = "";
    }, 700);
    const items = this.items().filter(
      (item) => !getBoolAttr(item, DROPDOWN_MENU_DISABLED),
    );
    const currentIndex = Math.max(
      0,
      items.findIndex(
        (item) => item.getAttribute(DROPDOWN_MENU_HIGHLIGHTED) === "true",
      ),
    );
    const ordered = [
      ...items.slice(currentIndex + 1),
      ...items.slice(0, currentIndex + 1),
    ];
    const match = ordered.find((item) =>
      this.itemText(item).toLowerCase().startsWith(this.typeaheadBuffer),
    );
    if (match) this.highlightItem(match);
  }

  private positionContent(
    content: HTMLElement,
    trigger: HTMLElement | null,
  ): void {
    if (!trigger || typeof window === "undefined") return;
    const rect = trigger.getBoundingClientRect();
    content.style.position = "fixed";
    content.style.minWidth = `${rect.width}px`;
    content.style.left = `${this.dir() === "rtl" ? rect.right - content.offsetWidth : rect.left}px`;
    content.style.top = `${rect.bottom + 4}px`;
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const trigger = target.closest(`[${DROPDOWN_MENU_TRIGGER}]`);
        if (trigger && this.root.contains(trigger)) {
          if (!this.disabled()) this.setOpen(!this.currentOpen, "trigger");
          return;
        }
        const item = target.closest(this.itemSelector());
        if (
          item &&
          (this.root.contains(item) || this.portaledNode?.contains(item))
        )
          this.activateItem(item, "click");
      },
      { signal },
    );

    this.root.addEventListener(
      "keydown",
      (event) => {
        const e = event as KeyboardEvent;
        const target = e.target;
        if (!(target instanceof Element)) return;
        if (
          target.closest(`[${DROPDOWN_MENU_TRIGGER}]`) &&
          ["ArrowDown", "ArrowUp", "Enter", " "].includes(e.key)
        ) {
          e.preventDefault();
          this.setOpen(true, "trigger");
          return;
        }
        if (!this.currentOpen) return;
        if (
          e.key.length === 1 &&
          !e.metaKey &&
          !e.ctrlKey &&
          !e.altKey &&
          e.key !== " "
        ) {
          this.handleTypeahead(e.key);
        }
        if (e.key === "ArrowRight" || e.key === "ArrowLeft") {
          const active = this.root.ownerDocument.activeElement;
          if (
            active instanceof Element &&
            active.hasAttribute(DROPDOWN_MENU_SUB_TRIGGER)
          ) {
            const opens =
              (e.key === "ArrowRight" && this.dir() === "ltr") ||
              (e.key === "ArrowLeft" && this.dir() === "rtl");
            this.setSubOpen(active, opens);
          }
        }
      },
      { signal },
    );

    window.addEventListener(
      "resize",
      () =>
        this.currentOpen &&
        this.positionContent(this.content() as HTMLElement, this.trigger()),
      { signal },
    );
  }
}

export interface DropdownMenuProps extends Omit<DropdownMenuOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<DropdownMenuOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onOpenChange?: (detail: DropdownMenuOpenChangeDetail) => void;
  onItemSelect?: (detail: DropdownMenuItemSelectDetail) => void;
  onCheckedChange?: (detail: DropdownMenuCheckedChangeDetail) => void;
  onValueChange?: (detail: DropdownMenuValueChangeDetail) => void;
}

export interface DropdownMenuTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type DropdownMenuPortalProps = React.ComponentPropsWithoutRef<"div">;

export type DropdownMenuContentProps = React.ComponentPropsWithoutRef<"div">;

export interface DropdownMenuItemProps extends React.ComponentPropsWithoutRef<"div"> {
  disabled?: boolean;
}

export interface DropdownMenuCheckboxItemProps extends React.ComponentPropsWithoutRef<"div"> {
  disabled?: boolean;
}

export type DropdownMenuRadioGroupProps = React.ComponentPropsWithoutRef<"div">;

export interface DropdownMenuRadioItemProps extends React.ComponentPropsWithoutRef<"div"> {
  disabled?: boolean;
}

export type DropdownMenuItemIndicatorProps = React.ComponentPropsWithoutRef<"span">;

export type DropdownMenuLabelProps = React.ComponentPropsWithoutRef<"div">;

export type DropdownMenuSeparatorProps = React.ComponentPropsWithoutRef<"div">;

export type DropdownMenuGroupProps = React.ComponentPropsWithoutRef<"div">;

export type DropdownMenuSubProps = React.ComponentPropsWithoutRef<"div">;

export interface DropdownMenuSubTriggerProps extends React.ComponentPropsWithoutRef<"div"> {
  disabled?: boolean;
}

export type DropdownMenuSubContentProps = React.ComponentPropsWithoutRef<"div">;

export type DropdownMenuArrowProps = React.ComponentPropsWithoutRef<"div">;

export function DropdownMenu({
  open,
  defaultOpen,
  disabled,
  modal,
  dir = "ltr",
  loop,
  onOpenChange,
  onItemSelect,
  onCheckedChange,
  onValueChange,
  children,
  ...props
}: DropdownMenuProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<DropdownMenuBehavior | null>(null);
  const controlled = open !== undefined;
  const onOpenChangeRef = React.useRef(onOpenChange);
  const onItemSelectRef = React.useRef(onItemSelect);
  const onCheckedChangeRef = React.useRef(onCheckedChange);
  const onValueChangeRef = React.useRef(onValueChange);

  React.useEffect(() => {
    if (open !== undefined && defaultOpen !== undefined) {
      console.warn(
        "[bambiui/dropdown-menu] DropdownMenu received both `open` and `defaultOpen`. Use `open` for controlled mode or `defaultOpen` for uncontrolled mode, not both.",
      );
    }
  }, [defaultOpen, open]);
  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  React.useEffect(() => {
    onItemSelectRef.current = onItemSelect;
  }, [onItemSelect]);

  React.useEffect(() => {
    onCheckedChangeRef.current = onCheckedChange;
  }, [onCheckedChange]);

  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onOpenChangeHandler = (event: Event) => {
      const e = event as CustomEvent<DropdownMenuOpenChangeDetail>;
      onOpenChangeRef.current?.(e.detail);
    };
    root.addEventListener(DROPDOWN_MENU_EVENT_OPEN_CHANGE, onOpenChangeHandler);
    const onItemSelectHandler = (event: Event) => {
      const e = event as CustomEvent<DropdownMenuItemSelectDetail>;
      onItemSelectRef.current?.(e.detail);
    };
    root.addEventListener(DROPDOWN_MENU_EVENT_SELECT, onItemSelectHandler);
    const onCheckedChangeHandler = (event: Event) => {
      const e = event as CustomEvent<DropdownMenuCheckedChangeDetail>;
      onCheckedChangeRef.current?.(e.detail);
    };
    root.addEventListener(DROPDOWN_MENU_EVENT_CHECKED_CHANGE, onCheckedChangeHandler);
    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<DropdownMenuValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(DROPDOWN_MENU_EVENT_VALUE_CHANGE, onValueChangeHandler);

    const behavior = new DropdownMenuBehavior(root, {
      open,
      defaultOpen,
      disabled,
      modal,
      dir,
      loop,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(DROPDOWN_MENU_EVENT_OPEN_CHANGE, onOpenChangeHandler);
      root.removeEventListener(DROPDOWN_MENU_EVENT_SELECT, onItemSelectHandler);
      root.removeEventListener(DROPDOWN_MENU_EVENT_CHECKED_CHANGE, onCheckedChangeHandler);
      root.removeEventListener(DROPDOWN_MENU_EVENT_VALUE_CHANGE, onValueChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      open,
      defaultOpen,
      disabled,
      modal,
      dir,
      loop,
      controlled,
    });
  }, [open, defaultOpen, disabled, modal, dir, loop, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [DROPDOWN_MENU_ROOT]: "" }}
      {...{ [DROPDOWN_MENU_OPEN]: open ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_DEFAULT_OPEN]: defaultOpen ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_MODAL]: modal ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_DIR]: dir }}
      {...{ [DROPDOWN_MENU_LOOP]: loop ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuTrigger({ disabled, children, ...props }: DropdownMenuTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [DROPDOWN_MENU_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function DropdownMenuPortal({ children, ...props }: DropdownMenuPortalProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_PORTAL]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuContent({ children, ...props }: DropdownMenuContentProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuItem({ disabled, children, ...props }: DropdownMenuItemProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_ITEM]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuCheckboxItem({ disabled, children, ...props }: DropdownMenuCheckboxItemProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_CHECKBOX_ITEM]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuRadioGroup({ children, ...props }: DropdownMenuRadioGroupProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_RADIO_GROUP]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuRadioItem({ disabled, children, ...props }: DropdownMenuRadioItemProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_RADIO_ITEM]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuItemIndicator({ children, ...props }: DropdownMenuItemIndicatorProps) {

  return (
    <span
      {...props}
      {...{ [DROPDOWN_MENU_ITEM_INDICATOR]: "" }}
    >
      {children}
    </span>
  );
}

export function DropdownMenuLabel({ children, ...props }: DropdownMenuLabelProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_LABEL]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuSeparator({ children, ...props }: DropdownMenuSeparatorProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_SEPARATOR]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuGroup({ children, ...props }: DropdownMenuGroupProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_GROUP]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuSub({ children, ...props }: DropdownMenuSubProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_SUB]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuSubTrigger({ disabled, children, ...props }: DropdownMenuSubTriggerProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DROPDOWN_MENU_SUB_TRIGGER]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuSubContent({ children, ...props }: DropdownMenuSubContentProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_SUB_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function DropdownMenuArrow({ children, ...props }: DropdownMenuArrowProps) {

  return (
    <div
      {...props}
      {...{ [DROPDOWN_MENU_ARROW]: "" }}
    >
      {children}
    </div>
  );
}
