// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp } from "../bambi-helpers";

const TOOLTIP_ROOT = "data-bambi-tooltip" as const;
const TOOLTIP_TRIGGER = "data-bambi-tooltip-trigger" as const;
const TOOLTIP_CONTENT = "data-bambi-tooltip-content" as const;
const TOOLTIP_ARROW = "data-bambi-tooltip-arrow" as const;
const TOOLTIP_OPEN = "data-open" as const;
const TOOLTIP_DEFAULT_OPEN = "data-default-open" as const;
const TOOLTIP_CONTROLLED = "data-controlled" as const;
const TOOLTIP_DISABLED = "data-disabled" as const;
const TOOLTIP_SIDE = "data-side" as const;
const TOOLTIP_ALIGN = "data-align" as const;
const TOOLTIP_SIDE_OFFSET = "data-side-offset" as const;
const TOOLTIP_DELAY_DURATION = "data-delay-duration" as const;
const TOOLTIP_DISABLE_HOVERABLE_CONTENT = "data-disable-hoverable-content" as const;
const TOOLTIP_PORTAL = "data-portal" as const;
const TOOLTIP_PORTAL_CONTAINER = "data-portal-container" as const;
const TOOLTIP_STATE = "data-state" as const;
const TOOLTIP_EVENT_OPEN_CHANGE = "bambi:open-change" as const;

export type TooltipSide = "top" | "right" | "bottom" | "left";
export type TooltipAlign = "start" | "center" | "end";

export interface TooltipOpenChangeDetail {
  open: boolean;
  previousOpen: boolean;
  source: "hover" | "focus" | "escape" | "programmatic";
}


export interface TooltipOptions {
  open?: boolean;
  defaultOpen?: boolean;
  controlled?: boolean;
  disabled?: boolean;
  side?: TooltipSide;
  align?: TooltipAlign;
  sideOffset?: string;
  delayDuration?: string;
  disableHoverableContent?: boolean;
  portal?: boolean;
  portalContainer?: string;
}

class TooltipBehavior implements BambiBehavior {
  private static _idCounter = 0;
  private readonly root: Element;
  private options: TooltipOptions;
  private currentOpen = false;
  private readonly _id: string;
  private readonly destroyAbort = new AbortController();
  private bindAbort = new AbortController();
  private openTimer = 0;
  private closeTimer = 0;
  private portaledContent: HTMLElement | null = null;
  private portalPlaceholder: Comment | null = null;
  private originalContentParent: Node | null = null;
  private originalContentNextSibling: Node | null = null;

  constructor(root: Element, options: TooltipOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-tooltip-${++TooltipBehavior._idCounter}`;
  }

  sync(): void {
    this.bindAbort.abort();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.syncRootAttributes();
    this.applyState(this.optionOpen() ?? this.defaultOpen());
    this.bindEvents();
  }

  update(options: TooltipOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.syncRootAttributes();
    if (options.open !== undefined) this.applyState(options.open);
    else this.applyState(this.currentOpen);
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.clearTimers();
    this.restorePortal();
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, TOOLTIP_CONTROLLED) ||
        this.options.open !== undefined)
    );
  }

  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, TOOLTIP_DISABLED);
  }

  private side(): TooltipSide {
    return (this.options.side ??
      getAttr(this.root, TOOLTIP_SIDE, "top")) as TooltipSide;
  }

  private align(): TooltipAlign {
    return (this.options.align ??
      getAttr(this.root, TOOLTIP_ALIGN, "center")) as TooltipAlign;
  }

  private sideOffset(): number {
    return (
      Number(
        this.options.sideOffset ?? getAttr(this.root, TOOLTIP_SIDE_OFFSET, "4"),
      ) || 0
    );
  }

  private delayDuration(): number {
    return (
      Number(
        this.options.delayDuration ??
          getAttr(this.root, TOOLTIP_DELAY_DURATION, "700"),
      ) || 0
    );
  }

  private disableHoverableContent(): boolean {
    return (
      this.options.disableHoverableContent ??
      getBoolAttr(this.root, TOOLTIP_DISABLE_HOVERABLE_CONTENT)
    );
  }

  private portal(): boolean {
    return this.options.portal ?? getBoolAttr(this.root, TOOLTIP_PORTAL);
  }

  private portalContainer(): string {
    return (
      this.options.portalContainer ??
      getAttr(this.root, TOOLTIP_PORTAL_CONTAINER, "")
    );
  }

  private optionOpen(): boolean | undefined {
    if (this.options.open !== undefined) return this.options.open;
    if (this.root.hasAttribute(TOOLTIP_OPEN))
      return getBoolAttr(this.root, TOOLTIP_OPEN);
    return undefined;
  }

  private defaultOpen(): boolean {
    return (
      this.options.defaultOpen ?? getBoolAttr(this.root, TOOLTIP_DEFAULT_OPEN)
    );
  }

  private trigger(): HTMLElement | null {
    const trigger = this.root.querySelector(`[${TOOLTIP_TRIGGER}]`);
    return trigger instanceof HTMLElement ? trigger : null;
  }

  private content(): HTMLElement | null {
    if (this.portaledContent?.isConnected) return this.portaledContent;
    const content = this.root.querySelector(`[${TOOLTIP_CONTENT}]`);
    return content instanceof HTMLElement ? content : null;
  }

  private syncRootAttributes(): void {
    this.root.setAttribute(TOOLTIP_ROOT, "");
    setAttr(this.root, TOOLTIP_CONTROLLED, this.controlled() ? "true" : null);
    setAttr(this.root, TOOLTIP_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, TOOLTIP_SIDE, this.side());
    setAttr(this.root, TOOLTIP_ALIGN, this.align());
    setAttr(this.root, TOOLTIP_SIDE_OFFSET, String(this.sideOffset()));
    setAttr(this.root, TOOLTIP_DELAY_DURATION, String(this.delayDuration()));
    setAttr(
      this.root,
      TOOLTIP_DISABLE_HOVERABLE_CONTENT,
      this.disableHoverableContent() ? "true" : null,
    );
    setAttr(this.root, TOOLTIP_PORTAL, this.portal() ? "true" : null);
    setAttr(
      this.root,
      TOOLTIP_PORTAL_CONTAINER,
      this.portalContainer() || null,
    );
  }

  private setOpen(
    open: boolean,
    source: TooltipOpenChangeDetail["source"],
  ): void {
    const previousOpen = this.currentOpen;
    if (previousOpen === open) return;
    if (!this.controlled()) this.applyState(open);
    dispatchBambiEvent(this.root, TOOLTIP_EVENT_OPEN_CHANGE, {
      open,
      previousOpen,
      source,
    });
  }

  private applyState(open: boolean): void {
    this.currentOpen = open;
    const state = open ? "open" : "closed";
    setAttr(this.root, TOOLTIP_OPEN, open ? "true" : null);
    setAttr(this.root, TOOLTIP_STATE, state);
    const trigger = this.trigger();
    const content = this.content();
    if (open && content) this.mountPortal(content);
    if (trigger) {
      if (!trigger.id) trigger.id = `${this._id}-trigger`;
      trigger.setAttribute(TOOLTIP_TRIGGER, "");
      setAttr(trigger, TOOLTIP_STATE, state);
      setAttr(trigger, TOOLTIP_DISABLED, this.disabled() ? "true" : null);
      if (content)
        trigger.setAttribute(
          "aria-describedby",
          open ? content.id || `${this._id}-content` : "",
        );
      if (trigger instanceof HTMLButtonElement && !trigger.getAttribute("type"))
        trigger.type = "button";
    }
    if (content) {
      if (!content.id) content.id = `${this._id}-content`;
      content.setAttribute(TOOLTIP_CONTENT, "");
      content.setAttribute("role", "tooltip");
      setAttr(content, TOOLTIP_STATE, state);
      setAttr(content, TOOLTIP_SIDE, this.side());
      setAttr(content, TOOLTIP_ALIGN, this.align());
      content.hidden = !open;
      if (open) this.positionContent();
      else this.restorePortal();
    }
    for (const arrow of this.root.querySelectorAll(`[${TOOLTIP_ARROW}]`)) {
      arrow.setAttribute(TOOLTIP_ARROW, "");
      setAttr(arrow, TOOLTIP_STATE, state);
    }
  }

  private clearTimers(): void {
    window.clearTimeout(this.openTimer);
    window.clearTimeout(this.closeTimer);
  }

  private scheduleOpen(source: "hover" | "focus"): void {
    if (this.disabled()) return;
    this.clearTimers();
    this.openTimer = window.setTimeout(
      () => this.setOpen(true, source),
      this.delayDuration(),
    );
  }

  private scheduleClose(source: "hover" | "focus"): void {
    this.clearTimers();
    this.closeTimer = window.setTimeout(
      () => this.setOpen(false, source),
      this.disableHoverableContent() ? 0 : 120,
    );
  }

  private resolvePortalContainer(): HTMLElement | null {
    const selector = this.portalContainer();
    if (selector) {
      const target = this.root.ownerDocument.querySelector(selector);
      return target instanceof HTMLElement ? target : null;
    }
    return this.root.ownerDocument.body;
  }

  private mountPortal(content: HTMLElement): void {
    if (!this.portal() || this.portaledContent === content) return;
    const container = this.resolvePortalContainer();
    if (!container) return;
    this.originalContentParent = content.parentNode;
    this.originalContentNextSibling = content.nextSibling;
    this.portalPlaceholder = this.root.ownerDocument.createComment(
      "bambi-tooltip-portal",
    );
    this.originalContentParent?.insertBefore(this.portalPlaceholder, content);
    container.appendChild(content);
    this.portaledContent = content;
  }

  private restorePortal(): void {
    const content = this.portaledContent;
    if (!content) return;
    this.originalContentParent?.insertBefore(
      content,
      this.originalContentNextSibling,
    );
    this.portalPlaceholder?.remove();
    this.portaledContent = null;
    this.portalPlaceholder = null;
    this.originalContentParent = null;
    this.originalContentNextSibling = null;
  }

  private positionContent(): void {
    const trigger = this.trigger();
    const content = this.content();
    if (!trigger || !content || typeof window === "undefined") return;
    const triggerRect = trigger.getBoundingClientRect();
    const contentRect = content.getBoundingClientRect();
    const side = this.side();
    const offset = this.sideOffset();
    let top =
      side === "top"
        ? triggerRect.top - contentRect.height - offset
        : side === "bottom"
          ? triggerRect.bottom + offset
          : triggerRect.top + (triggerRect.height - contentRect.height) / 2;
    let left =
      side === "left"
        ? triggerRect.left - contentRect.width - offset
        : side === "right"
          ? triggerRect.right + offset
          : triggerRect.left + (triggerRect.width - contentRect.width) / 2;
    if (this.align() === "start") {
      if (side === "top" || side === "bottom") left = triggerRect.left;
      else top = triggerRect.top;
    }
    if (this.align() === "end") {
      if (side === "top" || side === "bottom")
        left = triggerRect.right - contentRect.width;
      else top = triggerRect.bottom - contentRect.height;
    }
    content.style.position = "fixed";
    content.style.top = `${Math.max(4, Math.min(top, window.innerHeight - contentRect.height - 4))}px`;
    content.style.left = `${Math.max(4, Math.min(left, window.innerWidth - contentRect.width - 4))}px`;
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    const trigger = this.trigger();
    const content = this.content();
    trigger?.addEventListener(
      "pointerenter",
      () => this.scheduleOpen("hover"),
      { signal },
    );
    trigger?.addEventListener(
      "pointerleave",
      () => this.scheduleClose("hover"),
      { signal },
    );
    trigger?.addEventListener("focus", () => this.scheduleOpen("focus"), {
      signal,
    });
    trigger?.addEventListener("blur", () => this.scheduleClose("focus"), {
      signal,
    });
    if (!this.disableHoverableContent()) {
      content?.addEventListener("pointerenter", () => this.clearTimers(), {
        signal,
      });
      content?.addEventListener(
        "pointerleave",
        () => this.scheduleClose("hover"),
        { signal },
      );
    }
    this.root.ownerDocument.addEventListener(
      "keydown",
      (event) => {
        if (event.key === "Escape") this.setOpen(false, "escape");
      },
      { signal },
    );
    window.addEventListener(
      "resize",
      () => this.currentOpen && this.positionContent(),
      { signal },
    );
    window.addEventListener(
      "scroll",
      () => this.currentOpen && this.positionContent(),
      { capture: true, signal },
    );
  }
}

export interface TooltipProps extends Omit<TooltipOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"span">, keyof Omit<TooltipOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onOpenChange?: (detail: TooltipOpenChangeDetail) => void;
}

export interface TooltipTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type TooltipContentProps = React.ComponentPropsWithoutRef<"div">;

export type TooltipArrowProps = React.ComponentPropsWithoutRef<"div">;

export function Tooltip({
  open,
  defaultOpen,
  disabled,
  side = "top",
  align = "center",
  sideOffset,
  delayDuration,
  disableHoverableContent,
  portal,
  portalContainer,
  onOpenChange,
  children,
  ...props
}: TooltipProps) {
  const rootRef = React.useRef<HTMLSpanElement>(null);
  const behaviorRef = React.useRef<TooltipBehavior | null>(null);
  const controlled = open !== undefined;
  const onOpenChangeRef = React.useRef(onOpenChange);

  React.useEffect(() => {
    if (open !== undefined && defaultOpen !== undefined) {
      console.warn(
        "[bambiui/tooltip] Tooltip received both `open` and `defaultOpen`. Use `open` for controlled mode or `defaultOpen` for uncontrolled mode, not both.",
      );
    }
  }, [defaultOpen, open]);
  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onOpenChangeHandler = (event: Event) => {
      const e = event as CustomEvent<TooltipOpenChangeDetail>;
      onOpenChangeRef.current?.(e.detail);
    };
    root.addEventListener(TOOLTIP_EVENT_OPEN_CHANGE, onOpenChangeHandler);

    const behavior = new TooltipBehavior(root, {
      open,
      defaultOpen,
      disabled,
      side,
      align,
      sideOffset,
      delayDuration,
      disableHoverableContent,
      portal,
      portalContainer,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(TOOLTIP_EVENT_OPEN_CHANGE, onOpenChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      open,
      defaultOpen,
      disabled,
      side,
      align,
      sideOffset,
      delayDuration,
      disableHoverableContent,
      portal,
      portalContainer,
      controlled,
    });
  }, [open, defaultOpen, disabled, side, align, sideOffset, delayDuration, disableHoverableContent, portal, portalContainer, controlled]);

  return (
    <span
      {...props}
      ref={rootRef}
      {...{ [TOOLTIP_ROOT]: "" }}
      {...{ [TOOLTIP_OPEN]: open ? "true" : undefined }}
      {...{ [TOOLTIP_DEFAULT_OPEN]: defaultOpen ? "true" : undefined }}
      {...{ [TOOLTIP_DISABLED]: disabled ? "true" : undefined }}
      {...{ [TOOLTIP_SIDE]: side }}
      {...{ [TOOLTIP_ALIGN]: align }}
      {...{ [TOOLTIP_SIDE_OFFSET]: sideOffset }}
      {...{ [TOOLTIP_DELAY_DURATION]: delayDuration }}
      {...{ [TOOLTIP_DISABLE_HOVERABLE_CONTENT]: disableHoverableContent ? "true" : undefined }}
      {...{ [TOOLTIP_PORTAL]: portal ? "true" : undefined }}
      {...{ [TOOLTIP_PORTAL_CONTAINER]: portalContainer }}
      {...{ [TOOLTIP_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </span>
  );
}

export function TooltipTrigger({ disabled, children, ...props }: TooltipTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [TOOLTIP_DISABLED]: disabled ? "true" : undefined }}
      {...{ [TOOLTIP_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function TooltipContent({ children, ...props }: TooltipContentProps) {

  return (
    <div
      {...props}
      {...{ [TOOLTIP_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function TooltipArrow({ children, ...props }: TooltipArrowProps) {

  return (
    <div
      {...props}
      {...{ [TOOLTIP_ARROW]: "" }}
    >
      {children}
    </div>
  );
}
