// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const BUTTON_ROOT = "data-bambi-button" as const;
const BUTTON_VARIANT = "data-variant" as const;
const BUTTON_SIZE = "data-size" as const;
const BUTTON_DISABLED = "data-disabled" as const;
const BUTTON_LOADING = "data-loading" as const;

export type ButtonVariant =
  | "primary"
  | "secondary"
  | "outline"
  | "ghost"
  | "danger"
  | "success"
  | "warning";
export type ButtonSize = "sm" | "md" | "lg" | "icon";


export interface ButtonOptions {
  as?: string;
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  loading?: boolean;
}

class ButtonBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: ButtonOptions;

  constructor(root: Element, options: ButtonOptions = {}) {
    this.root = root;
    this.options = options;
  }

  sync(): void {
    this.applyState();
  }

  update(options: ButtonOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.applyState();
  }

  destroy(): void {}

  private applyState(): void {
    const variant = this.options.variant ?? getAttr(this.root, BUTTON_VARIANT, "primary");
    const size = this.options.size ?? getAttr(this.root, BUTTON_SIZE, "md");
    const disabled = this.options.disabled ?? getBoolAttr(this.root, BUTTON_DISABLED);
    const loading = this.options.loading ?? getBoolAttr(this.root, BUTTON_LOADING);
    const effectivelyDisabled = disabled || loading;
    const isNativeButton = this.root.tagName.toLowerCase() === "button";

    setAttr(this.root, BUTTON_VARIANT, variant);
    setAttr(this.root, BUTTON_SIZE, size);
    setAttr(this.root, BUTTON_DISABLED, effectivelyDisabled ? "true" : null);
    setAttr(this.root, BUTTON_LOADING, loading ? "true" : null);
    setAttr(this.root, "aria-busy", loading ? "true" : null);

    if (isNativeButton) {
      if (this.root instanceof HTMLButtonElement && !this.root.getAttribute("type")) {
        this.root.type = "button";
      }
      if (this.root instanceof HTMLButtonElement) {
        this.root.disabled = effectivelyDisabled;
      } else {
        setAttr(this.root, "disabled", effectivelyDisabled ? "" : null);
      }
      this.root.removeAttribute("aria-disabled");
    } else {
      setAttr(this.root, "disabled", null);
      setAttr(this.root, "aria-disabled", effectivelyDisabled ? "true" : null);
    }
  }
}

export interface ButtonProps extends ButtonOptions, Omit<React.HTMLAttributes<HTMLElement>, keyof ButtonOptions> {
  children?: React.ReactNode;
  className?: string;
  [key: string]: unknown;
}



export function Button({
  as,
  variant = "primary",
  size = "md",
  disabled,
  loading,
  children,
  ...props
}: ButtonProps) {
  const rootRef = React.useRef<HTMLElement>(null);
  const behaviorRef = React.useRef<ButtonBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new ButtonBehavior(root, {
      as,
      variant,
      size,
      disabled,
      loading,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, [as]);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      as,
      variant,
      size,
      disabled,
      loading,
    });
  }, [as, variant, size, disabled, loading]);

  const Component = (as ?? "button") as keyof React.JSX.IntrinsicElements;
  const isNativeElement = Component === "button";
  const effectiveDisabled = Boolean(disabled || loading);

  return React.createElement(
    Component,
    {
      ...props,
      ref: rootRef,
      [BUTTON_ROOT]: "",
      type: isNativeElement ? ((props as { type?: string }).type ?? "button") : undefined,
      disabled: isNativeElement ? effectiveDisabled : undefined,
      "aria-disabled": !isNativeElement && effectiveDisabled ? "true" : undefined,
      "aria-busy": loading ? "true" : undefined,
      [BUTTON_VARIANT]: variant,
      [BUTTON_SIZE]: size,
      "data-disabled": effectiveDisabled ? "true" : undefined,
      [BUTTON_LOADING]: loading ? "true" : undefined,
    },
    children,
  );
}
