// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const ASPECT_RATIO_ROOT = "data-bambi-aspect-ratio" as const;
const ASPECT_RATIO_CONTENT = "data-bambi-aspect-ratio-content" as const;
const ASPECT_RATIO_RATIO = "data-ratio" as const;


export interface AspectRatioOptions {
  ratio?: string;
}

class AspectRatioBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: AspectRatioOptions;

  constructor(root: Element, options: AspectRatioOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: AspectRatioOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(ASPECT_RATIO_ROOT, "");
    for (const part of this.root.querySelectorAll(`[${ASPECT_RATIO_CONTENT}]`)) part.setAttribute(ASPECT_RATIO_CONTENT, "");
    const ratio = this.options.ratio ?? getAttr(this.root, ASPECT_RATIO_RATIO, "");
    setAttr(this.root, ASPECT_RATIO_RATIO, ratio || null);
    if (ratio) (this.root as HTMLElement).style.setProperty("--bambi-aspect-ratio", ratio);
  }
}

export interface AspectRatioProps extends AspectRatioOptions, Omit<React.ComponentPropsWithoutRef<"div">, keyof AspectRatioOptions> {
  children?: React.ReactNode;
  className?: string;
}

export type AspectRatioContentProps = React.ComponentPropsWithoutRef<"div">;

export function AspectRatio({
  ratio,
  children,
  ...props
}: AspectRatioProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<AspectRatioBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new AspectRatioBehavior(root, {
      ratio,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      ratio,
    });
  }, [ratio]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [ASPECT_RATIO_ROOT]: "" }}
      {...{ [ASPECT_RATIO_RATIO]: ratio }}
    >
      {children}
    </div>
  );
}

export function AspectRatioContent({ children, ...props }: AspectRatioContentProps) {

  return (
    <div
      {...props}
      {...{ [ASPECT_RATIO_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}
