// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const SPINNER_ROOT = "data-bambi-spinner" as const;
const SPINNER_SIZE = "data-size" as const;
const SPINNER_LABEL = "data-label" as const;

export type SpinnerSize = "sm" | "md" | "lg";


export interface SpinnerOptions {
  size?: SpinnerSize;
  label?: string;
}

class SpinnerBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: SpinnerOptions;

  constructor(root: Element, options: SpinnerOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: SpinnerOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(SPINNER_ROOT, "");
    const size = this.options.size ?? getAttr(this.root, SPINNER_SIZE, "sm") as SpinnerSize;
    setAttr(this.root, SPINNER_SIZE, size);
    const label = this.options.label ?? getAttr(this.root, SPINNER_LABEL, "");
    setAttr(this.root, SPINNER_LABEL, label || null);
    this.root.setAttribute("role", "status");
    this.root.setAttribute("aria-live", "polite");
    this.root.setAttribute("aria-busy", "true");
    this.root.setAttribute("aria-label", label || "Loading");
  }
}

export interface SpinnerProps extends SpinnerOptions, Omit<React.ComponentPropsWithoutRef<"span">, keyof SpinnerOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Spinner({
  size = "sm",
  label,
  children,
  ...props
}: SpinnerProps) {
  const rootRef = React.useRef<HTMLSpanElement>(null);
  const behaviorRef = React.useRef<SpinnerBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new SpinnerBehavior(root, {
      size,
      label,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      size,
      label,
    });
  }, [size, label]);

  return (
    <span
      {...props}
      ref={rootRef}
      {...{ [SPINNER_ROOT]: "" }}
      {...{ [SPINNER_SIZE]: size }}
      {...{ [SPINNER_LABEL]: label }}
    >
      {children}
    </span>
  );
}
