// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const LABEL_ROOT = "data-bambi-label" as const;
const LABEL_FOR = "data-for" as const;
const LABEL_DISABLED = "data-disabled" as const;
const LABEL_REQUIRED = "data-required" as const;


export interface LabelOptions {
  htmlFor?: string;
  disabled?: boolean;
  required?: boolean;
}

class LabelBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: LabelOptions;

  constructor(root: Element, options: LabelOptions = {}) {
    this.root = root;
    this.options = options;
  }

  sync(): void {
    this.applyState();
  }

  update(options: LabelOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.applyState();
  }

  destroy(): void {}

  private applyState(): void {
    const htmlFor = this.options.htmlFor ?? getAttr(this.root, LABEL_FOR, "");
    const disabled = this.options.disabled ?? getBoolAttr(this.root, LABEL_DISABLED);
    const required = this.options.required ?? getBoolAttr(this.root, LABEL_REQUIRED);

    this.root.setAttribute(LABEL_ROOT, "");
    setAttr(this.root, LABEL_FOR, htmlFor || null);
    setAttr(this.root, LABEL_DISABLED, disabled ? "true" : null);
    setAttr(this.root, LABEL_REQUIRED, required ? "true" : null);
    setAttr(this.root, "aria-disabled", disabled ? "true" : null);
    if (this.root instanceof HTMLLabelElement) {
      if (htmlFor) this.root.htmlFor = htmlFor;
      else this.root.removeAttribute("for");
    } else {
      setAttr(this.root, "for", htmlFor || null);
    }
  }
}

export interface LabelProps extends LabelOptions, Omit<React.ComponentPropsWithoutRef<"label">, keyof LabelOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Label({
  htmlFor,
  disabled,
  required,
  children,
  ...props
}: LabelProps) {
  const rootRef = React.useRef<HTMLLabelElement>(null);
  const behaviorRef = React.useRef<LabelBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new LabelBehavior(root, {
      htmlFor,
      disabled,
      required,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      htmlFor,
      disabled,
      required,
    });
  }, [htmlFor, disabled, required]);

  return (
    <label
      {...props}
      ref={rootRef}
      {...{ [LABEL_ROOT]: "" }}
      {...{ [LABEL_FOR]: htmlFor }}
      {...{ [LABEL_DISABLED]: disabled ? "true" : undefined }}
      {...{ [LABEL_REQUIRED]: required ? "true" : undefined }}
    >
      {children}
    </label>
  );
}
