// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp, type RovingFocusOptions, type RovingFocus, createRovingFocus } from "../bambi-helpers";

const ACCORDION_ROOT = "data-bambi-accordion" as const;
const ACCORDION_ITEM = "data-bambi-accordion-item" as const;
const ACCORDION_HEADER = "data-bambi-accordion-header" as const;
const ACCORDION_TRIGGER = "data-bambi-accordion-trigger" as const;
const ACCORDION_CONTENT = "data-bambi-accordion-content" as const;
const ACCORDION_TYPE = "data-type" as const;
const ACCORDION_VALUE = "data-value" as const;
const ACCORDION_DEFAULT_VALUE = "data-default-value" as const;
const ACCORDION_CONTROLLED = "data-controlled" as const;
const ACCORDION_COLLAPSIBLE = "data-collapsible" as const;
const ACCORDION_DISABLED = "data-disabled" as const;
const ACCORDION_ORIENTATION = "data-orientation" as const;
const ACCORDION_DIR = "data-dir" as const;
const ACCORDION_STATE = "data-state" as const;
const ACCORDION_EVENT_VALUE_CHANGE = "bambi:value-change" as const;

export type AccordionType = "single" | "multiple";
export type AccordionOrientation = "horizontal" | "vertical";
export type AccordionDir = "ltr" | "rtl";
export type AccordionValue = string | string[];

export interface AccordionValueChangeDetail {
  value: AccordionValue;
  previousValue: AccordionValue;
  source: "click" | "keyboard" | "programmatic";
}


export interface AccordionOptions {
  type?: AccordionType;
  value?: AccordionValue;
  defaultValue?: AccordionValue;
  collapsible?: boolean;
  disabled?: boolean;
  orientation?: AccordionOrientation;
  dir?: AccordionDir;
  controlled?: boolean;
}

function parseValue(
  value: AccordionValue | string | null | undefined,
  type: AccordionType,
): AccordionValue {
  if (Array.isArray(value)) return value;
  if (value === undefined || value === null || value === "")
    return type === "multiple" ? [] : "";
  if (type === "multiple")
    return String(value)
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  return String(value);
}

function serializeValue(value: AccordionValue): string {
  return Array.isArray(value) ? value.join(",") : value;
}

function valueIncludes(value: AccordionValue, itemValue: string): boolean {
  return Array.isArray(value) ? value.includes(itemValue) : value === itemValue;
}

function sameValue(a: AccordionValue, b: AccordionValue): boolean {
  return serializeValue(a) === serializeValue(b);
}

function measureContentSize(content: HTMLElement): {
  height: number;
  width: number;
} {
  const wasHidden = content.hidden;
  if (wasHidden) content.hidden = false;
  const height = content.scrollHeight;
  const width = content.scrollWidth;
  if (wasHidden) content.hidden = true;
  return { height, width };
}

class AccordionBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: AccordionOptions;
  private currentValue: AccordionValue = "";
  private readonly _id: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private rovingFocus: RovingFocus | null = null;

  constructor(root: Element, options: AccordionOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-accordion-${++AccordionBehavior._idCounter}`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.syncRootAttributes();
    this.syncHeaders();

    const initialValue = this.optionValue() ?? this.defaultValue();
    this.applyState(initialValue);
    this.bindEvents();
  }

  update(options: AccordionOptions = {}): void {
    const prevOrientation = this.orientation();
    this.options = { ...this.options, ...options };
    this.syncRootAttributes();
    this.syncHeaders();
    if (this.orientation() !== prevOrientation) {
      this.rovingFocus?.destroy();
      this.rovingFocus = this.createRovingFocusInstance();
    }
    if (options.value !== undefined)
      this.applyState(parseValue(options.value, this.type()));
    else this.applyState(this.currentValue);
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
  }

  private type(): AccordionType {
    return (this.options.type ??
      getAttr(this.root, ACCORDION_TYPE, "single")) as AccordionType;
  }

  private orientation(): AccordionOrientation {
    return (this.options.orientation ??
      getAttr(
        this.root,
        ACCORDION_ORIENTATION,
        "vertical",
      )) as AccordionOrientation;
  }

  private dir(): AccordionDir {
    return (this.options.dir ??
      getAttr(
        this.root,
        ACCORDION_DIR,
        document.dir === "rtl" ? "rtl" : "ltr",
      )) as AccordionDir;
  }

  private collapsible(): boolean {
    return (
      this.options.collapsible ?? getBoolAttr(this.root, ACCORDION_COLLAPSIBLE)
    );
  }

  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, ACCORDION_DISABLED);
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, ACCORDION_CONTROLLED) ||
        this.options.value !== undefined)
    );
  }

  private optionValue(): AccordionValue | undefined {
    if (this.options.value !== undefined)
      return parseValue(this.options.value, this.type());
    const attr = this.root.getAttribute(ACCORDION_VALUE);
    return attr === null ? undefined : parseValue(attr, this.type());
  }

  private defaultValue(): AccordionValue {
    return parseValue(
      this.options.defaultValue ??
        this.root.getAttribute(ACCORDION_DEFAULT_VALUE),
      this.type(),
    );
  }

  private items(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${ACCORDION_ITEM}]`));
  }

  private triggers(): HTMLElement[] {
    return Array.from(
      this.root.querySelectorAll(`[${ACCORDION_TRIGGER}]`),
    ).filter((el): el is HTMLElement => el instanceof HTMLElement);
  }

  private contentForItem(item: Element): HTMLElement | null {
    const content = item.querySelector(`[${ACCORDION_CONTENT}]`);
    return content instanceof HTMLElement ? content : null;
  }

  private triggerForItem(item: Element): HTMLElement | null {
    const trigger = item.querySelector(`[${ACCORDION_TRIGGER}]`);
    return trigger instanceof HTMLElement ? trigger : null;
  }

  private itemForTrigger(trigger: Element): Element | null {
    return trigger.closest(`[${ACCORDION_ITEM}]`);
  }

  private valueForItem(item: Element): string {
    return item.getAttribute(ACCORDION_VALUE) ?? "";
  }

  private isItemDisabled(item: Element): boolean {
    return this.disabled() || getBoolAttr(item, ACCORDION_DISABLED);
  }

  private syncRootAttributes(): void {
    this.root.setAttribute(ACCORDION_ROOT, "");
    setAttr(this.root, ACCORDION_TYPE, this.type());
    setAttr(this.root, ACCORDION_ORIENTATION, this.orientation());
    setAttr(this.root, ACCORDION_DIR, this.dir());
    setAttr(
      this.root,
      ACCORDION_COLLAPSIBLE,
      this.collapsible() ? "true" : null,
    );
    setAttr(this.root, ACCORDION_DISABLED, this.disabled() ? "true" : null);
    setAttr(this.root, ACCORDION_CONTROLLED, this.controlled() ? "true" : null);
  }

  private syncHeaders(): void {
    for (const header of this.root.querySelectorAll(`[${ACCORDION_HEADER}]`)) {
      header.setAttribute(ACCORDION_HEADER, "");
    }
  }

  private applyState(value: AccordionValue): void {
    const normalized = parseValue(value, this.type());
    this.currentValue = normalized;
    setAttr(this.root, ACCORDION_VALUE, serializeValue(normalized) || null);

    for (const item of this.items()) {
      const itemValue = this.valueForItem(item);
      const open = itemValue ? valueIncludes(normalized, itemValue) : false;
      const state = open ? "open" : "closed";
      const disabled = this.isItemDisabled(item);
      const trigger = this.triggerForItem(item);
      const content = this.contentForItem(item);

      if (!item.id)
        item.id = `${this._id}-item-${itemValue || this.items().indexOf(item)}`;
      setAttr(item, ACCORDION_STATE, state);
      setAttr(item, ACCORDION_DISABLED, disabled ? "true" : null);

      if (trigger) {
        if (!trigger.id) trigger.id = `${item.id}-trigger`;
        trigger.setAttribute(ACCORDION_TRIGGER, "");
        setAttr(trigger, ACCORDION_VALUE, itemValue);
        setAttr(trigger, ACCORDION_STATE, state);
        setAttr(trigger, ACCORDION_DISABLED, disabled ? "true" : null);
        trigger.setAttribute("aria-expanded", open ? "true" : "false");
        if (content)
          trigger.setAttribute(
            "aria-controls",
            content.id || `${item.id}-content`,
          );
        const lockedOpen =
          open && this.type() === "single" && !this.collapsible();
        if (trigger instanceof HTMLButtonElement) {
          if (!trigger.getAttribute("type")) trigger.type = "button";
          trigger.disabled = disabled;
          trigger.setAttribute("aria-disabled", lockedOpen ? "true" : "false");
        } else {
          setAttr(
            trigger,
            "aria-disabled",
            disabled || lockedOpen ? "true" : null,
          );
        }
        trigger.tabIndex = disabled ? -1 : 0;
      }

      if (content) {
        if (!content.id) content.id = `${item.id}-content`;
        content.setAttribute(ACCORDION_CONTENT, "");
        setAttr(content, ACCORDION_STATE, state);
        setAttr(content, ACCORDION_DISABLED, disabled ? "true" : null);
        if (trigger) content.setAttribute("aria-labelledby", trigger.id);
        const size = measureContentSize(content);
        content.hidden = !open;
        content.style.setProperty(
          "--bambi-accordion-content-height",
          `${size.height}px`,
        );
        content.style.setProperty(
          "--bambi-accordion-content-width",
          `${size.width}px`,
        );
      }
    }
  }

  private nextValue(itemValue: string): AccordionValue {
    const type = this.type();
    const current = parseValue(this.currentValue, type);
    if (type === "multiple") {
      const values = Array.isArray(current)
        ? current
        : current
          ? [current]
          : [];
      return values.includes(itemValue)
        ? values.filter((value) => value !== itemValue)
        : [...values, itemValue];
    }
    if (current === itemValue) return this.collapsible() ? "" : current;
    return itemValue;
  }

  private setValue(
    value: AccordionValue,
    source: AccordionValueChangeDetail["source"],
  ): void {
    const previousValue = this.currentValue;
    if (sameValue(previousValue, value)) return;
    if (!this.controlled()) this.applyState(value);
    dispatchBambiEvent(this.root, ACCORDION_EVENT_VALUE_CHANGE, { value, previousValue, source });
  }

  private activateTrigger(
    trigger: Element,
    source: AccordionValueChangeDetail["source"],
  ): void {
    const item = this.itemForTrigger(trigger);
    if (!item || this.isItemDisabled(item)) return;
    const value = this.valueForItem(item);
    if (!value) return;
    this.setValue(this.nextValue(value), source);
  }

  private createRovingFocusInstance(): RovingFocus {
    return createRovingFocus(this.root, {
      orientation: this.orientation(),
      getItems: () => this.triggers(),
      isDisabled: (trigger) => {
        const item = this.itemForTrigger(trigger);
        return !item || this.isItemDisabled(item);
      },
      onFocus: (trigger) => {
        if (trigger instanceof HTMLElement) trigger.focus();
      },
      onActivate: (trigger) => this.activateTrigger(trigger, "keyboard"),
    });
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const trigger = target.closest(`[${ACCORDION_TRIGGER}]`);
        if (!trigger || !this.root.contains(trigger)) return;
        this.activateTrigger(trigger, "click");
      },
      { signal },
    );
    this.rovingFocus = this.createRovingFocusInstance();
  }
}

export interface AccordionProps extends Omit<AccordionOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<AccordionOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onValueChange?: (detail: AccordionValueChangeDetail) => void;
}

export interface AccordionItemProps extends React.ComponentPropsWithoutRef<"div"> {
  value: string;
  disabled?: boolean;
}

export type AccordionHeaderProps = React.ComponentPropsWithoutRef<"h3">;

export interface AccordionTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type AccordionContentProps = React.ComponentPropsWithoutRef<"div">;

export function Accordion({
  type = "single",
  value,
  defaultValue,
  collapsible,
  disabled,
  orientation = "vertical",
  dir,
  onValueChange,
  children,
  ...props
}: AccordionProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<AccordionBehavior | null>(null);
  const controlled = value !== undefined;
  const onValueChangeRef = React.useRef(onValueChange);

  React.useEffect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/accordion] Accordion received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  }, [defaultValue, value]);
  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<AccordionValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(ACCORDION_EVENT_VALUE_CHANGE, onValueChangeHandler);

    const behavior = new AccordionBehavior(root, {
      type,
      value,
      defaultValue,
      collapsible,
      disabled,
      orientation,
      dir,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(ACCORDION_EVENT_VALUE_CHANGE, onValueChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      type,
      value,
      defaultValue,
      collapsible,
      disabled,
      orientation,
      dir,
      controlled,
    });
  }, [type, value, defaultValue, collapsible, disabled, orientation, dir, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [ACCORDION_ROOT]: "" }}
      {...{ [ACCORDION_TYPE]: type }}
      {...{ [ACCORDION_VALUE]: value }}
      {...{ [ACCORDION_DEFAULT_VALUE]: defaultValue }}
      {...{ [ACCORDION_COLLAPSIBLE]: collapsible ? "true" : undefined }}
      {...{ [ACCORDION_DISABLED]: disabled ? "true" : undefined }}
      {...{ [ACCORDION_ORIENTATION]: orientation }}
      {...{ [ACCORDION_DIR]: dir }}
      {...{ [ACCORDION_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function AccordionItem({ value, disabled, children, ...props }: AccordionItemProps) {

  return (
    <div
      {...props}
      {...{ [ACCORDION_DISABLED]: disabled ? "true" : undefined }}
      {...{ [ACCORDION_ITEM]: "" }}
      {...{ [ACCORDION_VALUE]: value }}
    >
      {children}
    </div>
  );
}

export function AccordionHeader({ children, ...props }: AccordionHeaderProps) {

  return (
    <h3
      {...props}
      {...{ [ACCORDION_HEADER]: "" }}
    >
      {children}
    </h3>
  );
}

export function AccordionTrigger({ disabled, children, ...props }: AccordionTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [ACCORDION_DISABLED]: disabled ? "true" : undefined }}
      {...{ [ACCORDION_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function AccordionContent({ children, ...props }: AccordionContentProps) {

  return (
    <div
      {...props}
      {...{ [ACCORDION_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}
