// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, dispatchBambiEvent, clamp, type LayerHandle, createLayerHandle, getTopLayer, isInLayerStack, type DismissableLayerEventDetail, type DismissableLayerOptions, type DismissableLayer, type DismissableLayerEvent, createDismissableLayer, type FocusScopeOptions, type FocusScope, getFocusableElements, createFocusScope, type ScrollLock, createScrollLock } from "../bambi-helpers";

const DIALOG_ROOT = "data-bambi-dialog" as const;
const DIALOG_TRIGGER = "data-bambi-dialog-trigger" as const;
const DIALOG_PORTAL = "data-bambi-dialog-portal" as const;
const DIALOG_OVERLAY = "data-bambi-dialog-overlay" as const;
const DIALOG_CONTENT = "data-bambi-dialog-content" as const;
const DIALOG_TITLE = "data-bambi-dialog-title" as const;
const DIALOG_DESCRIPTION = "data-bambi-dialog-description" as const;
const DIALOG_CLOSE = "data-bambi-dialog-close" as const;
const DIALOG_OPEN = "data-open" as const;
const DIALOG_DEFAULT_OPEN = "data-default-open" as const;
const DIALOG_CONTROLLED = "data-controlled" as const;
const DIALOG_MODAL = "data-modal" as const;
const DIALOG_DISABLED = "data-disabled" as const;
const DIALOG_ROLE = "data-role" as const;
const DIALOG_INITIAL_FOCUS = "data-initial-focus" as const;
const DIALOG_PORTAL_CONTAINER = "data-portal-container" as const;
const DIALOG_STATE = "data-state" as const;
const DIALOG_EVENT_OPEN_CHANGE = "bambi:open-change" as const;
const DIALOG_EVENT_ESCAPE_KEY_DOWN = "bambi:escape-key-down" as const;
const DIALOG_EVENT_POINTER_DOWN_OUTSIDE =
  "bambi:pointer-down-outside" as const;
const DIALOG_EVENT_INTERACT_OUTSIDE = "bambi:interact-outside" as const;

export type DialogRole = "dialog" | "alertdialog";

export interface DialogOpenChangeDetail {
  open: boolean;
  previousOpen: boolean;
  source: "trigger" | "close" | "escape" | "outside" | "programmatic";
}

export interface DialogEscapeKeyDownDetail {
  originalEvent: KeyboardEvent;
}

export interface DialogPointerDownOutsideDetail {
  originalEvent: Event;
}

export interface DialogInteractOutsideDetail {
  originalEvent: Event;
}

export type DialogOutsideInteractionDetail =
  | DialogPointerDownOutsideDetail
  | DialogInteractOutsideDetail;


export interface DialogOptions {
  open?: boolean;
  defaultOpen?: boolean;
  controlled?: boolean;
  modal?: boolean;
  disabled?: boolean;
  role?: DialogRole;
  initialFocus?: string;
  portalContainer?: string;
}

interface HiddenSiblingState {
  element: HTMLElement;
  ariaHidden: string | null;
  inert: boolean;
}

type DialogPrimitiveReferenceTypes =
  | LayerHandle
  | DismissableLayerEventDetail
  | DismissableLayerOptions
  | FocusScopeOptions;

const dialogPrimitiveReferenceTypes: DialogPrimitiveReferenceTypes | null =
  null;
const dialogPrimitiveReferenceValues = [
  clamp,
  createLayerHandle,
  getTopLayer,
  isInLayerStack,
  getFocusableElements,
] as const;
void dialogPrimitiveReferenceTypes;
void dialogPrimitiveReferenceValues;

function dispatchCancelableEvent<Detail>(
  element: Element,
  name: string,
  detail: Detail,
): CustomEvent<Detail> {
  const event = new CustomEvent<Detail>(name, {
    bubbles: true,
    cancelable: true,
    composed: false,
    detail,
  });
  element.dispatchEvent(event);
  return event;
}

class DialogBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: DialogOptions;
  private currentOpen = false;
  private readonly _id: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private dismissableLayer: DismissableLayer | null = null;
  private focusScope: FocusScope | null = null;
  private scrollLock: ScrollLock | null = null;
  private portaledNode: HTMLElement | null = null;
  private portalPlaceholder: Comment | null = null;
  private originalPortalParent: Node | null = null;
  private originalPortalNextSibling: Node | null = null;
  private hiddenSiblings: HiddenSiblingState[] = [];

  constructor(root: Element, options: DialogOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-dialog-${++DialogBehavior._idCounter}`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.destroyLayerBehavior(false);
    this.bindAbort = new AbortController();
    if (!this.root.id) this.root.id = this._id;
    this.syncRootAttributes();
    const initialOpen = this.optionOpen() ?? this.defaultOpen();
    this.applyState(initialOpen);
    this.bindEvents();
  }

  update(options: DialogOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.syncRootAttributes();
    if (options.open !== undefined) this.applyState(options.open);
    else this.applyState(this.currentOpen);
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.destroyLayerBehavior(true);
    this.restorePortal();
    this.restoreOutsideTree();
  }

  private controlled(): boolean {
    return (
      this.options.controlled ??
      (getBoolAttr(this.root, DIALOG_CONTROLLED) ||
        this.options.open !== undefined)
    );
  }

  private modal(): boolean {
    return (
      this.options.modal ?? this.root.getAttribute(DIALOG_MODAL) !== "false"
    );
  }

  private disabled(): boolean {
    return this.options.disabled ?? getBoolAttr(this.root, DIALOG_DISABLED);
  }

  private role(): DialogRole {
    const role = this.options.role ?? getAttr(this.root, DIALOG_ROLE, "dialog");
    return role === "alertdialog" ? "alertdialog" : "dialog";
  }

  private initialFocus(): string {
    return (
      this.options.initialFocus ?? getAttr(this.root, DIALOG_INITIAL_FOCUS, "")
    );
  }

  private portalContainer(): string {
    return (
      this.options.portalContainer ??
      getAttr(this.root, DIALOG_PORTAL_CONTAINER, "")
    );
  }

  private optionOpen(): boolean | undefined {
    if (this.options.open !== undefined) return this.options.open;
    if (this.root.hasAttribute(DIALOG_OPEN))
      return getBoolAttr(this.root, DIALOG_OPEN);
    return undefined;
  }

  private defaultOpen(): boolean {
    return (
      this.options.defaultOpen ?? getBoolAttr(this.root, DIALOG_DEFAULT_OPEN)
    );
  }

  private trigger(): HTMLElement | null {
    const trigger = this.root.querySelector(`[${DIALOG_TRIGGER}]`);
    return trigger instanceof HTMLElement ? trigger : null;
  }

  private portal(): HTMLElement | null {
    if (this.portaledNode?.hasAttribute(DIALOG_PORTAL))
      return this.portaledNode;
    const portal = this.root.querySelector(`[${DIALOG_PORTAL}]`);
    return portal instanceof HTMLElement ? portal : null;
  }

  private overlay(): HTMLElement | null {
    const scope = this.portaledNode ?? this.root;
    const overlay = scope.querySelector(`[${DIALOG_OVERLAY}]`);
    return overlay instanceof HTMLElement ? overlay : null;
  }

  private content(): HTMLElement | null {
    const scope = this.portaledNode ?? this.root;
    const content = scope.querySelector(`[${DIALOG_CONTENT}]`);
    return content instanceof HTMLElement ? content : null;
  }

  private syncRootAttributes(): void {
    this.root.setAttribute(DIALOG_ROOT, "");
    setAttr(this.root, DIALOG_CONTROLLED, this.controlled() ? "true" : null);
    setAttr(this.root, DIALOG_MODAL, this.modal() ? "true" : "false");
    setAttr(this.root, DIALOG_DISABLED, this.disabled() ? "true" : null);
    setAttr(
      this.root,
      DIALOG_ROLE,
      this.role() === "dialog" ? null : this.role(),
    );
    setAttr(this.root, DIALOG_INITIAL_FOCUS, this.initialFocus() || null);
    setAttr(this.root, DIALOG_PORTAL_CONTAINER, this.portalContainer() || null);
  }

  private resolvePortalContainer(): HTMLElement | null {
    const selector = this.portalContainer();
    if (selector) {
      const target = this.root.ownerDocument.querySelector(selector);
      return target instanceof HTMLElement ? target : null;
    }
    return this.root.ownerDocument.body;
  }

  private mountPortal(): void {
    if (this.portaledNode) return;
    const portal = this.portal();
    const node = portal ?? this.content()?.parentElement;
    if (!node || node === this.root) return;
    const container = this.resolvePortalContainer();
    if (!container || node.parentNode === container) return;
    this.originalPortalParent = node.parentNode;
    this.originalPortalNextSibling = node.nextSibling;
    this.portalPlaceholder = this.root.ownerDocument.createComment(
      "bambi-dialog-portal",
    );
    this.originalPortalParent?.insertBefore(this.portalPlaceholder, node);
    container.appendChild(node);
    this.portaledNode = node;
  }

  private restorePortal(): void {
    const node = this.portaledNode;
    if (!node) return;
    if (this.originalPortalParent) {
      this.originalPortalParent.insertBefore(
        node,
        this.originalPortalNextSibling,
      );
    }
    this.portalPlaceholder?.remove();
    this.portaledNode = null;
    this.portalPlaceholder = null;
    this.originalPortalParent = null;
    this.originalPortalNextSibling = null;
  }

  private applyState(open: boolean): void {
    const wasOpen = this.currentOpen;
    this.currentOpen = open;
    const state = open ? "open" : "closed";
    setAttr(this.root, DIALOG_OPEN, open ? "true" : null);
    setAttr(this.root, DIALOG_STATE, state);

    if (open) this.mountPortal();

    const trigger = this.trigger();
    const content = this.content();
    const overlay = this.overlay();
    const portal = this.portal();

    if (trigger) {
      if (!trigger.id) trigger.id = `${this._id}-trigger`;
      trigger.setAttribute(DIALOG_TRIGGER, "");
      setAttr(trigger, DIALOG_STATE, state);
      setAttr(trigger, DIALOG_DISABLED, this.disabled() ? "true" : null);
      trigger.setAttribute("aria-haspopup", "dialog");
      trigger.setAttribute("aria-expanded", open ? "true" : "false");
      if (content)
        trigger.setAttribute(
          "aria-controls",
          content.id || `${this._id}-content`,
        );
      if (trigger instanceof HTMLButtonElement) {
        if (!trigger.getAttribute("type")) trigger.type = "button";
        trigger.disabled = this.disabled();
      } else {
        setAttr(trigger, "aria-disabled", this.disabled() ? "true" : null);
      }
    }

    if (portal) {
      portal.setAttribute(DIALOG_PORTAL, "");
      setAttr(portal, DIALOG_STATE, state);
      portal.hidden = !open;
    }

    if (overlay) {
      overlay.setAttribute(DIALOG_OVERLAY, "");
      setAttr(overlay, DIALOG_STATE, state);
      overlay.hidden = !open;
    }

    if (content) {
      if (!content.id) content.id = `${this._id}-content`;
      content.setAttribute(DIALOG_CONTENT, "");
      content.setAttribute("role", this.role());
      setAttr(content, "aria-modal", this.modal() ? "true" : null);
      setAttr(content, DIALOG_STATE, state);
      content.hidden = !open;
      this.syncContentLabels(content);
    }

    this.syncCloseButtons(state);

    if (open && content) {
      if (!wasOpen || !this.dismissableLayer || !this.focusScope) {
        this.destroyLayerBehavior(false);
        this.createLayerBehavior(content);
      }
      if (this.modal()) this.hideOutsideTree();
    } else if (!open && wasOpen) {
      this.destroyLayerBehavior(true);
      this.restoreOutsideTree();
      this.restorePortal();
    }
  }

  private syncContentLabels(content: HTMLElement): void {
    const title = content.querySelector(`[${DIALOG_TITLE}]`);
    if (title instanceof HTMLElement) {
      if (!title.id) title.id = `${this._id}-title`;
      title.setAttribute(DIALOG_TITLE, "");
      content.setAttribute("aria-labelledby", title.id);
    }
    const description = content.querySelector(`[${DIALOG_DESCRIPTION}]`);
    if (description instanceof HTMLElement) {
      if (!description.id) description.id = `${this._id}-description`;
      description.setAttribute(DIALOG_DESCRIPTION, "");
      content.setAttribute("aria-describedby", description.id);
    }
  }

  private syncCloseButtons(state: "open" | "closed"): void {
    const scopes: Element[] = [this.root];
    if (this.portaledNode) scopes.push(this.portaledNode);
    for (const scope of scopes) {
      for (const close of scope.querySelectorAll(`[${DIALOG_CLOSE}]`)) {
        close.setAttribute(DIALOG_CLOSE, "");
        setAttr(close, DIALOG_STATE, state);
        if (close instanceof HTMLButtonElement && !close.getAttribute("type")) {
          close.type = "button";
        }
      }
    }
  }

  private setOpen(
    open: boolean,
    source: DialogOpenChangeDetail["source"],
  ): void {
    const previousOpen = this.currentOpen;
    if (previousOpen === open) return;
    if (!this.controlled()) this.applyState(open);
    dispatchBambiEvent(this.root, DIALOG_EVENT_OPEN_CHANGE, {
      open,
      previousOpen,
      source,
    });
  }

  private createLayerBehavior(content: HTMLElement): void {
    const signal = this.bindAbort.signal;
    this.dismissableLayer = createDismissableLayer(content, {
      modal: this.modal(),
      branches: [
        this.root,
        ...(this.overlay() ? [this.overlay() as Element] : []),
      ],
      onEscapeKeyDown: (event) => {
        const customEvent = dispatchCancelableEvent<DialogEscapeKeyDownDetail>(
          this.root,
          DIALOG_EVENT_ESCAPE_KEY_DOWN,
          { originalEvent: event },
        );
        if (customEvent.defaultPrevented) event.preventDefault();
        if (!customEvent.defaultPrevented) this.setOpen(false, "escape");
      },
      onPointerDownOutside: (event) => {
        this.handleOutsideEvent(event, DIALOG_EVENT_POINTER_DOWN_OUTSIDE);
      },
      onFocusOutside: (event) => {
        this.handleOutsideEvent(event, DIALOG_EVENT_INTERACT_OUTSIDE);
      },
      onDismiss: (event) => {
        if (event instanceof KeyboardEvent && event.key === "Escape") return;
        this.setOpen(false, "outside");
      },
    });
    this.focusScope = createFocusScope(content, {
      trapped: this.modal(),
      restoreFocus: true,
      autofocus: false,
      containers: [
        this.root,
        ...(this.overlay() ? [this.overlay() as Element] : []),
      ],
    });
    this.focusInitial(content);
    if (this.modal()) this.scrollLock = createScrollLock(content.ownerDocument);
    const clickScope = this.portaledNode ?? this.root;
    clickScope.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const close = target.closest(`[${DIALOG_CLOSE}]`);
        if (close && clickScope.contains(close)) this.setOpen(false, "close");
      },
      { signal },
    );
  }

  private handleOutsideEvent(
    event: DismissableLayerEvent,
    eventName: string,
  ): void {
    const detail: DialogPointerDownOutsideDetail | DialogInteractOutsideDetail =
      {
        originalEvent: event.detail.originalEvent,
      };
    const customEvent = dispatchCancelableEvent<DialogOutsideInteractionDetail>(
      this.root,
      eventName,
      detail,
    );
    if (customEvent.defaultPrevented) event.preventDefault();
  }

  private focusInitial(content: HTMLElement): void {
    const selector = this.initialFocus();
    if (selector) {
      const target = content.querySelector(selector);
      if (target instanceof HTMLElement) {
        queueMicrotask(() => target.focus({ preventScroll: true }));
        return;
      }
    }
    this.focusScope?.focusFirst();
  }

  private destroyLayerBehavior(restoreFocus: boolean): void {
    this.dismissableLayer?.destroy();
    this.scrollLock?.destroy();
    if (restoreFocus) this.focusScope?.destroy();
    else {
      const scope = this.focusScope;
      this.focusScope = null;
      scope?.destroy();
    }
    this.dismissableLayer = null;
    this.focusScope = null;
    this.scrollLock = null;
  }

  private hideOutsideTree(): void {
    if (this.hiddenSiblings.length > 0) return;
    const ownerDocument = this.root.ownerDocument;
    const keep = this.portaledNode ?? this.root;
    for (const child of Array.from(ownerDocument.body.children)) {
      if (!(child instanceof HTMLElement)) continue;
      if (child === keep || child.contains(keep) || keep.contains(child))
        continue;
      this.hiddenSiblings.push({
        element: child,
        ariaHidden: child.getAttribute("aria-hidden"),
        inert: child.inert,
      });
      child.setAttribute("aria-hidden", "true");
      child.inert = true;
    }
  }

  private restoreOutsideTree(): void {
    for (const state of this.hiddenSiblings) {
      if (state.ariaHidden === null)
        state.element.removeAttribute("aria-hidden");
      else state.element.setAttribute("aria-hidden", state.ariaHidden);
      state.element.inert = state.inert;
    }
    this.hiddenSiblings = [];
  }

  private bindEvents(): void {
    const signal = this.bindAbort.signal;
    this.root.addEventListener(
      "click",
      (event) => {
        const target = event.target;
        if (!(target instanceof Element)) return;
        const trigger = target.closest(`[${DIALOG_TRIGGER}]`);
        if (trigger && this.root.contains(trigger)) {
          if (this.disabled()) return;
          this.setOpen(true, "trigger");
          return;
        }
        const close = target.closest(`[${DIALOG_CLOSE}]`);
        if (close && this.root.contains(close)) this.setOpen(false, "close");
      },
      { signal },
    );
  }
}

export interface DialogProps extends Omit<DialogOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<DialogOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onOpenChange?: (detail: DialogOpenChangeDetail) => void;
  onEscapeKeyDown?: (detail: DialogEscapeKeyDownDetail) => void;
  onPointerDownOutside?: (detail: DialogPointerDownOutsideDetail) => void;
  onInteractOutside?: (detail: DialogInteractOutsideDetail) => void;
}

export interface DialogTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  disabled?: boolean;
}

export type DialogPortalProps = React.ComponentPropsWithoutRef<"div">;

export type DialogOverlayProps = React.ComponentPropsWithoutRef<"div">;

export type DialogContentProps = React.ComponentPropsWithoutRef<"div">;

export type DialogTitleProps = React.ComponentPropsWithoutRef<"h2">;

export type DialogDescriptionProps = React.ComponentPropsWithoutRef<"p">;

export type DialogCloseProps = React.ComponentPropsWithoutRef<"button">;

export function Dialog({
  open,
  defaultOpen,
  modal,
  disabled,
  role = "dialog",
  initialFocus,
  portalContainer,
  onOpenChange,
  onEscapeKeyDown,
  onPointerDownOutside,
  onInteractOutside,
  children,
  ...props
}: DialogProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<DialogBehavior | null>(null);
  const controlled = open !== undefined;
  const onOpenChangeRef = React.useRef(onOpenChange);
  const onEscapeKeyDownRef = React.useRef(onEscapeKeyDown);
  const onPointerDownOutsideRef = React.useRef(onPointerDownOutside);
  const onInteractOutsideRef = React.useRef(onInteractOutside);

  React.useEffect(() => {
    if (open !== undefined && defaultOpen !== undefined) {
      console.warn(
        "[bambiui/dialog] Dialog received both `open` and `defaultOpen`. Use `open` for controlled mode or `defaultOpen` for uncontrolled mode, not both.",
      );
    }
  }, [defaultOpen, open]);
  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  React.useEffect(() => {
    onEscapeKeyDownRef.current = onEscapeKeyDown;
  }, [onEscapeKeyDown]);

  React.useEffect(() => {
    onPointerDownOutsideRef.current = onPointerDownOutside;
  }, [onPointerDownOutside]);

  React.useEffect(() => {
    onInteractOutsideRef.current = onInteractOutside;
  }, [onInteractOutside]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onOpenChangeHandler = (event: Event) => {
      const e = event as CustomEvent<DialogOpenChangeDetail>;
      onOpenChangeRef.current?.(e.detail);
    };
    root.addEventListener(DIALOG_EVENT_OPEN_CHANGE, onOpenChangeHandler);
    const onEscapeKeyDownHandler = (event: Event) => {
      const e = event as CustomEvent<DialogEscapeKeyDownDetail>;
      onEscapeKeyDownRef.current?.(e.detail);
    };
    root.addEventListener(DIALOG_EVENT_ESCAPE_KEY_DOWN, onEscapeKeyDownHandler);
    const onPointerDownOutsideHandler = (event: Event) => {
      const e = event as CustomEvent<DialogPointerDownOutsideDetail>;
      onPointerDownOutsideRef.current?.(e.detail);
    };
    root.addEventListener(DIALOG_EVENT_POINTER_DOWN_OUTSIDE, onPointerDownOutsideHandler);
    const onInteractOutsideHandler = (event: Event) => {
      const e = event as CustomEvent<DialogInteractOutsideDetail>;
      onInteractOutsideRef.current?.(e.detail);
    };
    root.addEventListener(DIALOG_EVENT_INTERACT_OUTSIDE, onInteractOutsideHandler);

    const behavior = new DialogBehavior(root, {
      open,
      defaultOpen,
      modal,
      disabled,
      role,
      initialFocus,
      portalContainer,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(DIALOG_EVENT_OPEN_CHANGE, onOpenChangeHandler);
      root.removeEventListener(DIALOG_EVENT_ESCAPE_KEY_DOWN, onEscapeKeyDownHandler);
      root.removeEventListener(DIALOG_EVENT_POINTER_DOWN_OUTSIDE, onPointerDownOutsideHandler);
      root.removeEventListener(DIALOG_EVENT_INTERACT_OUTSIDE, onInteractOutsideHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      open,
      defaultOpen,
      modal,
      disabled,
      role,
      initialFocus,
      portalContainer,
      controlled,
    });
  }, [open, defaultOpen, modal, disabled, role, initialFocus, portalContainer, controlled]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [DIALOG_ROOT]: "" }}
      {...{ [DIALOG_OPEN]: open ? "true" : undefined }}
      {...{ [DIALOG_DEFAULT_OPEN]: defaultOpen ? "true" : undefined }}
      {...{ [DIALOG_MODAL]: modal ? "true" : undefined }}
      {...{ [DIALOG_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DIALOG_ROLE]: role }}
      {...{ [DIALOG_INITIAL_FOCUS]: initialFocus }}
      {...{ [DIALOG_PORTAL_CONTAINER]: portalContainer }}
      {...{ [DIALOG_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );
}

export function DialogTrigger({ disabled, children, ...props }: DialogTriggerProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [DIALOG_DISABLED]: disabled ? "true" : undefined }}
      {...{ [DIALOG_TRIGGER]: "" }}
    >
      {children}
    </button>
  );
}

export function DialogPortal({ children, ...props }: DialogPortalProps) {

  return (
    <div
      {...props}
      {...{ [DIALOG_PORTAL]: "" }}
    >
      {children}
    </div>
  );
}

export function DialogOverlay({ children, ...props }: DialogOverlayProps) {

  return (
    <div
      {...props}
      {...{ [DIALOG_OVERLAY]: "" }}
    >
      {children}
    </div>
  );
}

export function DialogContent({ children, ...props }: DialogContentProps) {

  return (
    <div
      {...props}
      {...{ [DIALOG_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function DialogTitle({ children, ...props }: DialogTitleProps) {

  return (
    <h2
      {...props}
      {...{ [DIALOG_TITLE]: "" }}
    >
      {children}
    </h2>
  );
}

export function DialogDescription({ children, ...props }: DialogDescriptionProps) {

  return (
    <p
      {...props}
      {...{ [DIALOG_DESCRIPTION]: "" }}
    >
      {children}
    </p>
  );
}

export function DialogClose({ children, ...props }: DialogCloseProps) {

  return (
    <button
      {...props}
      type={props.type ?? "button"}
      {...{ [DIALOG_CLOSE]: "" }}
    >
      {children}
    </button>
  );
}
