// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const CALLOUT_ROOT = "data-bambi-callout" as const;
const CALLOUT_ICON = "data-bambi-callout-icon" as const;
const CALLOUT_TITLE = "data-bambi-callout-title" as const;
const CALLOUT_DESCRIPTION = "data-bambi-callout-description" as const;
const CALLOUT_VARIANT = "data-variant" as const;

export type CalloutVariant = "info" | "success" | "warning" | "danger" | "neutral";


export interface CalloutOptions {
  variant?: CalloutVariant;
}

class CalloutBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: CalloutOptions;

  constructor(root: Element, options: CalloutOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: CalloutOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(CALLOUT_ROOT, "");
    for (const part of this.root.querySelectorAll(`[${CALLOUT_ICON}]`)) part.setAttribute(CALLOUT_ICON, "");
    for (const part of this.root.querySelectorAll(`[${CALLOUT_TITLE}]`)) part.setAttribute(CALLOUT_TITLE, "");
    for (const part of this.root.querySelectorAll(`[${CALLOUT_DESCRIPTION}]`)) part.setAttribute(CALLOUT_DESCRIPTION, "");
    const variant = this.options.variant ?? getAttr(this.root, CALLOUT_VARIANT, "info") as CalloutVariant;
    setAttr(this.root, CALLOUT_VARIANT, variant);
    if (!this.root.hasAttribute("role")) this.root.setAttribute("role", variant === "danger" || variant === "warning" ? "alert" : "status");
  }
}

export interface CalloutProps extends CalloutOptions, Omit<React.ComponentPropsWithoutRef<"div">, keyof CalloutOptions> {
  children?: React.ReactNode;
  className?: string;
}

export type CalloutIconProps = React.ComponentPropsWithoutRef<"div">;

export type CalloutTitleProps = React.ComponentPropsWithoutRef<"div">;

export type CalloutDescriptionProps = React.ComponentPropsWithoutRef<"div">;

export function Callout({
  variant = "info",
  children,
  ...props
}: CalloutProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<CalloutBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new CalloutBehavior(root, {
      variant,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      variant,
    });
  }, [variant]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [CALLOUT_ROOT]: "" }}
      {...{ [CALLOUT_VARIANT]: variant }}
    >
      {children}
    </div>
  );
}

export function CalloutIcon({ children, ...props }: CalloutIconProps) {

  return (
    <div
      {...props}
      {...{ [CALLOUT_ICON]: "" }}
    >
      {children}
    </div>
  );
}

export function CalloutTitle({ children, ...props }: CalloutTitleProps) {

  return (
    <div
      {...props}
      {...{ [CALLOUT_TITLE]: "" }}
    >
      {children}
    </div>
  );
}

export function CalloutDescription({ children, ...props }: CalloutDescriptionProps) {

  return (
    <div
      {...props}
      {...{ [CALLOUT_DESCRIPTION]: "" }}
    >
      {children}
    </div>
  );
}
