// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const KBD_ROOT = "data-bambi-kbd" as const;
const KBD_SIZE = "data-size" as const;

export type KbdSize = "sm" | "md" | "lg";


export interface KbdOptions {
  size?: KbdSize;
}

class KbdBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: KbdOptions;

  constructor(root: Element, options: KbdOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: KbdOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(KBD_ROOT, "");
    const size = this.options.size ?? getAttr(this.root, KBD_SIZE, "sm") as KbdSize;
    setAttr(this.root, KBD_SIZE, size);
  }
}

export interface KbdProps extends KbdOptions, Omit<React.ComponentPropsWithoutRef<"kbd">, keyof KbdOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Kbd({
  size = "sm",
  children,
  ...props
}: KbdProps) {
  const rootRef = React.useRef<HTMLElement>(null);
  const behaviorRef = React.useRef<KbdBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new KbdBehavior(root, {
      size,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      size,
    });
  }, [size]);

  return (
    <kbd
      {...props}
      ref={rootRef}
      {...{ [KBD_ROOT]: "" }}
      {...{ [KBD_SIZE]: size }}
    >
      {children}
    </kbd>
  );
}
