// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const BADGE_ROOT = "data-bambi-badge" as const;
const BADGE_VARIANT = "data-variant" as const;
const BADGE_SIZE = "data-size" as const;

export type BadgeVariant = "default" | "secondary" | "outline" | "danger" | "success" | "warning";
export type BadgeSize = "sm" | "md" | "lg";


export interface BadgeOptions {
  variant?: BadgeVariant;
  size?: BadgeSize;
}

class BadgeBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: BadgeOptions;

  constructor(root: Element, options: BadgeOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: BadgeOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(BADGE_ROOT, "");
    const variant = this.options.variant ?? getAttr(this.root, BADGE_VARIANT, "default") as BadgeVariant;
    setAttr(this.root, BADGE_VARIANT, variant);
    const size = this.options.size ?? getAttr(this.root, BADGE_SIZE, "sm") as BadgeSize;
    setAttr(this.root, BADGE_SIZE, size);
  }
}

export interface BadgeProps extends BadgeOptions, Omit<React.ComponentPropsWithoutRef<"span">, keyof BadgeOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Badge({
  variant = "default",
  size = "sm",
  children,
  ...props
}: BadgeProps) {
  const rootRef = React.useRef<HTMLSpanElement>(null);
  const behaviorRef = React.useRef<BadgeBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new BadgeBehavior(root, {
      variant,
      size,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      variant,
      size,
    });
  }, [variant, size]);

  return (
    <span
      {...props}
      ref={rootRef}
      {...{ [BADGE_ROOT]: "" }}
      {...{ [BADGE_VARIANT]: variant }}
      {...{ [BADGE_SIZE]: size }}
    >
      {children}
    </span>
  );
}
