// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const INPUT_ROOT = "data-bambi-input" as const;
const INPUT_SIZE = "data-size" as const;
const INPUT_VARIANT = "data-variant" as const;
const INPUT_DISABLED = "data-disabled" as const;
const INPUT_REQUIRED = "data-required" as const;
const INPUT_INVALID = "data-invalid" as const;
const INPUT_READONLY = "data-readonly" as const;

export type InputSize = "sm" | "md" | "lg";
export type InputVariant = "default" | "ghost";


export interface InputOptions {
  size?: InputSize;
  variant?: InputVariant;
  disabled?: boolean;
  required?: boolean;
  invalid?: boolean;
  readOnly?: boolean;
}

class InputBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: InputOptions;

  constructor(root: Element, options: InputOptions = {}) {
    this.root = root;
    this.options = options;
  }

  sync(): void {
    this.applyState();
  }

  update(options: InputOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.applyState();
  }

  destroy(): void {}

  private applyState(): void {
    const size = this.options.size ?? (getAttr(this.root, INPUT_SIZE, "md") as InputSize);
    const variant = this.options.variant ?? (getAttr(this.root, INPUT_VARIANT, "default") as InputVariant);
    const disabled = this.options.disabled ?? getBoolAttr(this.root, INPUT_DISABLED);
    const required = this.options.required ?? getBoolAttr(this.root, INPUT_REQUIRED);
    const invalid = this.options.invalid ?? getBoolAttr(this.root, INPUT_INVALID);
    const readOnly = this.options.readOnly ?? getBoolAttr(this.root, INPUT_READONLY);

    this.root.setAttribute(INPUT_ROOT, "");
    setAttr(this.root, INPUT_SIZE, size);
    setAttr(this.root, INPUT_VARIANT, variant);
    setAttr(this.root, INPUT_DISABLED, disabled ? "true" : null);
    setAttr(this.root, INPUT_REQUIRED, required ? "true" : null);
    setAttr(this.root, INPUT_INVALID, invalid ? "true" : null);
    setAttr(this.root, INPUT_READONLY, readOnly ? "true" : null);
    setAttr(this.root, "aria-invalid", invalid ? "true" : null);

    if (this.root instanceof HTMLInputElement) {
      this.root.disabled = disabled;
      this.root.required = required;
      this.root.readOnly = readOnly;
    } else {
      setAttr(this.root, "aria-disabled", disabled ? "true" : null);
      setAttr(this.root, "aria-required", required ? "true" : null);
      setAttr(this.root, "aria-readonly", readOnly ? "true" : null);
    }
  }
}

export interface InputProps extends InputOptions, Omit<React.ComponentPropsWithoutRef<"input">, keyof InputOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Input({
  size = "md",
  variant = "default",
  disabled,
  required,
  invalid,
  readOnly,
  children,
  ...props
}: InputProps) {
  const rootRef = React.useRef<HTMLInputElement>(null);
  const behaviorRef = React.useRef<InputBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new InputBehavior(root, {
      size,
      variant,
      disabled,
      required,
      invalid,
      readOnly,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      size,
      variant,
      disabled,
      required,
      invalid,
      readOnly,
    });
  }, [size, variant, disabled, required, invalid, readOnly]);

  return (
    <input
      {...props}
      ref={rootRef}
      {...{ [INPUT_ROOT]: "" }}
      {...{ [INPUT_SIZE]: size }}
      {...{ [INPUT_VARIANT]: variant }}
      {...{ [INPUT_DISABLED]: disabled ? "true" : undefined }}
      {...{ [INPUT_REQUIRED]: required ? "true" : undefined }}
      {...{ [INPUT_INVALID]: invalid ? "true" : undefined }}
      {...{ [INPUT_READONLY]: readOnly ? "true" : undefined }}
    >
      {children}
    </input>
  );
}
