// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const TEXTAREA_ROOT = "data-bambi-textarea" as const;
const TEXTAREA_SIZE = "data-size" as const;
const TEXTAREA_VARIANT = "data-variant" as const;
const TEXTAREA_DISABLED = "data-disabled" as const;
const TEXTAREA_REQUIRED = "data-required" as const;
const TEXTAREA_INVALID = "data-invalid" as const;
const TEXTAREA_READONLY = "data-readonly" as const;
const TEXTAREA_RESIZE = "data-resize" as const;

export type TextareaSize = "sm" | "md" | "lg";
export type TextareaVariant = "default" | "ghost";
export type TextareaResize = "none" | "vertical" | "horizontal" | "both";


export interface TextareaOptions {
  size?: TextareaSize;
  variant?: TextareaVariant;
  disabled?: boolean;
  required?: boolean;
  invalid?: boolean;
  readOnly?: boolean;
  resize?: TextareaResize;
}

class TextareaBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: TextareaOptions;

  constructor(root: Element, options: TextareaOptions = {}) {
    this.root = root;
    this.options = options;
  }

  sync(): void {
    this.applyState();
  }

  update(options: TextareaOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.applyState();
  }

  destroy(): void {}

  private applyState(): void {
    const size = this.options.size ?? (getAttr(this.root, TEXTAREA_SIZE, "md") as TextareaSize);
    const variant = this.options.variant ?? (getAttr(this.root, TEXTAREA_VARIANT, "default") as TextareaVariant);
    const disabled = this.options.disabled ?? getBoolAttr(this.root, TEXTAREA_DISABLED);
    const required = this.options.required ?? getBoolAttr(this.root, TEXTAREA_REQUIRED);
    const invalid = this.options.invalid ?? getBoolAttr(this.root, TEXTAREA_INVALID);
    const readOnly = this.options.readOnly ?? getBoolAttr(this.root, TEXTAREA_READONLY);
    const resize = this.options.resize ?? (getAttr(this.root, TEXTAREA_RESIZE, "vertical") as TextareaResize);

    this.root.setAttribute(TEXTAREA_ROOT, "");
    setAttr(this.root, TEXTAREA_SIZE, size);
    setAttr(this.root, TEXTAREA_VARIANT, variant);
    setAttr(this.root, TEXTAREA_DISABLED, disabled ? "true" : null);
    setAttr(this.root, TEXTAREA_REQUIRED, required ? "true" : null);
    setAttr(this.root, TEXTAREA_INVALID, invalid ? "true" : null);
    setAttr(this.root, TEXTAREA_READONLY, readOnly ? "true" : null);
    setAttr(this.root, TEXTAREA_RESIZE, resize);
    setAttr(this.root, "aria-invalid", invalid ? "true" : null);

    if (this.root instanceof HTMLTextAreaElement) {
      this.root.disabled = disabled;
      this.root.required = required;
      this.root.readOnly = readOnly;
    } else {
      setAttr(this.root, "aria-disabled", disabled ? "true" : null);
      setAttr(this.root, "aria-required", required ? "true" : null);
      setAttr(this.root, "aria-readonly", readOnly ? "true" : null);
    }
  }
}

export interface TextareaProps extends TextareaOptions, Omit<React.ComponentPropsWithoutRef<"textarea">, keyof TextareaOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Textarea({
  size = "md",
  variant = "default",
  disabled,
  required,
  invalid,
  readOnly,
  resize = "vertical",
  children,
  ...props
}: TextareaProps) {
  const rootRef = React.useRef<HTMLTextAreaElement>(null);
  const behaviorRef = React.useRef<TextareaBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new TextareaBehavior(root, {
      size,
      variant,
      disabled,
      required,
      invalid,
      readOnly,
      resize,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      size,
      variant,
      disabled,
      required,
      invalid,
      readOnly,
      resize,
    });
  }, [size, variant, disabled, required, invalid, readOnly, resize]);

  return (
    <textarea
      {...props}
      ref={rootRef}
      {...{ [TEXTAREA_ROOT]: "" }}
      {...{ [TEXTAREA_SIZE]: size }}
      {...{ [TEXTAREA_VARIANT]: variant }}
      {...{ [TEXTAREA_DISABLED]: disabled ? "true" : undefined }}
      {...{ [TEXTAREA_REQUIRED]: required ? "true" : undefined }}
      {...{ [TEXTAREA_INVALID]: invalid ? "true" : undefined }}
      {...{ [TEXTAREA_READONLY]: readOnly ? "true" : undefined }}
      {...{ [TEXTAREA_RESIZE]: resize }}
    >
      {children}
    </textarea>
  );
}
