// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const SEPARATOR_ROOT = "data-bambi-separator" as const;
const SEPARATOR_ORIENTATION = "data-orientation" as const;
const SEPARATOR_DECORATIVE = "data-decorative" as const;

export type SeparatorOrientation = "horizontal" | "vertical";


export interface SeparatorOptions {
  orientation?: SeparatorOrientation;
  decorative?: boolean;
}

class SeparatorBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: SeparatorOptions;

  constructor(root: Element, options: SeparatorOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: SeparatorOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(SEPARATOR_ROOT, "");
    const orientation = this.options.orientation ?? getAttr(this.root, SEPARATOR_ORIENTATION, "horizontal") as SeparatorOrientation;
    setAttr(this.root, SEPARATOR_ORIENTATION, orientation);
    const decorative = this.options.decorative ?? getBoolAttr(this.root, SEPARATOR_DECORATIVE);
    setAttr(this.root, SEPARATOR_DECORATIVE, decorative ? "true" : null);
    if (decorative) { setAttr(this.root, "role", null); setAttr(this.root, "aria-hidden", "true"); setAttr(this.root, "aria-orientation", null); }
    else { this.root.setAttribute("role", "separator"); setAttr(this.root, "aria-hidden", null); this.root.setAttribute("aria-orientation", this.options.orientation ?? getAttr(this.root, SEPARATOR_ORIENTATION, "horizontal")); }
  }
}

export interface SeparatorProps extends SeparatorOptions, Omit<React.ComponentPropsWithoutRef<"div">, keyof SeparatorOptions> {
  children?: React.ReactNode;
  className?: string;
}



export function Separator({
  orientation = "horizontal",
  decorative,
  children,
  ...props
}: SeparatorProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<SeparatorBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new SeparatorBehavior(root, {
      orientation,
      decorative,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      orientation,
      decorative,
    });
  }, [orientation, decorative]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [SEPARATOR_ROOT]: "" }}
      {...{ [SEPARATOR_ORIENTATION]: orientation }}
      {...{ [SEPARATOR_DECORATIVE]: decorative ? "true" : undefined }}
    >
      {children}
    </div>
  );
}
