// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const CARD_ROOT = "data-bambi-card" as const;
const CARD_HEADER = "data-bambi-card-header" as const;
const CARD_TITLE = "data-bambi-card-title" as const;
const CARD_DESCRIPTION = "data-bambi-card-description" as const;
const CARD_CONTENT = "data-bambi-card-content" as const;
const CARD_FOOTER = "data-bambi-card-footer" as const;
const CARD_VARIANT = "data-variant" as const;
const CARD_SIZE = "data-size" as const;

export type CardVariant = "default" | "outline" | "ghost";
export type CardSize = "sm" | "md" | "lg";


export interface CardOptions {
  variant?: CardVariant;
  size?: CardSize;
}

class CardBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: CardOptions;

  constructor(root: Element, options: CardOptions = {}) {
    this.root = root;
    this.options = options;
  }
  sync(): void { this.applyState(); }
  update(options: CardOptions = {}): void { this.options = { ...this.options, ...options }; this.applyState(); }
  destroy(): void {}

  private applyState(): void {
    this.root.setAttribute(CARD_ROOT, "");
    for (const part of this.root.querySelectorAll(`[${CARD_HEADER}]`)) part.setAttribute(CARD_HEADER, "");
    for (const part of this.root.querySelectorAll(`[${CARD_TITLE}]`)) part.setAttribute(CARD_TITLE, "");
    for (const part of this.root.querySelectorAll(`[${CARD_DESCRIPTION}]`)) part.setAttribute(CARD_DESCRIPTION, "");
    for (const part of this.root.querySelectorAll(`[${CARD_CONTENT}]`)) part.setAttribute(CARD_CONTENT, "");
    for (const part of this.root.querySelectorAll(`[${CARD_FOOTER}]`)) part.setAttribute(CARD_FOOTER, "");
    const variant = this.options.variant ?? getAttr(this.root, CARD_VARIANT, "default") as CardVariant;
    setAttr(this.root, CARD_VARIANT, variant);
    const size = this.options.size ?? getAttr(this.root, CARD_SIZE, "sm") as CardSize;
    setAttr(this.root, CARD_SIZE, size);
  }
}

export interface CardProps extends CardOptions, Omit<React.ComponentPropsWithoutRef<"div">, keyof CardOptions> {
  children?: React.ReactNode;
  className?: string;
}

export type CardHeaderProps = React.ComponentPropsWithoutRef<"div">;

export type CardTitleProps = React.ComponentPropsWithoutRef<"h3">;

export type CardDescriptionProps = React.ComponentPropsWithoutRef<"p">;

export type CardContentProps = React.ComponentPropsWithoutRef<"div">;

export type CardFooterProps = React.ComponentPropsWithoutRef<"div">;

export function Card({
  variant = "default",
  size = "sm",
  children,
  ...props
}: CardProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<CardBehavior | null>(null);
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const behavior = new CardBehavior(root, {
      variant,
      size,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      variant,
      size,
    });
  }, [variant, size]);

  return (
    <div
      {...props}
      ref={rootRef}
      {...{ [CARD_ROOT]: "" }}
      {...{ [CARD_VARIANT]: variant }}
      {...{ [CARD_SIZE]: size }}
    >
      {children}
    </div>
  );
}

export function CardHeader({ children, ...props }: CardHeaderProps) {

  return (
    <div
      {...props}
      {...{ [CARD_HEADER]: "" }}
    >
      {children}
    </div>
  );
}

export function CardTitle({ children, ...props }: CardTitleProps) {

  return (
    <h3
      {...props}
      {...{ [CARD_TITLE]: "" }}
    >
      {children}
    </h3>
  );
}

export function CardDescription({ children, ...props }: CardDescriptionProps) {

  return (
    <p
      {...props}
      {...{ [CARD_DESCRIPTION]: "" }}
    >
      {children}
    </p>
  );
}

export function CardContent({ children, ...props }: CardContentProps) {

  return (
    <div
      {...props}
      {...{ [CARD_CONTENT]: "" }}
    >
      {children}
    </div>
  );
}

export function CardFooter({ children, ...props }: CardFooterProps) {

  return (
    <div
      {...props}
      {...{ [CARD_FOOTER]: "" }}
    >
      {children}
    </div>
  );
}
