// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import * as React from "react";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr, type RovingFocusOptions, type RovingFocus, createRovingFocus } from "../bambi-helpers";

const TABS_ROOT = "data-bambi-tabs" as const;
const TABS_LIST = "data-bambi-tabs-list" as const;
const TABS_TRIGGER = "data-bambi-tabs-trigger" as const;
const TABS_CONTENT = "data-bambi-tabs-content" as const;
const TABS_VALUE = "data-value" as const;
const TABS_DEFAULT_VALUE = "data-default-value" as const;
const TABS_CONTROLLED = "data-controlled" as const;
const TABS_ORIENTATION = "data-orientation" as const;
const TABS_ACTIVATION_MODE = "data-activation-mode" as const;
const TABS_DISABLED = "data-disabled" as const;
const TABS_STATE = "data-state" as const;
const TABS_EVENT_VALUE_CHANGE = "bambi:value-change" as const;

export type TabsOrientation = "horizontal" | "vertical";
export type TabsActivationMode = "automatic" | "manual";

export interface TabsValueChangeDetail {
  value: string;
  previousValue: string | null;
  source: "click" | "keyboard";
}



export interface TabsOptions {
  value?: string;
  defaultValue?: string;
  controlled?: boolean;
  orientation?: TabsOrientation;
  activationMode?: TabsActivationMode;
  disabled?: boolean;
}

function dispatchTabsEvent(
  element: Element,
  detail: TabsValueChangeDetail,
): void {
  element.dispatchEvent(
    new CustomEvent<TabsValueChangeDetail>(TABS_EVENT_VALUE_CHANGE, {
      bubbles: true,
      cancelable: false,
      composed: false,
      detail,
    }),
  );
}

class TabsBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: TabsOptions;
  private currentValue: string | null = null;
  private readonly _id: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private rovingFocus: RovingFocus | null = null;

  constructor(root: Element, options: TabsOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-tabs-${++TabsBehavior._idCounter}`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
    this.bindAbort = new AbortController();

    const orientation = (this.options.orientation ??
      getAttr(this.root, TABS_ORIENTATION, "horizontal")) as TabsOrientation;

    setAttr(this.root, TABS_ORIENTATION, orientation);
    setAttr(
      this.root,
      TABS_ACTIVATION_MODE,
      this.options.activationMode ??
        getAttr(this.root, TABS_ACTIVATION_MODE, "automatic"),
    );
    if (this.options.disabled !== undefined) {
      setAttr(this.root, TABS_DISABLED, this.options.disabled ? "true" : null);
    }

    this.syncTabLists(orientation);

    const value =
      (this.options.value ?? getAttr(this.root, TABS_VALUE, "")) ||
      (this.options.defaultValue ??
        getAttr(this.root, TABS_DEFAULT_VALUE, "")) ||
      this.firstTriggerValue();
    if (value) this.applyState(value);

    this.bindEvents();
  }

  update(options: TabsOptions = {}): void {
    const prev = this.options;
    this.options = { ...this.options, ...options };

    const orientation = (this.options.orientation ??
      getAttr(this.root, TABS_ORIENTATION, "horizontal")) as TabsOrientation;
    setAttr(this.root, TABS_ORIENTATION, orientation);
    setAttr(this.root, TABS_ACTIVATION_MODE, this.activationMode());
    if (this.options.disabled !== undefined) {
      setAttr(this.root, TABS_DISABLED, this.options.disabled ? "true" : null);
    }
    this.syncTabLists(orientation);

    if (
      options.orientation !== undefined &&
      options.orientation !== prev.orientation
    ) {
      this.rovingFocus?.destroy();
      this.rovingFocus = this.createRovingFocusInstance(orientation);
    }

    if (
      options.value !== undefined &&
      options.value !== prev.value &&
      options.value
    ) {
      this.applyState(options.value);
    } else if (this.currentValue) {
      this.applyState(this.currentValue);
    }
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
  }

  private firstTriggerValue(): string | null {
    return (
      this.root.querySelector(`[${TABS_TRIGGER}]`)?.getAttribute(TABS_VALUE) ??
      null
    );
  }

  private syncTabLists(orientation: TabsOrientation): void {
    for (const list of this.root.querySelectorAll(`[${TABS_LIST}]`)) {
      list.setAttribute("role", "tablist");
      list.setAttribute("aria-orientation", orientation);
    }
  }

  private triggers(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${TABS_TRIGGER}]`));
  }

  private contents(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${TABS_CONTENT}]`));
  }

  
  private applyState(newValue: string): void {
    const isControlled =
      this.options.controlled ?? getBoolAttr(this.root, TABS_CONTROLLED);

    if (!isControlled) setAttr(this.root, TABS_VALUE, newValue);
    this.currentValue = newValue;

    const triggers = this.triggers();
    const contents = this.contents();

    for (const trigger of triggers) {
      const val = trigger.getAttribute(TABS_VALUE) ?? "";
      if (!trigger.id) trigger.id = `${this._id}-trigger-${val}`;
      trigger.setAttribute("role", "tab");
      trigger.setAttribute("aria-controls", `${this._id}-content-${val}`);

      const isActive = val === newValue;
      setAttr(trigger, TABS_STATE, isActive ? "active" : "inactive");
      trigger.setAttribute("aria-selected", String(isActive));
      trigger.setAttribute("tabindex", isActive ? "0" : "-1");
      if (getBoolAttr(trigger, TABS_DISABLED)) {
        trigger.setAttribute("aria-disabled", "true");
      } else {
        trigger.removeAttribute("aria-disabled");
      }
    }

    for (const content of contents) {
      const val = content.getAttribute(TABS_VALUE) ?? "";
      if (!content.id) content.id = `${this._id}-content-${val}`;
      content.setAttribute("role", "tabpanel");
      content.setAttribute("aria-labelledby", `${this._id}-trigger-${val}`);
      if (!content.hasAttribute("tabindex"))
        content.setAttribute("tabindex", "0");

      const isActive = val === newValue;
      setAttr(content, TABS_STATE, isActive ? "active" : "inactive");
      if (isActive) {
        content.removeAttribute("hidden");
      } else {
        content.setAttribute("hidden", "");
      }
    }
  }

  
  private applyValue(newValue: string, source: "click" | "keyboard"): void {
    if (newValue === this.currentValue) return;

    const isControlled =
      this.options.controlled ?? getBoolAttr(this.root, TABS_CONTROLLED);
    const previousValue = this.currentValue;

    if (!isControlled) this.applyState(newValue);

    dispatchTabsEvent(this.root, { value: newValue, previousValue, source });
  }

  private activationMode(): TabsActivationMode {
    return (this.options.activationMode ??
      getAttr(
        this.root,
        TABS_ACTIVATION_MODE,
        "automatic",
      )) as TabsActivationMode;
  }

  private focusTrigger(trigger: Element): void {
    if (trigger instanceof HTMLElement) trigger.focus();
  }

  private activateFocusedTrigger(trigger: Element): void {
    const value = trigger.getAttribute(TABS_VALUE);
    if (value) this.applyValue(value, "keyboard");
  }

  private createRovingFocusInstance(orientation: TabsOrientation): RovingFocus {
    return createRovingFocus(this.root, {
      orientation,
      getItems: () => {
        if (this.options.disabled ?? getBoolAttr(this.root, TABS_DISABLED))
          return [];
        return this.triggers();
      },
      isDisabled: (el) =>
        getBoolAttr(el, TABS_DISABLED) ||
        el.getAttribute("aria-disabled") === "true",
      onFocus: (el) => {
        this.focusTrigger(el);
        if (this.activationMode() === "automatic")
          this.activateFocusedTrigger(el);
      },
      onActivate: (el) => this.activateFocusedTrigger(el),
    });
  }

  private bindEvents(): void {
    const { signal } = this.bindAbort;

    this.root.addEventListener(
      "click",
      (event: Event) => {
        const disabled =
          this.options.disabled ?? getBoolAttr(this.root, TABS_DISABLED);
        if (disabled) return;

        const target = (event.target as Element).closest(`[${TABS_TRIGGER}]`);
        if (!target || !this.root.contains(target)) return;

        const isDisabledTrigger =
          getBoolAttr(target, TABS_DISABLED) ||
          target.getAttribute("aria-disabled") === "true";
        if (isDisabledTrigger) return;

        const value = target.getAttribute(TABS_VALUE);
        if (!value) return;

        this.applyValue(value, "click");
      },
      { signal },
    );

    const orientation = (this.options.orientation ??
      getAttr(this.root, TABS_ORIENTATION, "horizontal")) as TabsOrientation;
    this.rovingFocus = this.createRovingFocusInstance(orientation);
  }
}


const SsrSelectedValueContext = React.createContext<string | string[] | undefined>(undefined);
export interface TabsProps extends Omit<TabsOptions, "controlled">, Omit<React.ComponentPropsWithoutRef<"div">, keyof Omit<TabsOptions, "controlled">> {
  children?: React.ReactNode;
  className?: string;
  onValueChange?: (detail: TabsValueChangeDetail) => void;
}

export type TabsListProps = React.ComponentPropsWithoutRef<"div">;

export interface TabsTriggerProps extends React.ComponentPropsWithoutRef<"button"> {
  value: string;
  disabled?: boolean;
}

export interface TabsContentProps extends React.ComponentPropsWithoutRef<"div"> {
  value: string;
}

export function Tabs({
  value,
  defaultValue,
  orientation = "horizontal",
  activationMode = "automatic",
  disabled,
  onValueChange,
  children,
  ...props
}: TabsProps) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const behaviorRef = React.useRef<TabsBehavior | null>(null);
  const controlled = value !== undefined;
  const selectedValue = value ?? defaultValue;
  const onValueChangeRef = React.useRef(onValueChange);

  React.useEffect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/tabs] Tabs received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  }, [defaultValue, value]);
  React.useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  React.useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const onValueChangeHandler = (event: Event) => {
      const e = event as CustomEvent<TabsValueChangeDetail>;
      onValueChangeRef.current?.(e.detail);
    };
    root.addEventListener(TABS_EVENT_VALUE_CHANGE, onValueChangeHandler);

    const behavior = new TabsBehavior(root, {
      value,
      defaultValue,
      orientation,
      activationMode,
      disabled,
      controlled,
    });
    behaviorRef.current = behavior;
    behavior.sync();

    return () => {
      root.removeEventListener(TABS_EVENT_VALUE_CHANGE, onValueChangeHandler);
      behaviorRef.current = null;
      behavior.destroy();
    };
  }, []);

  React.useEffect(() => {
    behaviorRef.current?.update?.({
      value,
      defaultValue,
      orientation,
      activationMode,
      disabled,
      controlled,
    });
  }, [value, defaultValue, orientation, activationMode, disabled, controlled]);

  const rootElement = (
    <div
      {...props}
      ref={rootRef}
      {...{ [TABS_ROOT]: "" }}
      {...{ [TABS_VALUE]: value }}
      {...{ [TABS_DEFAULT_VALUE]: defaultValue }}
      {...{ [TABS_ORIENTATION]: orientation }}
      {...{ [TABS_ACTIVATION_MODE]: activationMode }}
      {...{ [TABS_DISABLED]: disabled ? "true" : undefined }}
      {...{ [TABS_CONTROLLED]: controlled ? "true" : undefined }}
    >
      {children}
    </div>
  );

  return <SsrSelectedValueContext.Provider value={selectedValue}>{rootElement}</SsrSelectedValueContext.Provider>;
}

export function TabsList({ children, ...props }: TabsListProps) {

  return (
    <div
      {...props}
      {...{ [TABS_LIST]: "" }}
    >
      {children}
    </div>
  );
}

export function TabsTrigger({ value, disabled, children, ...props }: TabsTriggerProps) {

  const selectedValue = React.useContext(SsrSelectedValueContext);
  const hasSelectedValue = selectedValue !== undefined;
  const isSelected = Array.isArray(selectedValue) ? selectedValue.includes(value) : selectedValue === value;
  return (
    <button
      {...props}
      type={props.type ?? "button"}
      disabled={disabled}
      {...{ [TABS_DISABLED]: disabled ? "true" : undefined }}
      {...{ [TABS_TRIGGER]: "" }}
      {...{ [TABS_VALUE]: value }}
      role={"tab"}
      data-state={hasSelectedValue ? (isSelected ? "active" : "inactive") : undefined}
      aria-selected={hasSelectedValue ? (isSelected ? true : false) : undefined}
      tabIndex={hasSelectedValue ? (isSelected ? 0 : -1) : undefined}
    >
      {children}
    </button>
  );
}

export function TabsContent({ value, children, ...props }: TabsContentProps) {

  const selectedValue = React.useContext(SsrSelectedValueContext);
  const hasSelectedValue = selectedValue !== undefined;
  const isSelected = Array.isArray(selectedValue) ? selectedValue.includes(value) : selectedValue === value;
  return (
    <div
      {...props}
      {...{ [TABS_CONTENT]: "" }}
      {...{ [TABS_VALUE]: value }}
      role={"tabpanel"}
      data-state={hasSelectedValue ? (isSelected ? "active" : "inactive") : undefined}
      hidden={hasSelectedValue ? (isSelected ? false : true) : undefined}
    >
      {children}
    </div>
  );
}
